/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCopying.h"
#import "Twitter-Structs.h"
#import "NSObject.h"

@class NSString;

@protocol ABActiveTextRange <NSObject, NSCopying>
@property(readonly, assign, nonatomic) NSRange rangeValue;
@property(readonly, assign, nonatomic) int rangeFlavor;
@property(readonly, assign, nonatomic) NSString* displayString;
@end

