/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface ABActiveTextRanges : NSObject {
@private
	NSArray* links;
	NSArray* hashtags;
	NSArray* usernames;
	NSArray* lists;
	NSArray* stockSymbols;
	NSArray* emailAddresses;
	NSArray* activeRanges;
}
@property(readonly, assign, nonatomic) NSArray* links;
@property(readonly, assign, nonatomic) NSArray* hashtags;
@property(readonly, assign, nonatomic) NSArray* usernames;
@property(readonly, assign, nonatomic) NSArray* lists;
@property(readonly, assign, nonatomic) NSArray* stockSymbols;
@property(readonly, assign, nonatomic) NSArray* emailAddresses;
@property(readonly, assign, nonatomic) NSArray* activeRanges;
-(id)initWithString:(id)string;
-(void)dealloc;
@end

