/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIPopoverController.h>

@class ABAutocompleteTableView, UITextView;

__attribute__((visibility("hidden")))
@interface ABAutocompletePopover : UIPopoverController {
@private
	UITextView* textView;
	BOOL autocompleting;
}
@property(assign, nonatomic) UITextView* textView;
@property(readonly, assign, nonatomic) ABAutocompleteTableView* tableView;
-(id)init;
-(BOOL)updateAutocomplete;
-(BOOL)endAutocomplete;
@end

