/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>

@class ABAutocompleteTableView;

__attribute__((visibility("hidden")))
@interface ABAutocompletePopoverContentViewController : UIViewController {
@private
	ABAutocompleteTableView* _tableView;
}
-(void)loadView;
-(void)viewWillAppear:(BOOL)view;
@end

