/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class UITextView, ABAutocompleteTableView;

__attribute__((visibility("hidden")))
@interface ABAutocompleteView : UIView {
@private
	UITextView* textView;
	ABAutocompleteTableView* _tableView;
	BOOL autocompleting;
}
@property(assign, nonatomic) UITextView* textView;
@property(readonly, assign, nonatomic) ABAutocompleteTableView* tableView;
-(id)initWithFrame:(CGRect)frame;
-(void)_scrollSelectionToVisible;
-(BOOL)updateAutocomplete;
-(BOOL)endAutocomplete;
@end

