/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface ABCallback : NSObject {
@private
	id target;
	SEL selector;
	id info;
}
@property(readonly, assign, nonatomic) id target;
@property(readonly, assign, nonatomic) SEL selector;
@property(readonly, assign, nonatomic) id info;
+(id)callbackWithTarget:(id)target selector:(SEL)selector info:(id)info;
-(id)initWithTarget:(id)target selector:(SEL)selector info:(id)info;
-(void)dealloc;
-(void)invoke:(id)invoke;
-(void)dissociateTarget;
-(id)description;
@end

