/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class NSArray, ABColumnItem, UIToolbar;

__attribute__((visibility("hidden")))
@interface ABColumnBar : UIView {
@private
	id delegate;
	NSArray* items;
	ABColumnItem* _dummyBackToRootItem;
	UIView* currentBackButtonView;
	UIView* currentLeftTitleView;
	UIView* currentRightTitleView;
	struct {
		NSArray* removeViews;
	} transition;
	UIView* divider;
	UIToolbar* toolbar;
}
@property(assign, nonatomic) id delegate;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(id)backItem;
-(id)leftItem;
-(id)rightItem;
-(CGRect)backButtonFrame:(CGRect)frame;
-(CGRect)leftTitleFrame;
-(CGRect)dividerFrame;
-(CGRect)rightTitleFrame;
-(CGRect)toolbarFrame;
-(void)_updateLayout;
-(void)layoutSubviews;
-(void)pop:(id)pop;
-(void)_updateToolbarItems:(id)items animated:(BOOL)animated;
-(void)_itemDidUpdate:(id)_item;
-(void)setItems:(id)items animated:(BOOL)animated;
-(void)_finishTransition;
-(void)endSetItemsAnimation:(id)animation finished:(id)finished context:(void*)context;
@end

