/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "ABImage.h"

@class UIImage;

__attribute__((visibility("hidden")))
@interface ABConcreteImage : ABImage {
@private
	UIImage* uiImage;
	CGImageRef CGImage;
}
-(id)init;
-(id)initWithUIImage:(id)uiimage;
-(id)initWithCGImage:(CGImageRef)cgimage;
-(void)dealloc;
-(CGSize)size;
-(CGImageRef)CGImage;
-(id)uiImage;
-(void)drawInContext:(CGContextRef)context inRect:(CGRect)rect flipped:(BOOL)flipped;
-(void)drawInContext:(CGContextRef)context inRect:(CGRect)rect;
@end

