/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>


__attribute__((visibility("hidden")))
@interface ABDarkProgressBar : UIView {
@private
	float progress;
}
@property(assign, nonatomic) float progress;
-(id)initWithFrame:(CGRect)frame;
-(void)drawRect:(CGRect)rect;
@end

