/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABProxy.h"


__attribute__((visibility("hidden")))
@interface ABDelayProxy : ABProxy {
@private
	double delay;
}
@property(assign, nonatomic) double delay;
-(void)forwardInvocation:(id)invocation;
-(void)performInvocationAfterDelay:(id)delay;
@end

