/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MFMailComposeViewControllerDelegate.h"
#import <Foundation/NSObject.h>

@class UINavigationController, NSString, NSArray;

__attribute__((visibility("hidden")))
@interface ABEmailComposer : NSObject <MFMailComposeViewControllerDelegate> {
@private
	NSArray* toRecipients;
	NSString* body;
	NSString* subject;
	BOOL isHTML;
	UINavigationController* sourceNavigationController;
}
@property(copy, nonatomic) NSArray* toRecipients;
@property(copy, nonatomic) NSString* body;
@property(copy, nonatomic) NSString* subject;
@property(assign, nonatomic) BOOL isHTML;
+(id)composer;
-(void)dealloc;
-(id)presentableViewController;
-(void)showFrom:(id)from;
-(void)mailComposeController:(id)controller didFinishWithResult:(int)result error:(id)error;
@end

