/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface ABFileManager : NSObject {
}
+(id)createDirectoryIfNonExistent:(id)existent;
+(id)directoryForSearchPath:(unsigned)searchPath;
+(id)cachesDirectory;
+(id)documentsDirectory;
+(id)subCacheDirectory:(id)directory;
+(id)subDocumentsDirectory:(id)directory;
+(id)multipartPOSTDataDirectory;
+(id)tweetieComposeAttachmentsDirectory;
+(id)tweetieProfileImageCacheDirectory;
+(id)databaseCacheDirectory;
+(id)miscCacheDirectory;
+(id)applicationStateDirectory;
+(id)storedStreamsDirectory;
@end

