/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>

@class UIView;

__attribute__((visibility("hidden")))
@interface ABGenericViewController : UIViewController {
@private
	UIView* containedView;
}
@property(retain, nonatomic) UIView* containedView;
-(void)dealloc;
-(void)loadView;
@end

