/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface ABGeocodeLocation : NSObject {
@private
	double latitude;
	double longitude;
	int accuracy;
	NSString* address;
}
@property(assign, nonatomic) double latitude;
@property(assign, nonatomic) double longitude;
@property(copy, nonatomic) NSString* address;
@property(assign, nonatomic) int accuracy;
-(void)dealloc;
-(void)parseXML:(id)xml info:(id)info;
-(double)accuracyInMeters;
@end

