/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSArray, NSError;

__attribute__((visibility("hidden")))
@interface ABGeocode : NSObject {
@private
	NSError* error;
	NSArray* geocodedLocations;
}
@property(retain, nonatomic) NSError* error;
@property(copy, nonatomic) NSArray* geocodedLocations;
+(void)geocode:(id)geocode callback:(id)callback;
-(void)dealloc;
-(void)parseXML:(id)xml info:(id)info;
-(void)geocodeResponse:(id)response info:(id)info;
@end

