/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface ABGPS : NSObject {
}
+(void)startMonitoringSignificantLocationChanges;
+(void)stopMonitoringSignificantLocationChanges;
+(id)lastSignificantLocation;
+(id)callbacks;
+(void)broadcast:(id)broadcast;
+(void)_startup;
+(void)_shutdown;
+(void)watchdog:(id)watchdog;
+(void)sleep;
+(void)wake;
+(id)beginGPSUpdates:(id)updates;
+(void)endGPSUpdates:(id)updates;
+(void)cancelGeocoder;
+(void)reverseGeocoder:(id)geocoder didFindPlacemark:(id)placemark;
+(void)reverseGeocoder:(id)geocoder didFailWithError:(id)error;
+(void)locationManager:(id)manager didFailWithError:(id)error;
+(BOOL)locationUpdatesAreProbablyDisabled;
+(void)locationManager:(id)manager didUpdateToLocation:(id)location fromLocation:(id)location3;
@end

