/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CLLocationManagerDelegate.h"
#import <Foundation/NSObject.h>

@class CLLocationManager, CLLocation;

__attribute__((visibility("hidden")))
@interface ABGPSSignificantLocationChangeMonitor : NSObject <CLLocationManagerDelegate> {
@private
	CLLocationManager* manager;
	CLLocation* lastLocation;
}
@property(retain, nonatomic) CLLocation* lastLocation;
+(id)sharedMonitor;
-(id)init;
-(void)start;
-(void)stop;
-(void)dealloc;
-(BOOL)supportsSignificantLocationChange;
-(void)locationManager:(id)manager didUpdateToLocation:(id)location fromLocation:(id)location3;
-(void)locationManager:(id)manager didFailWithError:(id)error;
@end

