/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABRowView.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface ABGroupedRowView : ABRowView {
@private
	UIView* container;
}
-(float)xOffset;
-(float)childWidth:(float)width;
-(id)childContainer;
@end

