/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UITextView.h>


__attribute__((visibility("hidden")))
@interface ABGrowingTextView : UITextView {
}
-(BOOL)isOneLine;
-(void)setBounds:(CGRect)bounds;
-(void)setContentOffset:(CGPoint)offset;
@end

