/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class UIColor;

__attribute__((visibility("hidden")))
@interface ABGradientView : UIView {
@private
	UIColor* a;
	UIColor* b;
}
@property(retain, nonatomic) UIColor* a;
@property(retain, nonatomic) UIColor* b;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
@end

