/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <Foundation/NSObject.h>

@class NSString, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ABHTTPMultipartFormData : NSObject <NSCoding> {
@private
	NSMutableArray* parts;
	NSString* dataFile;
	int dataLength;
}
-(id)init;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)addDataPart:(id)part name:(id)name;
-(void)addTextPart:(id)part name:(id)name;
-(void)addImageFile:(id)file name:(id)name;
-(void)addVideoFile:(id)file name:(id)name;
-(id)boundary;
-(id)contentTypeHeader;
-(void)_writeData:(id)data toFileHandle:(id)fileHandle;
-(id)dataInputStream;
-(int)dataInputLength;
-(void)cleanup;
@end

