/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface ABImageService : NSObject {
}
+(id)service;
+(id)fullSizeImageURLForURL:(id)url;
+(id)thumbnailImageURLForURL:(id)url;
+(BOOL)isImageServiceLink:(id)link;
+(BOOL)entitiesMightContainMedia:(id)media;
+(BOOL)stringMightContainMedia:(id)media;
+(id)isVideoServiceLink:(id)link;
+(BOOL)isMediaLink:(id)link;
+(BOOL)isHotLink:(id)link;
+(BOOL)isYFrogImageLink:(id)link;
+(BOOL)isTwitPicLink:(id)link;
+(BOOL)isTwitgooLink:(id)link;
+(BOOL)isImglyLink:(id)link;
+(BOOL)isPixImLink:(id)link;
+(BOOL)isTweetphotoLink:(id)link;
+(BOOL)isPikchurLink:(id)link;
+(BOOL)isMobypictureLink:(id)link;
+(id)currentService;
+(int)approximateImageLinkLength;
+(int)approximateVideoLinkLength;
+(void)postImage:(id)image associatedMessage:(id)message fromAccount:(id)account callback:(id)callback;
+(id)currentVideoService;
+(void)postVideo:(id)video associatedMessage:(id)message fromAccount:(id)account callback:(id)callback;
-(void)postImage:(id)image associatedMessage:(id)message fromAccount:(id)account callback:(id)callback;
-(void)postVideo:(id)video associatedMessage:(id)message fromAccount:(id)account callback:(id)callback;
@end

