/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface ABImage : NSObject {
}
@property(readonly, assign, nonatomic) UIImage* uiImage;
@property(readonly, assign, nonatomic) CGImageRef CGImage;
@property(readonly, assign, nonatomic) CGSize size;
+(id)imageNamed:(id)named;
+(id)imageWithData:(id)data;
+(id)imageWithCGImage:(CGImageRef)cgimage;
+(id)imageWithUIImage:(id)uiimage;
-(id)imageData;
-(id)stretchableImageWithLeftCapWidth:(int)leftCapWidth topCapHeight:(int)height;
-(int)leftCapWidth;
-(int)topCapHeight;
-(void)drawInContext:(CGContextRef)context inRect:(CGRect)rect flipped:(BOOL)flipped;
-(void)drawInContext:(CGContextRef)context inRect:(CGRect)rect;
@end

