/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSError, NSString;

__attribute__((visibility("hidden")))
@interface ABLanguageTranslator : NSObject {
@private
	NSString* translatedText;
	NSError* error;
}
@property(copy, nonatomic) NSString* translatedText;
@property(retain, nonatomic) NSError* error;
+(id)apiKey;
+(id)apiRoot;
+(void)translate:(id)translate from:(id)from to:(id)to callback:(id)callback;
+(void)translate:(id)translate from:(id)from callback:(id)callback;
+(void)translate:(id)translate callback:(id)callback;
-(void)dealloc;
-(void)translateResponse:(id)response info:(id)info;
-(void)parseJSON:(id)json info:(id)info;
@end

