/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CLLocationManagerDelegate.h"
#import <Foundation/NSObject.h>

@class ABCallback, NSDate, NSError, CLLocationManager, CLLocation;

__attribute__((visibility("hidden")))
@interface ABLocation : NSObject <CLLocationManagerDelegate> {
@private
	ABCallback* callback;
	CLLocationManager* locationManager;
	CLLocation* location;
	NSError* error;
	NSDate* startLocatingDate;
}
@property(retain, nonatomic) ABCallback* callback;
@property(retain, nonatomic) CLLocation* location;
@property(retain, nonatomic) NSError* error;
-(void)dealloc;
-(void)requestCurrentLocation;
-(void)invokeCallback;
-(void)locationTimeout:(id)timeout;
-(void)locationManager:(id)manager didUpdateToLocation:(id)location fromLocation:(id)location3;
-(void)locationManager:(id)manager didFailWithError:(id)error;
@end

