/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "ABUITextRendererDelegate.h"
#import <Foundation/NSObject.h>

@class NSMutableAttributedString, NSAttributedString, NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ABMarkupText : NSObject <ABUITextRendererDelegate> {
@private
	NSMutableAttributedString* _attributedString;
	NSMutableArray* _attributesStack;
	NSMutableArray* _activeRanges;
	NSRange _currentRange;
	BOOL inActiveRange;
	int activeRangeTagDepth;
	int tagDepth;
}
@property(readonly, assign, nonatomic) NSArray* activeRanges;
@property(readonly, assign, nonatomic) NSAttributedString* attributedString;
-(void)dealloc;
-(NSRange)rangeOfHREF:(id)href;
-(id)activeRangesOffsetBy:(int)by;
-(id)activeRangesForTextRenderer:(id)textRenderer;
-(id)currentAttribute:(id)attribute;
-(void)startElement:(id)element attributes:(id)attributes;
-(void)endElement:(id)element;
-(void)characters:(id)characters;
-(void)error:(id)error;
-(void)parseString:(id)string;
-(id)initWithMarkup:(id)markup;
@end

