/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABProxy.h"


__attribute__((visibility("hidden")))
@interface ABMainThreadProxy : ABProxy {
}
-(void)forwardInvocation:(id)invocation;
-(void)performInvocationOnMainThread:(id)thread;
-(id)description;
@end

