/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABTextView.h"
#import "Twitter-Structs.h"


__attribute__((visibility("hidden")))
@interface ABMarkupTextView : ABTextView {
}
+(void)test;
@end

