/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "UINavigationControllerDelegate.h"
#import "UIVideoEditorControllerDelegate.h"

@class UIVideoEditorController, ABCallback, UINavigationController, NSURL;

__attribute__((visibility("hidden")))
@interface ABMediaEditor : NSObject <UIVideoEditorControllerDelegate, UINavigationControllerDelegate> {
@private
	UIVideoEditorController* videoEditorController;
	UINavigationController* navigationController;
	ABCallback* callback;
	NSURL* videoURL;
}
@property(retain, nonatomic) UINavigationController* navigationController;
@property(retain, nonatomic) ABCallback* callback;
@property(retain, nonatomic) NSURL* videoURL;
+(void)editVideo:(id)video navigationController:(id)controller callback:(id)callback;
-(void)dealloc;
-(void)show;
-(void)_dismiss;
-(void)videoEditorController:(id)controller didSaveEditedVideoToPath:(id)path;
-(void)videoEditorController:(id)controller didFailWithError:(id)error;
-(void)videoEditorControllerDidCancel:(id)videoEditorController;
@end

