/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Twitter-Structs.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIActionSheetDelegate.h"

@class UINavigationController, UIView, NSURL, UIImage, ABCallback;

__attribute__((visibility("hidden")))
@interface ABMediaChooser : NSObject <UIActionSheetDelegate, UINavigationControllerDelegate, UIImagePickerControllerDelegate> {
@private
	int choices;
	UINavigationController* sourceNavigationController;
	ABCallback* callback;
	struct {
		int takePhoto;
		int chooseExistingPhoto;
		int recordVideo;
		int recordAudio;
	} buttonIndex;
	XXStruct_3sqDcB _flags;
	UIImage* image;
	NSURL* movieURL;
	CGRect fromRect;
	UIView* inView;
}
@property(retain, nonatomic) UIImage* image;
@property(retain, nonatomic) NSURL* movieURL;
+(int)availableOptions:(int)options;
+(BOOL)hasCamera;
+(id)choose:(int)choose fromNavigationController:(id)navigationController callback:(id)callback;
+(id)choose:(int)choose rect:(CGRect)rect inView:(id)view callback:(id)callback;
+(void)_showSuccessOrError:(id)error forHUD:(id)hud;
+(void)_saveToPhotoAlbum:(id)photoAlbum context:(id)context;
+(void)saveToPhotoAlbum:(id)photoAlbum;
+(void)image:(id)image didFinishSavingWithError:(id)error contextInfo:(id)info;
+(void)_saveMovieToAlbum:(id)album context:(id)context;
+(void)saveMovieToAlbum:(id)album;
+(void)video:(id)video didFinishSavingWithError:(id)error contextInfo:(id)info;
-(id)rootViewController;
-(void)imagePickerController:(id)controller didFinishPickingMediaWithInfo:(id)info;
-(void)imagePickerControllerDidCancel:(id)imagePickerController;
-(void)takePhotoOrVideo;
-(void)takePhoto;
-(void)chooseExistingPhoto;
-(void)chooseExistingVideo;
-(void)chooseExistingPhotoOrVideo;
-(void)recordVideo;
-(void)recordAudio;
-(void)showActionSheet;
-(void)actionSheet:(id)sheet didDismissWithButtonIndex:(int)buttonIndex;
-(void)show;
-(id)initWithMediaChoices:(int)mediaChoices rect:(CGRect)rect inView:(id)view callback:(id)callback;
-(id)initWithMediaChoices:(int)mediaChoices navigationController:(id)controller callback:(id)callback;
-(void)dealloc;
@end

