/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSMutableArray.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface ABMutableAttributedArray : NSMutableArray {
@private
	NSMutableArray* _array;
	NSMutableDictionary* userInfo;
}
@property(retain, nonatomic) NSMutableArray* _array;
@property(retain, nonatomic) NSMutableDictionary* userInfo;
-(id)init;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(unsigned)count;
-(id)objectAtIndex:(unsigned)index;
-(void)insertObject:(id)object atIndex:(unsigned)index;
-(void)removeObjectAtIndex:(unsigned)index;
-(void)addObject:(id)object;
-(void)removeLastObject;
-(void)replaceObjectAtIndex:(unsigned)index withObject:(id)object;
@end

