/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface ABMutableReference : NSObject {
@private
	id reference;
	BOOL retainsReference;
}
+(id)retainedReference:(id)reference;
+(id)nonRetainedReference:(id)reference;
-(id)initWithReference:(id)reference retainsReference:(BOOL)reference2;
-(void)dealloc;
-(void)setReference:(id)reference;
-(id)reference;
@end

