/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "NSCoding.h"
#import "NSFastEnumeration.h"
#import <Foundation/NSObject.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface ABMutableMultiDictionary : NSObject <NSCoding, NSFastEnumeration> {
@private
	NSMutableDictionary* dictionary;
}
-(id)init;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(unsigned)count;
-(id)_mutableArrayForKey:(id)key;
-(id)objectsForKey:(id)key;
-(void)setObject:(id)object forKey:(id)key;
-(void)addObject:(id)object forKey:(id)key;
-(void)removeObject:(id)object forKey:(id)key;
-(void)removeObjectsForKey:(id)key;
-(unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
-(id)description;
@end

