/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface ABNetworkCache : NSObject {
}
+(id)cachedDataForURL:(id)url file:(id*)file;
+(id)cachedDataForURL:(id)url;
+(void)request:(id)request callback:(id)callback;
+(void)response:(id)response info:(id)info;
@end

