/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIImageView.h>

@protocol ABNetworkImageViewDelegate;

__attribute__((visibility("hidden")))
@interface ABNetworkImageView : UIImageView {
@private
	id<ABNetworkImageViewDelegate> delegate;
}
@property(assign, nonatomic) id<ABNetworkImageViewDelegate> delegate;
-(id)initWithPlaceholderImage:(id)placeholderImage forImageURL:(id)imageURL;
-(void)dealloc;
-(void)errorLoadingImage:(id)image;
-(void)imageResponse:(id)response info:(id)info;
-(void)progress:(id)progress info:(id)info;
@end

