/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIScrollView.h>


__attribute__((visibility("hidden")))
@interface ABNetworkImageDisplayControllerScrollView : UIScrollView {
@private
	id networkImageDelegate;
}
@property(assign, nonatomic) id networkImageDelegate;
-(void)touchesEnded:(id)ended withEvent:(id)event;
@end

