/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewController.h"


__attribute__((visibility("hidden")))
@interface AboutSettingsViewController : ABStaticTableViewController {
}
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)loadTableView;
-(void)tos:(id)tos;
-(void)privacy:(id)privacy;
-(void)viewUser:(id)user;
-(void)viewWillAppear:(BOOL)view;
@end

