/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "ABRowView.h"

@class NSString, UIColor;

__attribute__((visibility("hidden")))
@interface ABPlainRowCell : ABRowView {
@private
	NSString* text;
	NSString* altText;
	int style;
	UIColor* textColor;
}
@property(retain, nonatomic) NSString* text;
@property(retain, nonatomic) NSString* altText;
@property(assign, nonatomic) int style;
@property(retain, nonatomic) UIColor* textColor;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
-(id)textFont;
@end

