/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface ABProxy : NSObject {
@private
	id object;
}
+(id)proxyForObject:(id)object;
-(id)initWithObject:(id)object;
-(void)dealloc;
-(id)proxiedObject;
-(BOOL)respondsToSelector:(SEL)selector;
-(void)forwardInvocation:(id)invocation;
-(id)methodSignatureForSelector:(SEL)selector;
@end

