/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIScrollView.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface ABRailView : UIScrollView {
@private
	id delegate;
	NSArray* items;
}
@property(assign, nonatomic) id delegate;
-(void)dealloc;
-(CGRect)frameForIndex:(int)index;
-(void)setItems:(id)items animated:(BOOL)animated;
@end

