/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class UIImage, NSString;

__attribute__((visibility("hidden")))
@interface ABRailViewItem : NSObject {
@private
	NSString* title;
	UIImage* image;
}
-(id)initWithTitle:(id)title image:(id)image;
-(id)_makeView;
@end

