/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class NSArray, NSMutableArray;
@protocol ABRowViewDelegate;

__attribute__((visibility("hidden")))
@interface ABRowView : UIView {
@private
	id<ABRowViewDelegate> delegate;
	id target;
	SEL action;
	id userInfo;
	BOOL dynamicHeight;
	ABRowView* parentRow;
	NSMutableArray* childRows;
	float rowHeight;
	struct {
		unsigned selectable : 1;
		unsigned highlighted : 1;
		unsigned selected : 1;
		unsigned deferUpdate : 5;
		unsigned cleanRowHeight : 1;
		unsigned plainSetFrame : 1;
		unsigned fadeNextContentsChange : 1;
		unsigned forceGroupedStyle : 1;
	} _flags;
}
@property(assign, nonatomic) id<ABRowViewDelegate> delegate;
@property(retain, nonatomic) id userInfo;
@property(assign, nonatomic) ABRowView* parentRow;
@property(assign, nonatomic) BOOL dynamicHeight;
@property(assign, nonatomic) BOOL selected;
@property(assign, nonatomic) BOOL highlighted;
@property(readonly, assign, nonatomic) BOOL isGrouped;
@property(readonly, assign, nonatomic) BOOL isLast;
@property(readonly, assign, nonatomic) BOOL isFirst;
@property(copy, nonatomic) NSArray* childRows;
@property(readonly, assign, nonatomic) ABRowView* rootRow;
@property(assign, nonatomic) BOOL selectable;
@property(assign, nonatomic) float rowHeight;
+(id)row;
+(id)sectionHeader:(id)header;
+(id)spacerRow:(float)row;
+(id)divider:(id)divider;
+(id)loadingRow;
-(id)initWithFrame:(CGRect)frame;
-(id)init;
-(void)dealloc;
-(void)beginChanges;
-(void)endChanges;
-(void)_childRowsChanged;
-(id)description;
-(void)_setupFrame:(id)frame;
-(id)childContainer;
-(void)_add:(id)add;
-(void)_remove:(id)remove;
-(void)_mightHaveRemovedAllChildren;
-(id)addChildRow:(id)row;
-(void)removeChildRow:(id)row;
-(void)replaceChildRow:(id)row withRow:(id)row2;
-(float)calculatedRowHeight;
-(float)childWidth:(float)width;
-(float)xOffset;
-(float)_updateLayout:(float)layout width:(float)width xOffset:(float)offset;
-(void)layoutSubviews;
-(void)updateLayout;
-(void)setFrame:(CGRect)frame;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)setNeedsDisplay;
-(void)_deselectRowsBesides:(id)besides animated:(BOOL)animated;
-(void)deselectAllRowsAnimated:(BOOL)animated;
-(void)deselectOtherRowsAnimated:(BOOL)animated;
-(id)actionForLayer:(id)layer forKey:(id)key;
-(void)setTarget:(id)target action:(SEL)action;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
@end

