/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABRowViewDelegate.h"
#import "UIScrollViewDelegate.h"
#import <UIKit/UIViewController.h>

@class ABRowView, UIScrollView;

__attribute__((visibility("hidden")))
@interface ABRowViewController : UIViewController <UIScrollViewDelegate, ABRowViewDelegate> {
@private
	ABRowView* _rowView;
}
@property(readonly, assign, nonatomic) UIScrollView* scrollView;
@property(readonly, assign, nonatomic) ABRowView* rowView;
-(void)loadRowView;
-(void)loadView;
-(void)reloadRowView;
-(void)scrollViewWillBeginDragging:(id)scrollView;
@end

