/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIGestureRecognizer.h>

@class UITouch, UIScrollView;

__attribute__((visibility("hidden")))
@interface ABScrollGestureRecognizer : UIGestureRecognizer {
@private
	UITouch* _touch;
	CGPoint _firstPoint;
	CGPoint _lastPoint;
	double _lastTime;
	float _dx;
	float _dt;
	CGRect _originalBounds;
	UIScrollView* _startedOverScrollView;
	XXStruct_3sqDcB _flags;
}
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)reset;
-(BOOL)canBePreventedByGestureRecognizer:(id)recognizer;
@end

