/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "Twitter-Structs.h"
#import "UISearchDisplayDelegate.h"
#import "UISearchBarDelegate.h"
#import <UIKit/UIViewController.h>

@class UISearchDisplayController, UIImageView, UITableView;

__attribute__((visibility("hidden")))
@interface ABSearchableTableViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchDisplayDelegate, UISearchBarDelegate> {
@private
	UITableView* _tableView;
	UIImageView* _tableHeader;
	UISearchDisplayController* searchDisplayController;
	BOOL activateSearchDisplayImmediately;
}
@property(assign, nonatomic) BOOL activateSearchDisplayImmediately;
@property(readonly, assign, nonatomic) UISearchDisplayController* searchDisplayController;
@property(readonly, assign, nonatomic) UITableView* tableView;
-(void)dealloc;
-(id)placeholderSearchStringForFilterBar;
-(id)appropriateSearchDisplayContentsController;
-(void)loadView;
-(void)viewDidUnload;
-(id)searchField;
-(void)viewWillAppear:(BOOL)view;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(BOOL)isSearchTableView:(id)view;
-(BOOL)searchDisplayIsActive;
-(void)searchDisplayControllerWillBeginSearch:(id)searchDisplayController;
-(void)searchDisplayControllerDidBeginSearch:(id)searchDisplayController;
-(void)searchDisplayControllerWillEndSearch:(id)searchDisplayController;
-(void)searchDisplayControllerDidEndSearch:(id)searchDisplayController;
-(void)searchDisplayController:(id)controller didLoadSearchResultsTableView:(id)view;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)searchBarSearchButtonClicked:(id)clicked;
@end

