/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABSimpleSearchViewController.h"
#import "Twitter-Structs.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface ABSimplePersistentRecentSearchViewController : ABSimpleSearchViewController {
@private
	NSMutableArray* recentSearches;
}
-(id)defaultsKey;
-(id)recentSearches;
-(id)recentsMatching:(id)matching;
-(void)saveRecent:(id)recent;
-(BOOL)removeRecent:(id)recent;
@end

