/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "Twitter-Structs.h"
#import "ABStaticTableViewController.h"

@class UINavigationController, NSString, ABCallback, UITextField;

__attribute__((visibility("hidden")))
@interface ABSingleTextFieldViewController : ABStaticTableViewController <UITextFieldDelegate> {
@private
	BOOL modal;
	BOOL didChange;
	NSString* text;
	NSString* placeholderText;
	UITextField* textField;
	NSString* footerText;
	UINavigationController* navigationController;
	ABCallback* callback;
}
@property(copy, nonatomic) NSString* text;
@property(copy, nonatomic) NSString* placeholderText;
@property(retain, nonatomic) ABCallback* callback;
@property(assign, nonatomic) BOOL didChange;
@property(assign, nonatomic) UINavigationController* navigationController;
@property(assign, nonatomic) BOOL modal;
@property(copy, nonatomic) NSString* footerText;
+(id)showSingleTextFieldWithText:(id)text placeholder:(id)placeholder title:(id)title fromNavigationController:(id)navigationController modal:(BOOL)modal callback:(id)callback;
-(void)_present;
-(void)_dismiss;
-(void)dealloc;
-(void)loadTableView;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)view;
-(BOOL)textFieldShouldClear:(id)textField;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(void)cancel:(id)cancel;
-(void)save:(id)save;
@end

