/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "Twitter-Structs.h"
#import <UIKit/UIViewController.h>

@class NSArray, UIButton, NSString, UITableView, UITextField;

__attribute__((visibility("hidden")))
@interface ABSimpleSearchViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate> {
@private
	UITableView* _tableView;
	UITextField* _searchField;
	UIButton* _overlayView;
	UIButton* _clearButton;
	BOOL faded;
	NSString* searchText;
	NSArray* matchingSearches;
}
@property(retain, nonatomic) NSString* searchText;
-(id)init;
-(void)dealloc;
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
-(id)placeholderText;
-(id)unmatchedResultFormatText;
-(int)returnKeyType;
-(void)loadView;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)_refade;
-(void)_unfade;
-(id)recentsMatching:(id)matching;
-(void)_updateMatchingSearches;
-(BOOL)enforceHashtagPrefix;
-(void)_textDidUpdate;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(void)clear:(id)clear;
-(void)saveRecent:(id)recent;
-(void)search:(id)search;
-(void)performSearch:(id)search;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)cancel:(id)cancel;
-(void)scrollViewDidScroll:(id)scrollView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(BOOL)removeRecent:(id)recent;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
@end

