/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface ABSound : NSObject {
@private
	unsigned soundID;
}
+(id)soundNamed:(id)named;
+(void)playSoundNamed:(id)named;
+(void)vibrate;
-(id)initWithSoundID:(unsigned long)soundID;
-(void)dealloc;
-(void)play;
@end

