/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewElement.h"


__attribute__((visibility("hidden")))
@interface ABStaticTableViewDisclosureElement : ABStaticTableViewElement {
@private
	Class viewControllerClass;
}
@property(assign, nonatomic) Class viewControllerClass;
-(id)cellForTableView:(id)tableView;
-(void)didSelectInTableView:(id)tableView;
@end

