/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewElement.h"


__attribute__((visibility("hidden")))
@interface ABStaticTableViewCheckmarkElement : ABStaticTableViewElement {
@private
	BOOL checked;
	BOOL canOnlyCheck;
}
@property(assign, nonatomic) BOOL checked;
@property(assign, nonatomic) BOOL canOnlyCheck;
-(void)dealloc;
-(id)cellForTableView:(id)tableView;
-(void)didSelectInTableView:(id)tableView;
@end

