/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewElement.h"

@class UIImage;

__attribute__((visibility("hidden")))
@interface ABStaticTableViewLargeLeftImageElement : ABStaticTableViewElement {
@private
	UIImage* image;
}
@property(retain, nonatomic) UIImage* image;
-(void)dealloc;
-(id)cellForTableView:(id)tableView;
-(float)heightInTableView:(id)tableView;
@end

