/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewElement.h"

@class UIImage, NSString;

__attribute__((visibility("hidden")))
@interface ABStaticTableViewSliderElement : ABStaticTableViewElement {
@private
	NSString* key;
	UIImage* leftImage;
	UIImage* rightImage;
}
@property(copy, nonatomic) NSString* key;
@property(retain, nonatomic) UIImage* leftImage;
@property(retain, nonatomic) UIImage* rightImage;
-(void)dealloc;
-(BOOL)isSelectable;
-(id)cellForTableView:(id)tableView;
@end

