/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewController.h"

@class ABStaticTableViewMultiValueElement;

__attribute__((visibility("hidden")))
@interface ABStaticMultiValueViewController : ABStaticTableViewController {
@private
	ABStaticTableViewMultiValueElement* multiValueElement;
}
@property(retain, nonatomic) ABStaticTableViewMultiValueElement* multiValueElement;
-(void)dealloc;
-(void)viewDidLoad;
-(void)loadTableView;
-(void)didCheckmarkElement:(id)element;
@end

