/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewElement.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface ABStaticTableViewSwitchElement : ABStaticTableViewElement {
@private
	NSString* key;
	BOOL on;
	BOOL invert;
}
@property(copy, nonatomic) NSString* key;
@property(assign, nonatomic) BOOL invert;
@property(assign, nonatomic) BOOL on;
-(void)dealloc;
-(void)performCallback:(id)callback;
-(BOOL)isSelectable;
-(BOOL)hasValidKey;
-(BOOL)switchValue;
-(id)cellForTableView:(id)tableView;
-(void)switchAction:(id)action;
@end

