/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewElement.h"


__attribute__((visibility("hidden")))
@interface ABStaticTableViewButtonElement : ABStaticTableViewElement {
@private
	id accessoryTarget;
	SEL accessoryAction;
}
@property(assign, nonatomic) id accessoryTarget;
@property(assign, nonatomic) SEL accessoryAction;
-(id)cellForTableView:(id)tableView;
-(void)didTapAccessoryInTableView:(id)tableView;
@end

