/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewElement.h"

@class UITextField;

__attribute__((visibility("hidden")))
@interface ABStaticTableViewTextFieldElement : ABStaticTableViewElement {
@private
	UITextField* textField;
}
@property(retain, nonatomic) UITextField* textField;
-(void)dealloc;
-(id)cellForTableView:(id)tableView;
-(BOOL)isSelectable;
-(void)willSelectInTableView:(id)tableView;
@end

