/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewElement.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface ABStaticTableViewLabelElement : ABStaticTableViewElement {
@private
	NSString* labelText;
	BOOL contactStyleLabel;
}
@property(copy, nonatomic) NSString* labelText;
@property(assign, nonatomic) BOOL contactStyleLabel;
-(void)dealloc;
-(BOOL)isSelectable;
-(id)cellForTableView:(id)tableView;
@end

