/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewElement.h"

@class NSArray, ABCallback, NSString;

__attribute__((visibility("hidden")))
@interface ABStaticTableViewMultiValueElement : ABStaticTableViewElement {
@private
	NSString* key;
	NSArray* titles;
	NSArray* values;
	id defaultValue;
	ABCallback* additionalOptions;
}
@property(copy, nonatomic) NSString* key;
@property(copy, nonatomic) NSArray* titles;
@property(copy, nonatomic) NSArray* values;
@property(copy, nonatomic) id defaultValue;
@property(retain, nonatomic) ABCallback* additionalOptions;
-(void)dealloc;
-(id)currentValue;
-(id)selectedTitle;
-(BOOL)isSelectedValue:(id)value;
-(id)cellForTableView:(id)tableView;
-(void)didSelectInTableView:(id)tableView;
@end

