/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class ABCallback, ABStaticTableViewController, NSString;

__attribute__((visibility("hidden")))
@interface ABStaticTableViewElement : NSObject {
@private
	id userInfo;
	NSString* title;
	NSString* subtitle;
	id target;
	SEL action;
	ABStaticTableViewController* associatedViewController;
	ABCallback* callback;
	float height;
}
@property(copy, nonatomic) NSString* title;
@property(copy, nonatomic) NSString* subtitle;
@property(assign, nonatomic) id target;
@property(assign, nonatomic) SEL action;
@property(retain, nonatomic) id userInfo;
@property(assign, nonatomic) ABStaticTableViewController* associatedViewController;
@property(retain, nonatomic) ABCallback* callback;
@property(assign, nonatomic) float height;
@property(readonly, assign, nonatomic) BOOL isSelectable;
+(id)element;
-(void)performCallback:(id)callback;
-(void)dealloc;
-(float)heightInTableView:(id)tableView;
-(id)cellForTableView:(id)tableView;
-(void)didSelectInTableView:(id)tableView;
-(void)willSelectInTableView:(id)tableView;
-(void)didTapAccessoryInTableView:(id)tableView;
@end

