/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewElement.h"


__attribute__((visibility("hidden")))
@interface ABStaticTableViewMultilineLabelElement : ABStaticTableViewElement {
}
-(id)cellForTableView:(id)tableView;
-(float)heightInTableView:(id)tableView;
-(BOOL)canBecomeFirstResponder;
-(void)copy:(id)copy;
@end

