/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface ABStringReplacement : NSObject {
@private
	NSRange range;
	NSString* replacementString;
}
+(id)stringReplacement:(id)replacement forRange:(NSRange)range;
+(id)stringByApplyingReplacements:(id)replacements toString:(id)string;
-(id)initWithReplacementString:(id)replacementString forRange:(NSRange)range;
-(void)dealloc;
-(NSRange)range;
-(int)compare:(id)compare;
-(int)reverseCompare:(id)compare;
-(id)stringByApplyingToString:(id)string;
@end

