/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol ABSubTabBarControllerDelegate
-(int)numberOfTabsInSubTabController:(id)subTabController;
-(id)subTabBarController:(id)controller barItemForIndex:(int)index;
-(id)subTabBarController:(id)controller viewControllerForIndex:(int)index;
-(BOOL)subTabBarController:(id)controller drawGlowForIndex:(int)index;
-(void)subTabBarController:(id)controller didSelectViewControllerAtIndex:(int)index;
-(void)subTabBarController:(id)controller doubleTapTabItemAtIndex:(int)index;
-(id)subTabBarController:(id)controller accessibilityLabelForIndex:(int)index;
@end

