/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "ABSubTabBarDelegate.h"
#import <UIKit/UIViewController.h>

@class NSString, ABSubTabBar, UIView;
@protocol ABSubTabBarControllerDelegate;

__attribute__((visibility("hidden")))
@interface ABSubTabBarController : UIViewController <ABSubTabBarDelegate> {
@private
	id<ABSubTabBarControllerDelegate> subTabBarControllerDelegate;
	ABSubTabBar* _tabBar;
	UIViewController* _selectedViewController;
	UIView* _visibleView;
	UIViewController* ab_parentViewController;
	NSString* _referringEvent;
}
@property(assign, nonatomic) id<ABSubTabBarControllerDelegate> subTabBarControllerDelegate;
@property(readonly, assign, nonatomic) unsigned selectedIndex;
-(CGRect)_tabBarFrame;
-(id)init;
-(void)setInitialSelectedIndex:(int)index;
-(void)dealloc;
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
-(void)didReceiveMemoryWarning;
-(id)selectedViewController;
-(void)setSelectedViewController:(id)controller;
-(void)_updateSelectedWithCurrentSelection;
-(void)reloadTabs;
-(void)updateBadges;
-(void)setSelectedIndex:(int)index;
-(void)loadView;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(int)numberOfTabsInSubTabBar:(id)subTabBar;
-(id)subTabBar:(id)bar barItemForIndex:(int)index;
-(void)subTabBar:(id)bar didSelectTabAtIndex:(int)index;
-(void)subTabBar:(id)bar doubleTapTabAtIndex:(int)index;
-(BOOL)subTabBar:(id)bar drawGlowForTabAtIndex:(int)index;
-(id)subTabBar:(id)bar accessibilityLabelForTabAtIndex:(int)index;
-(void)setSelectedIndex:(int)index animated:(BOOL)animated;
-(void)ab_attemptToRecordImpressionFromReferringEvent:(id)referringEvent;
-(void)ab_resetImpression;
@end

