/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIControl.h>
#import "Twitter-Structs.h"

@class CALayer, NSMutableArray;
@protocol ABSubTabBarDelegate;

__attribute__((visibility("hidden")))
@interface ABSubTabBar : UIControl {
@private
	id<ABSubTabBarDelegate> delegate;
	int selectedIndex;
	int numberOfTabs;
	NSMutableArray* tabViews;
	NSMutableArray* tabBarItems;
	CALayer* nippleLayer;
}
@property(assign, nonatomic) id<ABSubTabBarDelegate> delegate;
@property(assign, nonatomic) int selectedIndex;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(CGRect)rectForIndex:(int)index;
-(id)accessibilityLabelForIndex:(int)index;
-(void)update;
-(void)updateGlows;
-(void)reallySetFrame:(CGRect)frame;
-(void)setFrame:(CGRect)frame;
-(void)drawRect:(CGRect)rect;
-(void)tabBarSelected:(id)selected;
-(void)tabBarDoubleTapped:(id)tapped;
@end

