/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIControl.h>
#import "Twitter-Structs.h"

@class ABSubTabBarItem;

__attribute__((visibility("hidden")))
@interface ABSubTabBarTabView : UIControl {
@private
	ABSubTabBarItem* item;
}
@property(retain, nonatomic) ABSubTabBarItem* item;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
-(void)setSelected:(BOOL)selected;
-(void)setHighlighted:(BOOL)highlighted;
-(BOOL)beginTrackingWithTouch:(id)touch withEvent:(id)event;
-(BOOL)continueTrackingWithTouch:(id)touch withEvent:(id)event;
-(void)endTrackingWithTouch:(id)touch withEvent:(id)event;
-(void)cancelTrackingWithEvent:(id)event;
@end

