/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol ABSubTabBarDelegate
@optional
-(int)numberOfTabsInSubTabBar:(id)subTabBar;
-(id)subTabBar:(id)bar barItemForIndex:(int)index;
-(void)subTabBar:(id)bar didSelectTabAtIndex:(int)index;
-(void)subTabBar:(id)bar doubleTapTabAtIndex:(int)index;
-(BOOL)subTabBar:(id)bar drawGlowForTabAtIndex:(int)index;
-(id)subTabBar:(id)bar accessibilityLabelForTabAtIndex:(int)index;
@end

