/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "ABSwipeColumnScrollViewDelegate.h"
#import "ABMasterViewController.h"

@class NSArray, UIImageView, UIView, UIToolbar, NSMutableArray, CALayer, ABSwipeColumnScrollView;
@protocol ABSwipeColumnViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface ABSwipeColumnViewController : ABMasterViewController <ABSwipeColumnScrollViewDelegate> {
@private
	id<ABSwipeColumnViewControllerDelegate> delegate;
	NSMutableArray* viewControllers;
	UIViewController* overViewController;
	UIView* _masterContainer;
	ABSwipeColumnScrollView* _scrollView;
	UIImageView* _pullTab;
	UIImageView* sidebarShadow;
	UIImageView* otherSidebarShadow;
	UIView* leftColumnDimmer;
	int currentOrientation;
	UIView* throwawayContainer;
	CALayer* page1;
	CALayer* page2;
	UIViewController* _updatingWidthViewController;
	float _updatingWidthOriginalWidth;
	float _updatingWidthDesiredWidth;
	UIToolbar* _fullScreenToolbar;
	UIView* _fullScreenView;
	struct {
		unsigned pushing : 1;
		unsigned tracking : 1;
		unsigned sidebarImage : 3;
		unsigned throwawayState : 2;
	} _flags;
	int lastSnapOffset;
}
@property(assign, nonatomic) id<ABSwipeColumnViewControllerDelegate> delegate;
@property(readonly, assign, nonatomic) UIViewController* overViewController;
@property(readonly, assign, nonatomic) UIViewController* topViewController;
@property(readonly, assign, nonatomic) NSArray* viewControllers;
+(void)_viewControllerDoneAnimatingAway:(id)away info:(id)info;
-(id)init;
-(void)dealloc;
-(void)_setThrowawayState:(int)state;
-(void)_updateLayout:(BOOL)layout;
-(void)loadView;
-(id)swipeView:(id)view willBeginTouches:(id)touches withEvent:(id)event;
-(void)_reveal:(id)reveal animated:(BOOL)animated;
-(void)swipeView:(id)view shouldRevealItem:(id)item;
-(id)swipePointsForSwipeView:(id)swipeView proposedOffset:(float)offset;
-(int)bestOffsetForPossibleOffsets:(id)possibleOffsets fromOffset:(int)offset toOffset:(int)offset3 inDirection:(int)direction;
-(int)nearestOffsetForPossibleOffsets:(id)possibleOffsets fromOffset:(int)offset toOffset:(int)offset3;
-(float)swipeView:(id)view willSwipeToOffset:(float)offset throwing:(BOOL)throwing;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)scrollViewDidEndScrollingAnimation:(id)scrollView;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewControllerNeedsToUpdateWidth:(id)updateWidth;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(id)popToRootViewControllerAnimated:(BOOL)rootViewControllerAnimated;
-(id)_superestColumn:(id)column;
-(void)pushViewController:(id)controller afterViewController:(id)controller2 animated:(BOOL)animated;
-(void)_finishPush:(id)push;
-(id)viewControllerAfter:(id)after;
-(void)showOverViewAnimationDidEnd:(id)showOverViewAnimation finished:(id)finished context:(void*)context;
-(void)showOverViewController:(id)controller animated:(BOOL)animated;
-(void)ignore:(id)ignore context:(void*)context;
-(void)hideOverViewAnimationDidEnd:(id)hideOverViewAnimation finished:(id)finished context:(void*)context;
-(void)hideOverViewControllerAnimated:(BOOL)animated;
-(id)beginFullScreenForView:(id)view animated:(BOOL)animated;
-(void)beginFullScreenAnimationDidStop:(id)beginFullScreenAnimation finished:(id)finished context:(void*)context;
-(id)endFullScreenAnimated:(BOOL)animated;
-(id)visibleViewControllers;
-(void)tapStatusBar:(CGPoint)bar;
@end

