/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class NSTimer, UIGestureRecognizer;
@protocol ABSwipeColumnScrollViewDelegate;

__attribute__((visibility("hidden")))
@interface ABSwipeColumnScrollView : UIView {
@private
	id<ABSwipeColumnScrollViewDelegate> delegate;
	CGSize contentSize;
	UIGestureRecognizer* r;
	NSTimer* timer;
	float dx;
	int steps;
	float friction;
	float springiness;
	CGRect workingBounds;
	float destinationOffset;
	id beganInteractionOnItem;
	struct {
		unsigned isLoadingNewer : 1;
		unsigned isLoadingOlder : 1;
		unsigned isAtEnd : 1;
	} _swipeFlags;
	BOOL didHesitate;
}
@property(assign, nonatomic) id<ABSwipeColumnScrollViewDelegate> delegate;
@property(readonly, assign, nonatomic) BOOL didHesitate;
@property(assign, nonatomic) CGSize contentSize;
@property(assign, nonatomic) CGPoint contentOffset;
+(Class)layerClass;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)_beginTouch:(CGPoint)touch;
-(void)_didScroll:(CGPoint)scroll;
-(void)_animateToDestinationOffset;
-(void)jiggle;
-(void)_endScroll:(float)scroll;
-(void)disableSpring;
-(void)animate;
-(void)setContentOffset:(CGPoint)offset animated:(BOOL)animated;
-(void)scrollRectToVisible:(CGRect)visible animated:(BOOL)animated;
-(void)_invalidateTimer;
-(void)swipeView:(id)view willBeginTouches:(id)touches withEvent:(id)event;
-(void)_didReset;
@end

