/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIScrollViewDelegate.h"


@protocol ABSwipeColumnScrollViewDelegate <UIScrollViewDelegate>
-(id)swipeView:(id)view willBeginTouches:(id)touches withEvent:(id)event;
-(void)swipeView:(id)view shouldRevealItem:(id)item;
-(float)swipeView:(id)view willSwipeToOffset:(float)offset throwing:(BOOL)throwing;
@end

