/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class UILabel, UIActivityIndicatorView, UIImageView, UIView, UIViewController, UITableView;
@protocol ABTableViewPullToRefreshDelegate;

__attribute__((visibility("hidden")))
@interface ABTableViewPullToRefreshController : NSObject {
@private
	UIViewController<ABTableViewPullToRefreshDelegate>* _contentsController;
	UITableView* _tableView;
	UIView* _headerView;
	UIImageView* loadNewerArrowView;
	UIActivityIndicatorView* loadNewerSpinner;
	UILabel* loadNewerLabel;
	UILabel* lastUpdatedLabel;
	struct {
		unsigned loadNewerUIInReleaseState : 2;
	} _flags;
}
-(id)initWithTableView:(id)tableView contentsController:(id)controller;
-(void)dealloc;
-(id)tableHeaderView;
-(void)_setLoadNewerState:(int)state;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(void)noteStateChanged:(int)changed;
@end

