/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class ABTableViewCell;

__attribute__((visibility("hidden")))
@interface ABTableViewCellView : UIView {
@private
	ABTableViewCell* _cell;
	struct {
		unsigned isLoadingNewer : 1;
		unsigned isLoadingOlder : 1;
		unsigned isAtEnd : 1;
	} _flags;
}
@property(assign, nonatomic, getter=isHighlighted) BOOL highlighted;
@property(readonly, assign, nonatomic) ABTableViewCell* cell;
-(id)initWithFrame:(CGRect)frame cell:(id)cell;
-(void)animatesNextFrameChange;
-(void)setIsAlwaysOnScreen:(BOOL)screen;
-(BOOL)canAnimateFrameChanges;
-(void)setFrame:(CGRect)frame;
-(void)drawRect:(CGRect)rect;
@end

