/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>
#import "Twitter-Structs.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface ABTableViewCell : UITableViewCell {
@private
	UIView* contentView;
}
@property(readonly, assign, nonatomic) BOOL contentViewHighlighted;
@property(readonly, assign, nonatomic) CGRect contentViewBounds;
-(Class)cellViewClass;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(id)initWithReuseIdentifier:(id)reuseIdentifier;
-(void)dealloc;
-(void)setBackgroundColor:(id)color;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)setNeedsDisplay;
-(void)drawContentView:(CGRect)view;
-(id)primaryContentView;
@end

