/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>

@class UIImageView, UIView, UIViewController, UITableView;

__attribute__((visibility("hidden")))
@interface ABTableViewStayOnScreenController : NSObject {
@private
	UIViewController* _contentsController;
	UITableView* _tableView;
	UIView* _selected;
	UIImageView* shadow;
	id _selectedItem;
	BOOL shadowState;
	BOOL enabled;
}
@property(assign, nonatomic) BOOL enabled;
-(id)initWithTableView:(id)tableView contentsController:(id)controller;
-(void)dealloc;
-(void)updateSelectedCellFrame:(BOOL)frame;
-(void)scrollViewDidScroll:(id)scrollView;
-(id)stayOnScreenCellForPoint:(CGPoint)point;
-(void)tableView:(id)view didSelectItem:(id)item;
@end

