/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol ABTableViewPinchPreview
-(BOOL)pinchPreviewController:(id)controller willStartPreviewForCell:(id)cell;
-(id)pinchPreviewController:(id)controller viewControllerForCell:(id)cell;
-(id)pinchPreviewController:(id)controller containerViewForPinchedCell:(id)pinchedCell;
-(id)pinchPreviewController:(id)controller headerFlapForPinchedCell:(id)pinchedCell;
-(id)pinchPreviewController:(id)controller footerFlapControllerForPinchedCell:(id)pinchedCell;
@end

