/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class ABUITextRenderer;
@protocol ABUITextViewDelegate;

__attribute__((visibility("hidden")))
@interface ABTextView : UIView {
@private
	ABUITextRenderer* renderer;
	id<ABUITextViewDelegate> delegate;
	XXStruct_3sqDcB _flags;
}
@property(retain, nonatomic) ABUITextRenderer* renderer;
@property(assign, nonatomic) id<ABUITextViewDelegate> delegate;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)setFrame:(CGRect)frame;
-(void)drawRect:(CGRect)rect;
-(void)animateNextUpdate;
-(id)actionForLayer:(id)layer forKey:(id)key;
-(float)heightThatFits;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
@end

