/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIGestureRecognizer.h>

@class UITouch;

__attribute__((visibility("hidden")))
@interface ABTwoFingerDragDownGestureRecognizer : UIGestureRecognizer {
@private
	CGPoint aStart;
	CGPoint bStart;
	UITouch* a;
	UITouch* b;
	int twoFingerState;
}
@property(readonly, assign, nonatomic) int twoFingerState;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)reset;
@end

