/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>

@class UIImage, NSString;

__attribute__((visibility("hidden")))
@interface ABVerticalFlowViewItem : UIView {
@private
	NSString* subtext;
	UIImage* image;
}
@property(retain, nonatomic) UIImage* image;
@property(retain, nonatomic) NSString* subtext;
-(void)dealloc;
@end

