/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>
#import "UIScrollViewDelegate.h"

@class NSMutableArray, UIScrollView;
@protocol ABVerticalFlowViewDelegate;

__attribute__((visibility("hidden")))
@interface ABVerticalFlowView : UIView <UIScrollViewDelegate> {
@private
	id<ABVerticalFlowViewDelegate> delegate;
	UIScrollView* _scrollView;
	NSMutableArray* _items;
	CGPoint lastOffset;
	float velocity;
	CGContextRef scratchContext;
	int disableUpdate;
	CGRect fullscreenOriginalRect;
	UIView* fullscreenContainer;
	UIView* fullscreenImage;
}
@property(assign, nonatomic) id<ABVerticalFlowViewDelegate> delegate;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(void)drawItem:(id)item inContext:(CGContextRef)context;
-(void)updateItemContents:(id)contents;
-(void)setImage:(id)image forIndex:(int)index;
-(void)setSubtext:(id)subtext forIndex:(int)index;
-(void)beginDisableUpdate;
-(void)endDisableUpdate;
-(float)_updateItem:(id)item withIndex:(int)index;
-(void)_updateItems;
-(void)_updateContentSize;
-(void)setFrame:(CGRect)frame;
-(void)reloadData;
-(float)offsetForIndex:(int)index;
-(int)indexForOffset:(float)offset;
-(void)selectIndex:(int)index animated:(BOOL)animated;
-(int)selectedIndex;
-(void)scrollViewDidEndScrollingAnimation:(id)scrollView;
-(void)tap:(id)tap;
-(void)doubleTap:(id)tap;
-(void)pinch:(id)pinch;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)fullscreen:(int)fullscreen;
-(void)_endFullscreen;
-(void)endFullScreenDidEnd:(id)endFullScreen finished:(id)finished context:(void*)context;
-(void)pinchClose:(id)close;
-(void)tapClose:(id)close;
@end

