/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface ABViewControllerPersistentProxy : NSObject <NSCoding> {
@private
	NSString* className;
	NSMutableDictionary* info;
}
+(id)proxy;
-(id)init;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)setClass:(Class)aClass;
-(void)setObject:(id)object forKey:(id)key;
-(id)objectForKey:(id)key;
-(id)decodedViewController;
@end

