/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface ABViewControllerCoder : NSObject {
}
+(id)savedPath;
+(void)saveRootViewController:(id)controller;
+(id)restoreRootViewController;
@end

