/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIWebViewDelegate.h"
#import <UIKit/UIViewController.h>

@class UIBarButtonItem, UIActivityIndicatorView, NSURL, UIWindow, NSArray, UIWebView;

__attribute__((visibility("hidden")))
@interface ABWebViewController : UIViewController <UIWebViewDelegate> {
@private
	NSURL* rootURL;
	NSURL* currentURL;
	UIWebView* _webView;
	UIBarButtonItem* backItem;
	UIBarButtonItem* forwardItem;
	UIBarButtonItem* statusItem;
	UIBarButtonItem* reloadItem;
	UIBarButtonItem* actionItem;
	NSArray* loadingItemsSet;
	NSArray* loadedItemsSet;
	UIActivityIndicatorView* spinner;
	UIWindow* originalWindow;
	struct {
		unsigned isLoading : 1;
		unsigned shouldRemove : 1;
	} _flags;
}
@property(copy, nonatomic) NSURL* rootURL;
@property(copy, nonatomic) NSURL* currentURL;
-(void)_updateToolbar;
-(id)init;
-(void)dealloc;
-(id)persistentProxy;
-(void)loadView;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)didReceiveMemoryWarning;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)back:(id)back;
-(void)forward:(id)forward;
-(void)refresh:(id)refresh;
-(void)action:(id)action;
-(void)openLatitude:(double)latitude longitude:(double)longitude;
-(void)openExternalURL:(id)url;
-(void)shouldOpenExternalURL:(id)url info:(id)info;
-(BOOL)shouldStartLoadWithURL:(id)url;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(unsigned)type;
-(void)webViewDidStartLoad:(id)webView;
-(void)webViewDidFinishLoad:(id)webView;
-(void)webView:(id)view didFailLoadWithError:(id)error;
@end

