/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABProxy.h"


__attribute__((visibility("hidden")))
@interface ABWeakProxy : ABProxy {
}
+(id)_weakProxyMap;
+(id)proxyForObject:(id)object;
+(void)dissociateWeakProxyForObject:(id)object;
-(id)initWithObject:(id)object;
-(void)dissociate;
-(id)description;
@end

