/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface ABWeakMap : NSObject {
@private
	NSMutableDictionary* dictionary;
}
-(id)init;
-(void)dealloc;
-(id)objectForKey:(id)key;
-(void)setObject:(id)object forKey:(id)key;
-(void)removeObjectForKey:(id)key;
-(int)count;
@end

