/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ADBook : NSObject {
@private
	void* addressBook;
	NSMutableArray* records;
	NSMutableArray* _records;
	NSMutableDictionary* _canonicalIdentitiesToPeople;
}
+(id)sharedBook;
+(id)localizedLabel:(id)label;
-(id)init;
-(void)dealloc;
-(id)_ab_improved_description_body;
-(id)description;
-(BOOL)save:(id*)save;
-(BOOL)hasUnsavedChanges;
-(void*)addressBook;
-(BOOL)addRecord:(id)record error:(id*)error;
-(BOOL)removeRecord:(id)record error:(id*)error;
-(id)commonRecord:(id)record;
-(void)_addPersonsCanonicalIdentitiesToMapping:(id)mapping;
-(id)_mapNewRecords:(CFArrayRef)records;
-(void)noteNewABRecordRef:(void*)ref;
-(id)people;
-(id)groups;
-(id)peopleWithName:(id)name;
-(id)phones;
-(id)emails;
-(id)personWithCanonicalIdentity:(id)canonicalIdentity;
@end

