/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface ADLabelValue : NSObject {
@private
	NSString* label;
	id value;
}
@property(readonly, assign, nonatomic) NSString* label;
@property(readonly, assign, nonatomic) id value;
+(id)labelValueArrayForMultiValue:(void*)multiValue;
-(id)initWithLabel:(id)label value:(id)value;
-(void)dealloc;
-(id)_ab_improved_description_body;
-(id)description;
@end

