/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ADRecord.h"
#import "Twitter-Structs.h"

@class NSString, UIImage, NSArray, NSData;

__attribute__((visibility("hidden")))
@interface ADPerson : ADRecord {
@private
	NSData* imageData;
	UIImage* profileImage;
	XXStruct_3sqDcB _flags;
}
@property(readonly, assign, nonatomic) NSArray* urls;
@property(readonly, assign, nonatomic) NSArray* emails;
@property(readonly, assign, nonatomic) NSArray* phones;
@property(copy, nonatomic) NSString* note;
@property(copy, nonatomic) NSString* nickname;
@property(copy, nonatomic) NSString* middleName;
@property(copy, nonatomic) NSString* lastName;
@property(copy, nonatomic) NSString* firstName;
+(id)localizedPropertyName:(int)name;
-(void*)createRecord;
-(void)dealloc;
-(BOOL)matchesSomeIdentitiesWith:(id)with;
-(BOOL)isEqual:(id)equal;
-(id)_ab_improved_description_body;
-(id)description;
-(id)displayName;
-(void)setFullName:(id)name;
-(id)canonicalIdentities;
-(void)addPhoneNumber:(id)number label:(id)label;
-(void)addEmail:(id)email label:(id)label;
-(void)addURL:(id)url label:(id)label;
-(id)imageData;
-(void)setImageData:(id)data;
-(id)profileImage;
-(int)multiValueIdentifierForURLString:(id)urlstring;
@end

