/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class ADBook;

__attribute__((visibility("hidden")))
@interface ADRecord : NSObject {
@private
	ADBook* book;
	void* record;
}
@property(readonly, assign, nonatomic) int recordID;
-(void*)createRecord;
-(id)initWithRecord:(void*)record book:(id)book;
-(void)dealloc;
-(id)_ab_improved_description_body;
-(id)description;
-(BOOL)isInAddressBook;
-(BOOL)isEqual:(id)equal;
-(void*)ABRecordRef;
-(void)addValue:(id)value label:(id)label forPropertyID:(int)propertyID;
-(void)removeValueForPropertyID:(int)propertyID;
-(void)setValue:(id)value forPropertyID:(int)propertyID;
-(id)valueForPropertyID:(int)propertyID matchPropertyType:(unsigned)type;
-(id)stringForPropertyID:(int)propertyID;
-(id)labelValueStringArrayForPropertyID:(int)propertyID;
@end

