/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewController.h"


__attribute__((visibility("hidden")))
@interface AdvancedSettingsViewController : ABStaticTableViewController {
}
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)autorotationOptions:(id)options info:(id)info;
-(void)loadTableView;
-(void)readLaterServiceUpdate:(id)update info:(id)info;
-(void)imageServiceUpdate:(id)update info:(id)info;
-(void)customImageService:(id)service info:(id)info;
-(void)quoteStyleDidChange:(id)quoteStyle info:(id)info;
-(void)installBookmarklet:(id)bookmarklet;
-(void)installBookmarklet:(id)bookmarklet info:(id)info;
@end

