/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"
#import <Foundation/NSObject.h>
#import "UIAlertViewDelegate.h"

@class ABCallback;

__attribute__((visibility("hidden")))
@interface AlertViewHelper : NSObject <UIActionSheetDelegate, UIAlertViewDelegate> {
@private
	ABCallback* callback;
}
@property(retain, nonatomic) ABCallback* callback;
-(void)dealloc;
-(void)alertView:(id)view willDismissWithButtonIndex:(int)buttonIndex;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
@end

