/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BirdhouseBridge.h"
#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface BirdhouseBridge : NSObject {
}
+(BOOL)canSaveToBirdhouse;
+(id)pasteboard;
+(BOOL)saveTweetToBirdhouse:(id)birdhouse;
+(id)tweetsOnPasteboard;
+(void)clearTweetsOnPasteboard;
@end

@interface BirdhouseBridge (TweetieAdditions)
+(BOOL)saveCompositionToBirdhouse:(id)birdhouse;
+(BOOL)isInstalled;
+(void)sendCompositionToBirdhouse:(id)birdhouse;
@end

