/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BitlyCompatibleShorteningService.h"


__attribute__((visibility("hidden")))
@interface BitlyShortener : BitlyCompatibleShorteningService {
}
-(id)login;
-(id)apiKey;
-(id)apiRoot;
-(BOOL)addBitlyParameters;
@end

