/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "URLShorteningService.h"


__attribute__((visibility("hidden")))
@interface BitlyCompatibleShorteningService : URLShorteningService {
}
+(id)parseBitlyResponseData:(id)data;
+(void)parseShortenJSON:(id)json info:(id)info;
-(id)apiKey;
-(id)login;
-(id)apiRoot;
-(id)apikeyParameterName;
-(id)longurlParameterName;
-(BOOL)addBitlyParameters;
-(void)shortenURLString:(id)string callback:(id)callback;
-(void)shortenURLResponse:(id)response info:(id)info;
@end

