/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface BlackPopoverPrompt : UIView {
@private
	NSString* title;
	NSString* text;
	NSString* button1;
}
-(void)showPromptPointingAt:(CGPoint)at;
@end

