/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol ChooseUserViewControllerDelegate
-(void)chooseUserViewController:(id)controller didChooseUser:(id)user;
-(void)chooseUserViewController:(id)controller didChooseUsername:(id)username;
-(void)chooseUserViewControllerDidCancel:(id)chooseUserViewController;
@end

