/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class TweetieSignUpCaptchaViewController, UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface CustomCaptchaHeader : UIView {
@private
	UIActivityIndicatorView* spinner;
	TweetieSignUpCaptchaViewController* controller;
}
-(id)initWithFrame:(CGRect)frame;
-(void)layoutSubviews;
-(void)drawRect:(CGRect)rect;
@end

