/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>
#import "FMDatabase.h"

@class NSString, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface FMDatabase : NSObject {
@private
	sqlite3* db;
	NSString* databasePath;
	BOOL logsErrors;
	BOOL crashOnErrors;
	BOOL inUse;
	BOOL inTransaction;
	BOOL traceExecution;
	BOOL checkedOut;
	int busyRetryTimeout;
	BOOL shouldCacheStatements;
	NSMutableDictionary* cachedStatements;
}
+(id)databaseWithPath:(id)path;
+(id)sqliteLibVersion;
-(id)initWithPath:(id)path;
-(void)dealloc;
-(id)databasePath;
-(sqlite3*)sqliteHandle;
-(BOOL)open;
-(BOOL)openWithFlags:(int)flags;
-(BOOL)close;
-(void)clearCachedStatements;
-(id)cachedStatementForQuery:(id)query;
-(void)setCachedStatement:(id)statement forQuery:(id)query;
-(BOOL)rekey:(id)rekey;
-(BOOL)setKey:(id)key;
-(BOOL)goodConnection;
-(void)compainAboutInUse;
-(id)lastErrorMessage;
-(BOOL)hadError;
-(int)lastErrorCode;
-(long long)lastInsertRowId;
-(void)bindObject:(id)object toColumn:(int)column inStatement:(sqlite3_stmt*)statement;
-(id)executeQuery:(id)query withArgumentsInArray:(id)array orVAList:(void*)list;
-(id)executeQuery:(id)query;
-(id)executeQuery:(id)query withArgumentsInArray:(id)array;
-(BOOL)executeUpdate:(id)update withArgumentsInArray:(id)array orVAList:(void*)list;
-(BOOL)executeUpdate:(id)update;
-(BOOL)executeUpdate:(id)update withArgumentsInArray:(id)array;
-(BOOL)rollback;
-(BOOL)commit;
-(BOOL)beginDeferredTransaction;
-(BOOL)beginTransaction;
-(BOOL)logsErrors;
-(void)setLogsErrors:(BOOL)errors;
-(BOOL)crashOnErrors;
-(void)setCrashOnErrors:(BOOL)errors;
-(BOOL)inUse;
-(void)setInUse:(BOOL)use;
-(BOOL)inTransaction;
-(void)setInTransaction:(BOOL)transaction;
-(BOOL)traceExecution;
-(void)setTraceExecution:(BOOL)execution;
-(BOOL)checkedOut;
-(void)setCheckedOut:(BOOL)anOut;
-(int)busyRetryTimeout;
-(void)setBusyRetryTimeout:(int)timeout;
-(BOOL)shouldCacheStatements;
-(void)setShouldCacheStatements:(BOOL)cacheStatements;
-(id)cachedStatements;
-(void)setCachedStatements:(id)statements;
-(int)changes;
@end

@interface FMDatabase (FMDatabaseAdditions)
-(id)stringForQuery:(id)query;
-(int)intForQuery:(id)query;
-(long)longForQuery:(id)query;
-(BOOL)boolForQuery:(id)query;
-(double)doubleForQuery:(id)query;
-(id)dataForQuery:(id)query;
-(id)dateForQuery:(id)query;
-(BOOL)tableExists:(id)exists;
-(id)getSchema;
-(id)getTableSchema:(id)schema;
-(BOOL)columnExists:(id)exists columnName:(id)name;
@end

@interface FMDatabase (ABAdditions)
@property(readonly, assign, nonatomic) sqlite3* dbHandle;
@end

