/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, NSMutableDictionary, FMStatement, FMDatabase;

__attribute__((visibility("hidden")))
@interface FMResultSet : NSObject {
@private
	FMDatabase* parentDB;
	FMStatement* statement;
	NSString* query;
	NSMutableDictionary* columnNameToIndexMap;
	BOOL columnNamesSetup;
}
+(id)resultSetWithStatement:(id)statement usingParentDatabase:(id)database;
-(void)dealloc;
-(void)close;
-(void)setupColumnNames;
-(void)kvcMagic:(id)magic;
-(id)resultDict;
-(BOOL)next;
-(BOOL)hasAnotherRow;
-(int)columnIndexForName:(id)name;
-(int)intForColumn:(id)column;
-(int)intForColumnIndex:(int)columnIndex;
-(long)longForColumn:(id)column;
-(long)longForColumnIndex:(int)columnIndex;
-(long long)longLongIntForColumn:(id)column;
-(long long)longLongIntForColumnIndex:(int)columnIndex;
-(BOOL)boolForColumn:(id)column;
-(BOOL)boolForColumnIndex:(int)columnIndex;
-(double)doubleForColumn:(id)column;
-(double)doubleForColumnIndex:(int)columnIndex;
-(id)stringForColumnIndex:(int)columnIndex;
-(id)stringForColumn:(id)column;
-(id)dateForColumn:(id)column;
-(id)dateForColumnIndex:(int)columnIndex;
-(id)dataForColumn:(id)column;
-(id)dataForColumnIndex:(int)columnIndex;
-(id)dataNoCopyForColumn:(id)column;
-(id)dataNoCopyForColumnIndex:(int)columnIndex;
-(BOOL)columnIndexIsNull:(int)null;
-(BOOL)columnIsNull:(id)null;
-(const char*)UTF8StringForColumnIndex:(int)columnIndex;
-(const char*)UTF8StringForColumnName:(id)columnName;
-(id)columnNameForIndex:(int)index;
-(void)setParentDB:(id)db;
-(id)query;
-(void)setQuery:(id)query;
-(id)columnNameToIndexMap;
-(void)setColumnNameToIndexMap:(id)indexMap;
-(id)statement;
-(void)setStatement:(id)statement;
@end

