/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface FMStatement : NSObject {
@private
	sqlite3_stmt* statement;
	NSString* query;
	long useCount;
}
-(void)dealloc;
-(void)close;
-(void)reset;
-(sqlite3_stmt*)statement;
-(void)setStatement:(sqlite3_stmt*)statement;
-(id)query;
-(void)setQuery:(id)query;
-(long)useCount;
-(void)setUseCount:(long)count;
-(id)description;
@end

