/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol FollowCostDelegate
-(void)followCost:(id)cost didUpdateForUser:(id)user;
-(void)followCost:(id)cost failedToUpdateForUser:(id)user withError:(id)error;
@end

