/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class TwitterUser, NSString;
@protocol FollowCostDelegate;

__attribute__((visibility("hidden")))
@interface FollowCost : NSObject {
@private
	id<FollowCostDelegate> delegate;
	BOOL loading;
	TwitterUser* user;
	NSString* averageTweetsPerDay;
	NSString* averageTweetsPerDayRecently;
	NSString* atReplyIndex;
	NSString* goldenIndex;
	NSString* politicalIndex;
}
@property(assign, nonatomic) id<FollowCostDelegate> delegate;
@property(readonly, assign, nonatomic) BOOL loading;
@property(copy, nonatomic) NSString* averageTweetsPerDay;
@property(copy, nonatomic) NSString* averageTweetsPerDayRecently;
@property(copy, nonatomic) NSString* atReplyIndex;
@property(copy, nonatomic) NSString* goldenIndex;
@property(copy, nonatomic) NSString* politicalIndex;
-(void)_load;
-(void)_didLoad:(id)load info:(id)info;
-(id)initWithTwitterUser:(id)twitterUser;
-(void)dealloc;
-(void)parseJSON:(id)json info:(id)info;
@end

