/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewController.h"
#import "Twitter-Structs.h"

@class FoursquareVenue, NSURL, TwitterAccount;

__attribute__((visibility("hidden")))
@interface FoursquareVenueViewController : ABStaticTableViewController {
@private
	TwitterAccount* account;
	NSURL* url;
	FoursquareVenue* venue;
	XXStruct_3sqDcB _flags;
}
@property(retain, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) NSURL* url;
@property(retain, nonatomic) FoursquareVenue* venue;
-(id)init;
-(void)dealloc;
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
-(void)loadTableView;
-(void)twitterUser:(id)user;
-(void)call:(id)call;
-(void)showMap:(id)map;
-(void)openInFoursquare:(id)foursquare;
-(void)viewWillAppear:(BOOL)view;
-(void)venueDetailsResponse:(id)response info:(id)info;
@end

