/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class FoursquareUser, NSDate, NSString;

__attribute__((visibility("hidden")))
@interface FoursquareCheckin : NSObject {
@private
	NSString* checkinID;
	NSDate* created;
	NSString* shout;
	FoursquareUser* user;
}
@end

