/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class FoursquareUser, NSString, NSDate, NSURL;

__attribute__((visibility("hidden")))
@interface FoursquareTip : NSObject {
@private
	NSString* tipID;
	NSString* text;
	NSURL* url;
	NSDate* created;
	FoursquareUser* user;
}
@end

