/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface Foursquare : NSObject {
}
+(void)venueDetailsFor4SQURL:(id)a4SQURL callback:(id)callback;
+(void)venueDetails4SQResponse:(id)response info:(id)info;
+(void)venueDetailsResponse:(id)response info:(id)info;
@end

