/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class FoursquareUser, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface FoursquareVenue : NSObject {
@private
	NSString* venueID;
	NSString* name;
	NSString* address;
	NSString* crossStreet;
	NSString* city;
	NSString* state;
	NSString* zip;
	NSString* phone;
	NSString* twitter;
	double latitude;
	double longitude;
	int numberOfCheckins;
	FoursquareUser* mayor;
	NSMutableArray* checkins;
	NSMutableArray* tips;
	NSMutableArray* specials;
}
@property(retain, nonatomic) NSString* venueID;
@property(retain, nonatomic) NSString* name;
@property(retain, nonatomic) NSString* address;
@property(retain, nonatomic) NSString* crossStreet;
@property(retain, nonatomic) NSString* city;
@property(retain, nonatomic) NSString* state;
@property(retain, nonatomic) NSString* zip;
@property(retain, nonatomic) NSString* phone;
@property(retain, nonatomic) NSString* twitter;
@property(assign, nonatomic) double latitude;
@property(assign, nonatomic) double longitude;
@property(assign, nonatomic) int numberOfCheckins;
@property(retain, nonatomic) FoursquareUser* mayor;
-(void)dealloc;
-(id)_ab_improved_description_body;
-(id)description;
-(void)parseXML:(id)xml info:(id)info;
-(void)parseVenueXML:(id)xml info:(id)info;
-(void)parseStatsXML:(id)xml info:(id)info;
-(void)parseMayorXML:(id)xml info:(id)info;
@end

