/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>

@class NSString, NSURL, ABImage;

__attribute__((visibility("hidden")))
@interface FusionAd : NSObject {
@private
	NSString* text;
	NSURL* imageURL;
	NSURL* link;
	ABImage* image;
	XXStruct_3sqDcB _flags;
}
@property(copy, nonatomic) NSString* text;
@property(retain, nonatomic) NSURL* imageURL;
@property(retain, nonatomic) NSURL* link;
@property(readonly, assign, nonatomic) ABImage* image;
-(void)dealloc;
-(id)init;
-(void)adResponse:(id)response info:(id)info;
-(void)imageResponse:(id)response info:(id)info;
-(void)parseAdXML_1_0:(id)a0 info:(id)info;
@end

