/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import "GeoRSSPoint.h"
#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>
#import "MKAnnotation.h"


__attribute__((visibility("hidden")))
@interface GeoRSSPoint : NSObject <NSCoding, MKAnnotation> {
@private
	BOOL didDecodePoint;
	double latitude;
	double longitude;
}
@property(assign, nonatomic) double latitude;
@property(assign, nonatomic) double longitude;
@property(readonly, assign, nonatomic) BOOL didDecodePoint;
@property(readonly, assign, nonatomic) XXStruct_zYrK5D coordinate;
+(id)geoPointWithDictionary:(id)dictionary;
-(void)parseDictionary:(id)dictionary;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(id)parseXMLCallback;
-(id)parseJSONCallback;
-(void)parseXML:(id)xml info:(id)info;
-(void)parseJSON:(id)json info:(id)info;
-(void)parseJSONCoordinates:(id)coordinates info:(id)info;
-(XXStruct_03F4WD)region;
-(id)annotationViewForMapView:(id)mapView;
-(id)title;
@end

@interface GeoRSSPoint (Search)
-(id)searchWithAccount:(id)account;
-(id)searchWithAccount:(id)account radius:(id)radius;
@end

@interface GeoRSSPoint (StaticMaps)
-(id)staticMapURLwithWidth:(int)width height:(int)height;
@end

