/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TweetieUserListViewController.h"


__attribute__((visibility("hidden")))
@interface GoToUserViewController : TweetieUserListViewController {
}
-(id)init;
-(void)dealloc;
-(id)persistentProxy;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(id)arbitraryUserFormatString;
-(void)selectUser:(id)user;
-(void)selectUsername:(id)username;
-(void)foundUsers:(id)users info:(id)info;
@end

