/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "NSMutableCopying.h"
#import <Foundation/NSDictionary.h>
#import "NSFastEnumeration.h"
#import "NSCopying.h"


__attribute__((visibility("hidden")))
@interface JKDictionary : NSDictionary <NSCopying, NSMutableCopying, NSFastEnumeration> {
@private
	unsigned count;
	unsigned capacity;
	unsigned mutations;
	JKHashTableEntry* entry;
}
+(void)load;
+(id)allocWithZone:(NSZone*)zone;
-(void)dealloc;
-(unsigned)count;
-(id)objectForKey:(id)key;
-(void)getObjects:(id*)objects andKeys:(id*)keys;
-(unsigned)countByEnumeratingWithState:(XXStruct_kFm5bA*)state objects:(id*)objects count:(unsigned)count;
-(id)keyEnumerator;
-(id)copyWithZone:(NSZone*)zone;
-(id)mutableCopyWithZone:(NSZone*)zone;
@end

