/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Twitter-Structs.h"


__attribute__((visibility("hidden")))
@interface JSONDecoder : NSObject {
@private
	JKParseState* parseState;
}
+(void)load;
+(id)decoder;
+(id)decoderWithParseOptions:(unsigned)parseOptions;
-(id)init;
-(id)initWithParseOptions:(unsigned)parseOptions;
-(void)dealloc;
-(void)clearCache;
-(id)parseUTF8String:(const char*)string length:(unsigned long)length;
-(id)parseUTF8String:(const char*)string length:(unsigned long)length error:(id*)error;
-(id)parseJSONData:(id)data;
-(id)parseJSONData:(id)data error:(id*)error;
-(id)objectWithUTF8String:(const char*)utf8String length:(unsigned)length;
-(id)objectWithUTF8String:(const char*)utf8String length:(unsigned)length error:(id*)error;
-(id)objectWithData:(id)data;
-(id)objectWithData:(id)data error:(id*)error;
-(id)mutableObjectWithUTF8String:(const char*)utf8String length:(unsigned)length;
-(id)mutableObjectWithUTF8String:(const char*)utf8String length:(unsigned)length error:(id*)error;
-(id)mutableObjectWithData:(id)data;
-(id)mutableObjectWithData:(id)data error:(id*)error;
@end

