/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABDocumentDisplayController.h"


__attribute__((visibility("hidden")))
@interface LegalViewController : ABDocumentDisplayController {
}
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)init;
-(id)documentPath;
@end

