/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface LinkQueue : NSObject {
@private
	NSString* username;
	NSString* password;
}
+(Class)preferredLinkQueueClass;
+(id)defaultLinkQueue;
+(id)defaultLinkQueueName;
+(id)defaultLinkQueueURLString;
+(id)defaultLinkQueueLoginTitle;
+(id)defaultLinkQueueLoginPlaceholder;
+(id)defaultLinkQueuePasswordPlaceholder;
-(id)initWithUsername:(id)username password:(id)password;
-(void)dealloc;
-(void)verifyCredentials:(id)credentials;
-(void)addURL:(id)url summary:(id)summary status:(id)status callback:(id)callback;
-(int)defaultsIntegerValue;
-(void)saveAsDefault;
@end

