/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LinkQueueAddAccountViewControllerDelegate.h"
#import <Foundation/NSObject.h>

@class NSString, UINavigationController, ABCallback, ABHUD;

__attribute__((visibility("hidden")))
@interface LinkQueueController : NSObject <LinkQueueAddAccountViewControllerDelegate> {
@private
	UINavigationController* navigationController;
	ABCallback* showLoginPanelCallback;
	NSString* link;
	NSString* summary;
	id refStatus;
	ABHUD* hud;
}
@property(retain, nonatomic) UINavigationController* navigationController;
+(id)controller;
-(void)dealloc;
-(void)_addLinkTo:(id)to;
-(void)_showLoginPanel;
-(void)didAddLink:(id)link info:(id)info;
-(void)addLink:(id)link summary:(id)summary status:(id)status navigationController:(id)controller;
-(void)didLoginInPreparationForAddingLink:(id)addingLink info:(id)info;
-(void)showLoginPanel:(id)panel callback:(id)callback;
-(void)linkQueueAddAccountViewControllerDismiss:(id)dismiss withLinkQueue:(id)linkQueue;
@end

