/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "Twitter-Structs.h"
#import "ABStaticTableViewController.h"

@class ABHUD, UITextField;
@protocol LinkQueueAddAccountViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface LinkQueueAddAccountViewController : ABStaticTableViewController <UITextFieldDelegate> {
@private
	id<LinkQueueAddAccountViewControllerDelegate> delegate;
	UITextField* usernameField;
	UITextField* passwordField;
	ABHUD* hud;
	BOOL hideHUDImmediatelyAfterVerifyingAccount;
}
@property(assign, nonatomic) id<LinkQueueAddAccountViewControllerDelegate> delegate;
@property(assign, nonatomic) BOOL hideHUDImmediatelyAfterVerifyingAccount;
-(void)dealloc;
-(void)loadTableView;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)view;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(void)save:(id)save;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)didVerify:(id)verify info:(id)info;
-(void)cancel:(id)cancel;
@end

