/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class FMDatabase;

__attribute__((visibility("hidden")))
@interface LocalAutocompleteDB : NSObject {
@private
	FMDatabase* db;
}
@property(readonly, assign, nonatomic) FMDatabase* db;
+(void)verifyDatabase;
+(id)databasePath;
+(id)sharedAutocompleteDB;
+(void)resetDatabase;
+(void)shutdown;
-(id)initWithPath:(id)path;
-(void)seedAccount:(id)account;
-(void)didReceiveFriends:(id)friends info:(id)info;
-(void)loadFromDisk;
-(void)saveToDisk;
-(id)execute:(id)execute;
-(void)loadSchema;
-(void)close;
-(void)dealloc;
-(void)setSynchronize:(BOOL)synchronize;
-(void)beginTransaction;
-(void)endTransaction;
-(void)addUser:(id)user;
-(void)addUsername:(id)username fullName:(id)name avatarURL:(id)url;
-(void)addHashtag:(id)hashtag description:(id)description;
-(void)addPlace:(id)place placeType:(int)type name:(id)name address:(id)address latitude:(id)latitude longitude:(id)longitude;
-(void)prioritizeUsername:(id)username;
-(void)prioritizeHashtag:(id)hashtag;
-(void)prioritizePlace:(id)place;
-(void)assimilateFromStatuses:(id)statuses;
-(void)compact;
-(id)defaultResultsForType:(int)type;
-(id)resultsForPartialText:(id)partialText type:(int)type;
-(id)placeAutocompletePrefixesNearPlace:(id)place;
@end

