/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>
#import "MKAnnotation.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface LocationPinAnnotation : NSObject <MKAnnotation> {
@private
	XXStruct_zYrK5D coordinate;
	NSString* title;
	NSString* subtitle;
}
@property(assign, nonatomic) XXStruct_zYrK5D coordinate;
@property(copy, nonatomic) NSString* title;
@property(copy, nonatomic) NSString* subtitle;
-(void)dealloc;
@end

