/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "URLShorteningService.h"


__attribute__((visibility("hidden")))
@interface LongURLShortener : URLShorteningService {
}
-(void)expandURLString:(id)string callback:(id)callback;
-(void)expandURLResponse:(id)response info:(id)info;
-(void)parseExpandJSON:(id)json info:(id)info;
@end

