/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "NSObject.h"


@protocol MKAnnotation <NSObject>
@property(readonly, assign, nonatomic) XXStruct_zYrK5D coordinate;
@optional
-(id)title;
-(id)subtitle;
-(void)setCoordinate:(XXStruct_zYrK5D)coordinate;
@end

