/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABImageService.h"


__attribute__((visibility("hidden")))
@interface Mobypicture : ABImageService {
}
+(id)adjustedImageURLForURL:(id)url insertPath:(id)path;
+(id)fullSizeImageURLForURL:(id)url;
+(id)thumbnailImageURLForURL:(id)url;
-(id)apiRoot;
-(id)apiKey;
-(id)OAuthEchoServiceProvider;
-(void)_postMedia:(id)media associatedMessage:(id)message fromAccount:(id)account callback:(id)callback;
-(void)postImage:(id)image associatedMessage:(id)message fromAccount:(id)account callback:(id)callback;
-(void)postVideo:(id)video associatedMessage:(id)message fromAccount:(id)account callback:(id)callback;
-(void)didPostMedia:(id)media info:(id)info;
-(void)parseMobyXML:(id)xml info:(id)info;
@end

