/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSData.h>


@interface NSData (ABAdditions)
-(id)ab_UTF8String;
-(id)gzipInflate;
-(id)gzipDeflate;
-(id)_ab_sha1Digest;
-(id)_ab_hexString;
@end

@interface NSData (Base64)
+(id)dataFromBase64String:(id)base64String;
-(id)initWithBase64String:(id)base64String;
-(id)base64EncodedString;
@end

@interface NSData (CommonHMAC)
-(id)HMACWithAlgorithm:(unsigned)algorithm;
-(id)HMACWithAlgorithm:(unsigned)algorithm key:(id)key;
@end

@interface NSData (LowLevelCommonCryptor)
-(id)_runCryptor:(CCCryptorRef)cryptor result:(int*)result;
-(id)dataEncryptedUsingAlgorithm:(unsigned)algorithm key:(id)key error:(int*)error;
-(id)dataEncryptedUsingAlgorithm:(unsigned)algorithm key:(id)key options:(unsigned)options error:(int*)error;
-(id)dataEncryptedUsingAlgorithm:(unsigned)algorithm key:(id)key initializationVector:(id)vector options:(unsigned)options error:(int*)error;
-(id)decryptedDataUsingAlgorithm:(unsigned)algorithm key:(id)key error:(int*)error;
-(id)decryptedDataUsingAlgorithm:(unsigned)algorithm key:(id)key options:(unsigned)options error:(int*)error;
-(id)decryptedDataUsingAlgorithm:(unsigned)algorithm key:(id)key initializationVector:(id)vector options:(unsigned)options error:(int*)error;
@end

@interface NSData (CommonCryptor)
+(id)randomAES256InitializationVector;
-(id)AES256EncryptedDataUsingKey:(id)key initializationVector:(id)vector error:(id*)error;
-(id)AES256EncryptedDataUsingKey:(id)key error:(id*)error;
-(id)decryptedAES256DataUsingKey:(id)key error:(id*)error;
-(id)DESEncryptedDataUsingKey:(id)key error:(id*)error;
-(id)decryptedDESDataUsingKey:(id)key error:(id*)error;
-(id)CASTEncryptedDataUsingKey:(id)key error:(id*)error;
-(id)decryptedCASTDataUsingKey:(id)key error:(id*)error;
@end

@interface NSData (CommonDigest)
-(id)MD2Sum;
-(id)MD4Sum;
-(id)MD5Sum;
-(id)SHA1Hash;
-(id)SHA224Hash;
-(id)SHA256Hash;
-(id)SHA384Hash;
-(id)SHA512Hash;
@end

@interface NSData (ABEncryption)
-(id)encryptWithKey:(id)key hmacKey:(id)key2 initializationVector:(id*)vector hmac:(id*)hmac;
@end

@interface NSData (ABSimpleArchive)
-(const char*)ab_classNameForSimpleEncoding;
-(void)ab_simpleEncode:(XXStruct_Z6OKRC*)encode;
-(id)ab_initWithSimpleDecoder:(XXStruct_Z6OKRC*)simpleDecoder;
@end

@interface NSData (JSONKit)
-(id)objectFromJSONData;
-(id)objectFromJSONDataWithParseOptions:(unsigned)parseOptions;
-(id)objectFromJSONDataWithParseOptions:(unsigned)parseOptions error:(id*)error;
-(id)mutableObjectFromJSONData;
-(id)mutableObjectFromJSONDataWithParseOptions:(unsigned)parseOptions;
-(id)mutableObjectFromJSONDataWithParseOptions:(unsigned)parseOptions error:(id*)error;
@end

