/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSDate.h>


@interface NSDate (ABAdditions)
-(BOOL)isBefore:(id)before;
-(BOOL)isAfter:(id)after;
-(id)mediumDateString;
-(id)longDateString;
-(id)_hour_minute_string;
-(void)_US_messagesStyleBoldString:(id*)string normalString:(id*)string2;
-(void)messagesStyleBoldString:(id*)string normalString:(id*)string2;
-(void)relativeStyleBoldString:(id*)string normalString:(id*)string2;
-(id)tinyRelativeTimeAgoString;
-(id)relativeTimeAgoString;
-(id)ISO8601String;
-(id)ab_beginningOfDay;
@end

@interface NSDate (ABSimpleArchive)
-(const char*)ab_classNameForSimpleEncoding;
-(void)ab_simpleEncode:(XXStruct_Z6OKRC*)encode;
-(id)ab_initWithSimpleDecoder:(XXStruct_Z6OKRC*)simpleDecoder;
@end

