/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSDateFormatter.h>


@interface NSDateFormatter (ABAdditions)
+(id)dateFormatterForHTTPLikeDate;
+(id)dateFormatterForJSONTwitterDate;
@end

