/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSDictionary.h>


@interface NSDictionary (ABAdditions)
-(id)mapFunction:(/*function-pointer*/ void*)function context:(void*)context;
-(id)URLParameterString;
@end

@interface NSDictionary (ABSimpleArchive)
-(const char*)ab_classNameForSimpleEncoding;
-(void)ab_simpleEncode:(XXStruct_Z6OKRC*)encode;
-(id)ab_initWithSimpleDecoder:(XXStruct_Z6OKRC*)simpleDecoder;
@end

@interface NSDictionary (JSONKit)
-(id)JSONData;
-(id)JSONDataWithOptions:(unsigned)options error:(id*)error;
-(id)JSONString;
-(id)JSONStringWithOptions:(unsigned)options error:(id*)error;
@end

