/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSMutableAttributedString.h>
#import "Twitter-Structs.h"

@class UIColor, UIFont;

@interface NSMutableAttributedString (ABUIAdditions)
@property(assign, nonatomic) int alignment;
@property(retain, nonatomic) UIColor* color;
@property(retain, nonatomic) UIFont* font;
-(NSRange)_stringRange;
-(void)setFont:(id)font inRange:(NSRange)range;
-(void)setColor:(id)color inRange:(NSRange)range;
@end

