/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSMutableString.h>
#import "Twitter-Structs.h"


@interface NSMutableString (RegexKitLiteAdditions)
-(unsigned)replaceOccurrencesOfRegex:(id)regex withString:(id)string;
-(unsigned)replaceOccurrencesOfRegex:(id)regex withString:(id)string range:(NSRange)range;
-(unsigned)replaceOccurrencesOfRegex:(id)regex withString:(id)string options:(unsigned)options range:(NSRange)range error:(id*)error;
@end

