/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSNumber.h>


@interface NSNumber (ABAdditions)
+(id)formattedDecimalStringForNumberString:(id)numberString;
+(id)formattedSizeOfBytes:(int)bytes;
-(id)URLEncodedString;
-(id)formattedDecimalString;
@end

@interface NSNumber (ABSimpleArchive)
-(const char*)ab_classNameForSimpleEncoding;
-(void)ab_simpleEncode:(XXStruct_Z6OKRC*)encode;
-(id)ab_initWithSimpleDecoder:(XXStruct_Z6OKRC*)simpleDecoder;
@end

