/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>


@protocol NSObject
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(Class)superclass;
-(Class)class;
-(id)self;
-(NSZone*)zone;
-(id)performSelector:(SEL)selector;
-(id)performSelector:(SEL)selector withObject:(id)object;
-(id)performSelector:(SEL)selector withObject:(id)object withObject:(id)object3;
-(BOOL)isProxy;
-(BOOL)isKindOfClass:(Class)aClass;
-(BOOL)isMemberOfClass:(Class)aClass;
-(BOOL)conformsToProtocol:(id)protocol;
-(BOOL)respondsToSelector:(SEL)selector;
-(id)retain;
-(oneway void)release;
-(id)autorelease;
-(unsigned)retainCount;
-(id)description;
@end

@interface NSObject (ABAdditions)
-(id)delayProxy;
-(id)backgroundProxy;
-(id)mainThreadProxy;
-(id)weakProxy;
-(void)dissociateWeakProxy;
-(id)weakMainThreadProxy;
-(id)callback:(id)callback;
-(id)isError;
-(void)_ab_setClass:(Class)aClass;
-(id)applicationSupportFolder;
@end

@interface NSObject (ABBackgroundThread)
+(void)_ab_runBackgroundThread;
-(id)_ab_sharedBackgroundThread;
-(void)performSelectorOnSharedBackgroundThread:(SEL)thread withObject:(id)object;
@end

@interface NSObject (ABAssociatedObjectAdditions)
-(void)ab_setAssignedAssociatedObject:(id)object forKey:(void*)key;
-(void)ab_setNonAtomicRetainedAssociatedObject:(id)object forKey:(void*)key;
-(id)ab_associatedObjectForKey:(void*)key;
@end

@interface NSObject (GoActiveTextRange)
-(void)navigateWithViewController:(id)viewController account:(id)account animated:(BOOL)animated;
@end

@interface NSObject (ABSimpleArchive)
-(const char*)ab_classNameForSimpleEncoding;
-(void)ab_simpleEncode:(XXStruct_Z6OKRC*)encode;
-(id)ab_initWithSimpleDecoder:(XXStruct_Z6OKRC*)simpleDecoder;
@end

@interface NSObject (YAJL)
-(id)ab_JSONString;
-(id)ab_JSONStringWithOptions:(unsigned)options indentString:(id)string;
@end

