/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSString.h>


@interface NSString (ABDateAdditions)
-(id)dateValueFromISO8601;
@end

@interface NSString (ABAdditions)
+(id)GUID;
-(id)base64EncodedString;
-(id)_ab_sha1Digest;
-(id)ab_UTF8String;
-(id)stringByRot13ingString;
-(BOOL)ab_containsRange:(NSRange)range;
-(id)ab_dictionaryFromParams;
-(BOOL)containsSubstring:(id)substring;
-(int)numberOfOccurrencesOfSubstring:(id)substring;
-(BOOL)containsSubstringIgnoringCase:(id)aCase;
-(BOOL)matchesPartialsSearchString:(id)string;
-(int)ab_editDistance:(id)distance;
-(BOOL)ab_fuzzyPrefixMatch:(id)match;
-(id)stringByUnescapingXMLEntities;
-(id)stringByEscapingXMLEntities;
-(int)caseInsensitiveCompare:(id)compare;
-(id)URLEncodedString;
-(id)ab_URLDecodedString:(BOOL)string;
-(id)dateValueFromHTTPLikeDate;
-(id)dateValueFromJSONTwitterDate;
-(int)ab_lengthAssumingRangesForRegex:(id)regex areReplacedByFixedLength:(int)length;
-(id)arrayOfRangesForRegex:(id)regex class:(Class)aClass;
-(id)arrayOfRangesForRegex:(id)regex;
-(int)activeStringType;
@end

@interface NSString (RegexKitLiteAdditions)
+(void)clearStringCache;
+(int)captureCountForRegex:(id)regex;
+(int)captureCountForRegex:(id)regex options:(unsigned)options error:(id*)error;
-(id)componentsSeparatedByRegex:(id)regex;
-(id)componentsSeparatedByRegex:(id)regex range:(NSRange)range;
-(id)componentsSeparatedByRegex:(id)regex options:(unsigned)options range:(NSRange)range error:(id*)error;
-(BOOL)isMatchedByRegex:(id)regex;
-(BOOL)isMatchedByRegex:(id)regex inRange:(NSRange)range;
-(BOOL)isMatchedByRegex:(id)regex options:(unsigned)options inRange:(NSRange)range error:(id*)error;
-(NSRange)rangeOfRegex:(id)regex;
-(NSRange)rangeOfRegex:(id)regex capture:(int)capture;
-(NSRange)rangeOfRegex:(id)regex inRange:(NSRange)range;
-(NSRange)rangeOfRegex:(id)regex options:(unsigned)options inRange:(NSRange)range capture:(int)capture error:(id*)error;
-(id)stringByMatching:(id)matching;
-(id)stringByMatching:(id)matching capture:(int)capture;
-(id)stringByMatching:(id)matching inRange:(NSRange)range;
-(id)stringByMatching:(id)matching options:(unsigned)options inRange:(NSRange)range capture:(int)capture error:(id*)error;
-(id)stringByReplacingOccurrencesOfRegex:(id)regex withString:(id)string;
-(id)stringByReplacingOccurrencesOfRegex:(id)regex withString:(id)string range:(NSRange)range;
-(id)stringByReplacingOccurrencesOfRegex:(id)regex withString:(id)string options:(unsigned)options range:(NSRange)range error:(id*)error;
@end

@interface NSString (RegexKitLiteEnumeratorAdditions)
-(id)matchEnumeratorWithRegex:(id)regex;
@end

@interface NSString (TwitterAdditions)
-(id)canonicalTwitterUserID;
-(id)canonicalTwitterUsername;
-(id)canonicalTwitterStatusID;
-(id)canonicalTwitterDirectMessageID;
@end

@interface NSString (ABEmoji)
+(id)emojiPhotoString;
+(id)emojiVideoString;
+(id)emojiAudioString;
+(id)emojiWarningString;
+(id)unicodeInfinityString;
@end

@interface NSString (ADAdditions)
-(id)stringByStrippingCharactersInSet:(id)set;
-(id)canonicalEmailString;
-(id)canonicalPhoneString;
-(id)canonicalURLString;
-(BOOL)isTextieablePhoneNumber;
@end

@interface NSString (OAuth)
-(id)ab_RFC3986EncodedString;
@end

@interface NSString (ABSimpleArchive)
-(const char*)ab_classNameForSimpleEncoding;
-(void)ab_simpleEncode:(XXStruct_Z6OKRC*)encode;
-(id)ab_initWithSimpleDecoder:(XXStruct_Z6OKRC*)simpleDecoder;
@end

@interface NSString (IFUnicodeURLHelpers)
-(id)IFUnicodeURL_splitAfterString:(id)string;
-(id)IFUnicodeURL_splitBeforeCharactersInSet:(id)set;
@end

@interface NSString (JSONKit)
-(id)objectFromJSONString;
-(id)objectFromJSONStringWithParseOptions:(unsigned)parseOptions;
-(id)objectFromJSONStringWithParseOptions:(unsigned)parseOptions error:(id*)error;
-(id)mutableObjectFromJSONString;
-(id)mutableObjectFromJSONStringWithParseOptions:(unsigned)parseOptions;
-(id)mutableObjectFromJSONStringWithParseOptions:(unsigned)parseOptions error:(id*)error;
@end

