/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSURL.h>


@interface NSURL (ADAdditions)
-(id)canonicalURLString;
@end

@interface NSURL (ABAdditions)
+(id)parseURLQueryString:(id)string;
+(id)ab_URLWithString:(id)string;
-(id)ab_displayString;
-(BOOL)isTalon;
@end

@interface NSURL (IFUnicodeURL)
+(id)URLWithUnicodeString:(id)unicodeString;
-(id)initWithUnicodeString:(id)unicodeString;
-(id)unicodeAbsoluteString;
-(id)unicodeHost;
@end

