/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface OAuth : NSObject {
}
+(void)requestRequestToken:(id)token consumerKey:(id)key consumerSecret:(id)secret oAuthCallback:(id)callback callback:(id)callback5;
+(void)requestTokenResponse:(id)response info:(id)info;
+(void)requestAccessToken:(id)token consumerKey:(id)key consumerSecret:(id)secret unauthorizedToken:(id)token4 unauthorizedSecret:(id)secret5 verifier:(id)verifier callback:(id)callback;
+(void)requestAccessResponse:(id)response info:(id)info;
@end

