/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MKAnnotation.h"
#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface PinAnnotation : NSObject <MKAnnotation> {
@private
	XXStruct_zYrK5D coordinate;
}
@property(assign, nonatomic) XXStruct_zYrK5D coordinate;
@end

