/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TwitPicCompatibleImageService.h"


__attribute__((visibility("hidden")))
@interface Posterous : TwitPicCompatibleImageService {
}
-(id)apiRoot;
-(id)messageParameterName;
-(id)mediaURLResponseTag;
-(BOOL)useOAuthEcho;
-(id)OAuthEchoServiceProvider;
@end

