/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LinkQueue.h"


__attribute__((visibility("hidden")))
@interface ReadItLater : LinkQueue {
}
+(id)defaultLinkQueueName;
+(id)defaultLinkQueueURLString;
+(id)defaultLinkQueueLoginTitle;
+(id)defaultLinkQueueLoginPlaceholder;
+(id)defaultLinkQueuePasswordPlaceholder;
-(int)defaultsIntegerValue;
-(void)verifyCredentials:(id)credentials;
-(void)verifyCredentialsResponse:(id)response info:(id)info;
-(void)addURL:(id)url summary:(id)summary status:(id)status callback:(id)callback;
-(void)addURLResponse:(id)response info:(id)info;
@end

