/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSEnumerator.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface RKLMatchEnumerator : NSEnumerator {
@private
	NSString* string;
	NSString* regex;
	unsigned location;
}
-(id)initWithString:(id)string regex:(id)regex;
-(id)nextObject;
-(void)dealloc;
@end

