/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "NSObject.h"


@protocol SearchRowViewDelegate <NSObject>
-(id)account;
-(void)searchRowViewDidBegin:(id)searchRowView;
-(void)searchRowViewDidCancel:(id)searchRowView;
-(void)searchFor:(id)aFor;
-(void)searchNearby:(id)nearby coordinates:(XXStruct_zYrK5D)coordinates;
-(void)gotoUsername:(id)username;
-(void)gotoUser:(id)user;
@end

