/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class NSArray;
@protocol SearchTabsDelegate;

__attribute__((visibility("hidden")))
@interface SearchTabs : UIView {
@private
	id<SearchTabsDelegate> delegate;
	NSArray* titles;
	int selectedIndex;
}
@property(assign, nonatomic) id<SearchTabsDelegate> delegate;
@property(copy, nonatomic) NSArray* titles;
@property(assign, nonatomic) int selectedIndex;
-(void)dealloc;
-(CGRect)frameForIndex:(int)index;
-(void)drawRect:(CGRect)rect;
-(void)touchesBegan:(id)began withEvent:(id)event;
@end

