/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "SearchTabsDelegate.h"
#import "ABRowView.h"
#import "Twitter-Structs.h"

@class CLLocation, UIButton, MKPlacemark, ABPlainRowCell, NSString, SearchTabs, UITextField;
@protocol SearchRowViewDelegate;

__attribute__((visibility("hidden")))
@interface SearchRowView : ABRowView <UITextFieldDelegate, SearchTabsDelegate> {
@private
	id<SearchRowViewDelegate> searchDelegate;
	int context;
	UITextField* textField;
	UIButton* cancelButton;
	SearchTabs* tabs;
	ABRowView* resultsGroup;
	ABRowView* _highlightOnReturn;
	ABPlainRowCell* nearbySection;
	ABPlainRowCell* gotouserRow;
	ABPlainRowCell* searchNearbyRow;
	id gpsRequestToken;
	MKPlacemark* mostRecentPlacemark;
	CLLocation* mostRecentLocation;
	NSString* findUsersSearchToken;
	BOOL active;
	struct {
		unsigned allTweets;
		unsigned nearby;
		unsigned people;
	} tabIndex;
}
@property(assign, nonatomic) id<SearchRowViewDelegate> searchDelegate;
@property(retain, nonatomic) CLLocation* mostRecentLocation;
@property(retain, nonatomic) MKPlacemark* mostRecentPlacemark;
@property(retain, nonatomic) NSString* findUsersSearchToken;
@property(assign, nonatomic) int context;
-(void)_updateZ;
-(id)init;
-(void)dealloc;
-(void)setActive:(BOOL)active;
-(id)strippedToUsername;
-(id)nearbyString;
-(void)_updateResults;
-(void)gpsUpdate:(id)update info:(id)info;
-(void)searchTabs:(id)tabs didSelectIndex:(int)index;
-(void)textFieldDidBeginEditing:(id)textField;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)textFieldShouldClear:(id)textField;
-(void)cancel:(id)cancel;
-(void)textFieldDidEndEditing:(id)textField;
-(void)searchAllTweets:(id)tweets;
-(void)searchNearbyTweets:(id)tweets;
-(void)searchPeople:(id)people;
-(void)findUsersResponse:(id)response info:(id)info;
-(void)selectUser:(id)user;
-(void)gotoUser:(id)user;
-(BOOL)textFieldShouldReturn:(id)textField;
@end

