/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABTableViewCell.h"
#import "Twitter-Structs.h"
#import "ABUITextRendererDelegate.h"

@class NSObject, NSDate, TwitterDirectMessage, NSString, ABUITextRenderer, UIImage, NSAttributedString;
@protocol ABActiveTextRange, TouchAndHoldCellDelegate;

__attribute__((visibility("hidden")))
@interface SMSStyleMessageCell : ABTableViewCell <ABUITextRendererDelegate> {
@private
	ABUITextRenderer* renderer;
	id<ABActiveTextRange> touchedActiveRange;
	TwitterDirectMessage* message;
	NSString* nameText;
	NSString* messageText;
	UIImage* image;
	NSDate* date;
	NSObject<TouchAndHoldCellDelegate>* delegate;
	BOOL mine;
	BOOL selected;
}
@property(retain, nonatomic) TwitterDirectMessage* message;
@property(retain, nonatomic) id<ABActiveTextRange> touchedActiveRange;
@property(retain, nonatomic) NSString* nameText;
@property(retain, nonatomic) NSString* messageText;
@property(retain, nonatomic) UIImage* image;
@property(retain, nonatomic) NSDate* date;
@property(assign, nonatomic) BOOL mine;
@property(assign, nonatomic) NSObject<TouchAndHoldCellDelegate>* delegate;
@property(assign, nonatomic) BOOL selected;
@property(retain, nonatomic) NSAttributedString* attributedMessageText;
+(id)messageFont;
+(id)nameFont;
+(CGRect)messageRectForWidth:(float)width;
+(CGSize)sizeForMessage:(id)message maxWidth:(float)width;
+(float)heightForMessage:(id)message inTableView:(id)tableView error:(BOOL)error;
-(BOOL)hasError;
-(void)dealloc;
-(id)activeRangesForTextRenderer:(id)textRenderer;
-(CGRect)imageRect;
-(float)errorPadding;
-(CGRect)_bubbleRect:(CGSize)rect;
-(CGRect)bubbleRect;
-(CGSize)textSize;
-(void)drawContentView:(CGRect)view;
-(id)timeStampString;
-(void)touchAndHold:(id)hold;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)didTapActiveRange:(id)range;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
@end

