/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface StatusIDSync : NSObject {
}
+(void)setValue:(id)value forKey:(id)key;
+(void)setResponse:(id)response info:(id)info;
+(void)requestValueForKey:(id)key callback:(id)callback;
+(void)requestResponse:(id)response info:(id)info;
+(void)parseResponseXML:(id)xml info:(id)info;
@end

