/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class TIComposeAttachmentsView, TwitterCompositionAttachment, UIButton;

__attribute__((visibility("hidden")))
@interface TIAttachmentView : UIView {
@private
	TIComposeAttachmentsView* attachmentsView;
	TwitterCompositionAttachment* attachment;
	UIButton* deleteButton;
}
@property(retain, nonatomic) TwitterCompositionAttachment* attachment;
@property(assign, nonatomic) TIComposeAttachmentsView* attachmentsView;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)layoutSubviews;
-(void)drawRect:(CGRect)rect;
-(void)delete:(id)aDelete;
@end

