/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class UIButton, NSMutableArray, UIScrollView;
@protocol TIComposeAttachmentsViewDelegate;

__attribute__((visibility("hidden")))
@interface TIComposeAttachmentsView : UIView {
@private
	id<TIComposeAttachmentsViewDelegate> delegate;
	UIScrollView* _scrollView;
	NSMutableArray* attachmentViews;
	UIButton* cameraButton;
	UIButton* libraryButton;
	XXStruct_3sqDcB _flags;
}
@property(assign, nonatomic) id<TIComposeAttachmentsViewDelegate> delegate;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)camera:(id)camera;
-(void)photoLibrary:(id)library;
-(id)attachmentViewForAttachment:(id)attachment;
-(void)didDelete:(id)aDelete finished:(id)finished context:(void*)context;
-(void)_updateAddMoreButtonState;
-(void)deleteAttachment:(id)attachment;
-(void)reload;
-(CGRect)buttonFrame:(int)frame;
-(void)layoutSubviews;
@end

