/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>
#import "MKMapViewDelegate.h"

@class UILabel, UIButton, UIImageView, MKMapView, UISwitch;
@protocol TIComposeMapViewDelegate;

__attribute__((visibility("hidden")))
@interface TIComposeMapView : UIView <MKMapViewDelegate> {
@private
	id<TIComposeMapViewDelegate> delegate;
	MKMapView* _mapView;
	UIImageView* _outline;
	UISwitch* _switch;
	UILabel* _label;
	UIButton* _toggleButton;
	UILabel* _fromLabel;
	XXStruct_zYrK5D _lastLocation;
}
@property(assign, nonatomic) id<TIComposeMapViewDelegate> delegate;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)layoutSubviews;
-(void)toggleGeo:(id)geo;
-(void)reload;
-(XXStruct_zYrK5D)coordinate;
-(void)updateMap;
-(id)mapView:(id)view viewForAnnotation:(id)annotation;
-(void)updateMapLabel:(id)label;
@end

