/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol TIComposeAttachmentsViewDelegate <NSObject>
-(id)account;
-(id)composition;
-(void)camera:(id)camera;
-(void)photoLibrary:(id)library;
-(void)didRemoveAttachment:(id)attachment;
@end

