/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class UILabel, UIProgressView;

__attribute__((visibility("hidden")))
@interface TISendProgressView : UIView {
@private
	UILabel* label;
	UIProgressView* progressBar;
}
@property(readonly, assign, nonatomic) UILabel* label;
@property(readonly, assign, nonatomic) UIProgressView* progressBar;
-(id)initWithFrame:(CGRect)frame;
-(void)layoutSubviews;
@end

