/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface TLists : NSObject {
}
+(void)searchTweeters:(id)tweeters page:(id)page callback:(id)callback;
+(void)searchTweetersResponse:(id)response info:(id)info;
+(void)parseSearchTweetersJSON:(id)json info:(id)info;
+(void)parseSearchTweeterJSON:(id)json info:(id)info;
@end

