/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TwitterUser.h"


__attribute__((visibility("hidden")))
@interface TListsPerson : TwitterUser {
@private
	float tweetsPerDay;
}
@property(assign, nonatomic) float tweetsPerDay;
-(void)parseSearchTweeter:(id)tweeter info:(id)info;
@end

