/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class UIActivityIndicatorView, UIImageView, UIScrollView;

__attribute__((visibility("hidden")))
@interface TopTweetsRailView : UIView {
@private
	id delegate;
	UIScrollView* scrollView;
	UIImageView* border;
	UIActivityIndicatorView* spinner;
	int numberOfTopTweets;
}
@property(assign, nonatomic) id delegate;
-(CGRect)frameForTag:(int)tag;
-(void)updateBlocks;
-(id)initWithFrame:(CGRect)frame;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
-(void)setTopTweets:(id)tweets;
@end

