/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol TopTweetsRailViewDelegate
-(void)topTweetsRailView:(id)view selectedTweet:(id)tweet;
-(void)topTweetsRailViewShowAllTopTweets:(id)tweets;
@end

