/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABSimplePersistentRecentSearchViewController.h"

@class TwitterAccount;

__attribute__((visibility("hidden")))
@interface TweetieNewSearchViewController : ABSimplePersistentRecentSearchViewController {
@private
	TwitterAccount* account;
}
@property(retain, nonatomic) TwitterAccount* account;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)dealloc;
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
-(id)defaultsKey;
-(id)placeholderText;
-(id)unmatchedResultFormatText;
-(void)search:(id)search;
-(void)cancel:(id)cancel;
@end

