/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TweetieAbstractSearchController.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface TweetieSearchPeopleController : TweetieAbstractSearchController {
@private
	NSArray* cachedUsers;
	NSArray* matchingUsers;
	NSArray* searchResults;
	struct {
		unsigned touchState : 3;
	} _flags;
}
-(void)dealloc;
-(BOOL)couldBeUsername;
-(id)usersMatching:(id)matching;
-(id)matchingUsers;
-(void)updateMatchingUsers;
-(void)searchBar:(id)bar textDidChange:(id)text;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)findUsers;
-(void)_returnToRecentsMode;
-(void)findUsersResponse:(id)response info:(id)info;
-(void)searchBarSearchButtonClicked:(id)clicked;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
@end

