/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "SMSStyleMessageCell.h"

@class ABCallback, UIButton, TwitterAccount, TweetieConversationViewController;

__attribute__((visibility("hidden")))
@interface TweetieDirectMessageCell : SMSStyleMessageCell {
@private
	TwitterAccount* account;
	TweetieConversationViewController* conversationViewController;
	UIButton* profileImageButton;
	UIButton* errorButton;
	ABCallback* retryCallback;
}
@property(assign, nonatomic) TwitterAccount* account;
@property(assign, nonatomic) TweetieConversationViewController* conversationViewController;
@property(retain, nonatomic) ABCallback* retryCallback;
@property(readonly, assign, nonatomic) UIButton* errorButton;
+(id)messageFont;
-(void)dealloc;
-(id)timeStampString;
-(void)layoutSubviews;
-(void)retrySend:(id)send;
-(void)userDetails:(id)details;
-(void)_updateImage;
-(BOOL)hasError;
-(void)updateErrorButton;
-(void)setMessage:(id)message;
-(void)didUpdate:(id)update;
-(void)drawContentView:(CGRect)view;
-(BOOL)canBecomeFirstResponder;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
-(void)copy:(id)copy;
-(void)didTapActiveRange:(id)range;
@end

