/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>


__attribute__((visibility("hidden")))
@interface TweetieUserProfile4WayCornerSelectionView : UIView {
@private
	int cornerMask;
}
@property(assign, nonatomic) int cornerMask;
-(void)drawRect:(CGRect)rect;
@end

