/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TweetieAbstractSearchController.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface TweetieSearchAllTweetsController : TweetieAbstractSearchController {
@private
	NSArray* matchingSearches;
}
-(void)dealloc;
-(id)recentSearches;
-(id)recentSearchesMatching:(id)matching;
-(id)matchingRecentSearches;
-(void)updateMatchingSearches;
-(id)matchingSearchAtIndex:(int)index;
-(void)saveRecentSearch:(id)search;
-(BOOL)removeRecentSearch:(id)search;
-(void)searchBar:(id)bar textDidChange:(id)text;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(BOOL)_isNearbySearch;
-(id)nearString;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)startSearch:(id)search;
-(void)doSearchFor:(id)aFor;
-(void)searchForSearchText;
-(void)searchBarSearchButtonClicked:(id)clicked;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
@end

