/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABWebViewController.h"

@class ABCallback, TwitterAccount;

__attribute__((visibility("hidden")))
@interface TweetieConfigureGeotagViewController : ABWebViewController {
@private
	TwitterAccount* account;
	ABCallback* callback;
}
@property(retain, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) ABCallback* callback;
-(void)dealloc;
-(void)viewDidLoad;
-(void)done:(id)done;
@end

