/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol TweetieTweetViewControllerDelegate
-(BOOL)tweetViewController:(id)controller canNavigate:(int)navigate;
-(void)tweetViewController:(id)controller navigate:(int)navigate;
-(void)tweetViewController:(id)controller getCurrentIndex:(int*)index of:(int*)of;
@end

