/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>
#import "MKAnnotation.h"

@class TwitterStatus;

__attribute__((visibility("hidden")))
@interface TweetieStatusAnnotation : NSObject <MKAnnotation> {
@private
	TwitterStatus* status;
	XXStruct_zYrK5D coordinate;
}
@property(retain, nonatomic) TwitterStatus* status;
@property(readonly, assign, nonatomic) XXStruct_zYrK5D coordinate;
-(void)dealloc;
-(id)title;
-(id)subtitle;
@end

