/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABTableViewPullToRefreshDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import <UIKit/UIViewController.h>
#import "UISearchBarDelegate.h"
#import "Twitter-Structs.h"

@class ABTableViewPullToRefreshController, UISearchBar, UISearchDisplayController, UITableView, TweetieGeoSearchDelegate, TwitterPlace, UIView, NSMutableArray, NSString, NSObject;
@protocol ABPlacePickerDelegate;

__attribute__((visibility("hidden")))
@interface TweetiePickPlaceViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, ABTableViewPullToRefreshDelegate> {
@private
	int pickPlaceMode;
	UISearchDisplayController* searchController;
	TwitterPlace* pickedPlace;
	TweetieGeoSearchDelegate* geoSearchDelegate;
	UITableView* _tableView;
	UISearchBar* searchBar;
	NSObject<ABPlacePickerDelegate>* delegate;
	NSString* token;
	ABTableViewPullToRefreshController* pullToRefreshController;
	NSMutableArray* places;
	UIView* loadingView;
	BOOL isSearching;
	BOOL isLoadingNewer;
	BOOL refreshOnLoad;
}
@property(retain, nonatomic) TwitterPlace* pickedPlace;
@property(retain, nonatomic) NSObject<ABPlacePickerDelegate>* delegate;
@property(assign, nonatomic) BOOL isLoadingNewer;
@property(assign, nonatomic) BOOL refreshOnLoad;
@property(readonly, assign, nonatomic) NSMutableArray* places;
-(void)_refresh;
-(void)_endNotifications;
-(void)loadView;
-(void)viewDidLoad;
-(void)userDidTouchCancel:(id)user;
-(void)userDidTouchClear:(id)user;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(void)pullToRefreshController:(id)refreshController didActivate:(BOOL)activate;
-(void)updateList;
-(void)nearbyPlacesDidRefresh:(id)nearbyPlaces;
-(void)nearbyPlacesDidError:(id)nearbyPlaces;
-(void)didReceiveMemoryWarning;
-(void)viewDidUnload;
-(void)dealloc;
@end

