/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TweetieUserListViewController.h"
#import "Twitter-Structs.h"

@class TwitterSULCategory;

__attribute__((visibility("hidden")))
@interface TweetieSULCategoryViewController : TweetieUserListViewController {
@private
	TwitterSULCategory* category;
	BOOL registered;
}
@property(retain, nonatomic) TwitterSULCategory* category;
-(void)dealloc;
-(BOOL)showComposeButton;
-(void)viewDidLoad;
-(void)_updateUsers;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(BOOL)automaticallyDeselect;
@end

