/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TweetieStatusListViewController.h"
#import "Twitter-Structs.h"

@class TwitterStream;

__attribute__((visibility("hidden")))
@interface TweetieStatusStreamViewController : TweetieStatusListViewController {
@private
	XXStruct_3sqDcB _streamFlags;
	XXStruct_3sqDcB _impressionFlags;
}
@property(readonly, assign, nonatomic) TwitterStream* statusStream;
-(void)dealloc;
-(void)streamDidUpdate:(id)stream;
-(void)streamError:(id)error;
-(void)ab_attemptToRecordImpressionFromReferringEvent:(id)referringEvent;
-(void)ab_resetImpression;
-(id)ab_referrerID;
-(void)recordImpressionFromReferringEvent:(id)referringEvent;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)syncStreamPosition:(id)position;
-(void)requestTopStatusID;
-(void)noteNewTopStatusID:(id)anId;
-(void)loadOlder:(id)older;
-(void)loadNewer:(id)newer;
-(void)fillInGap:(id)gap;
-(BOOL)isLoadingNewer;
-(id)lastUpdated;
-(id)autosaveName;
@end

