/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"
#import <Foundation/NSObject.h>

@class NSString, UINavigationController, NSMutableIndexSet, UIActionSheet, TwitterAccount;

__attribute__((visibility("hidden")))
@interface TweetieShowLinksForStringHelper : NSObject <UIActionSheetDelegate> {
@private
	TwitterAccount* account;
	UIActionSheet* sheet;
	UINavigationController* navigationController;
	NSString* sourceString;
	NSMutableIndexSet* linksSet;
	NSMutableIndexSet* usernamesSet;
	NSMutableIndexSet* hashtagsSet;
	NSMutableIndexSet* emailAddressesSet;
	NSMutableIndexSet* stockSymbolsSet;
}
@property(retain, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) UINavigationController* navigationController;
-(id)init;
-(void)dealloc;
-(BOOL)showForString:(id)string;
-(void)actionSheet:(id)sheet didDismissWithButtonIndex:(int)buttonIndex;
-(void)dismissSheet;
@end

