/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"
#import "Twitter-Structs.h"
#import "UIDocumentInteractionControllerDelegate.h"
#import <UIKit/UITableViewController.h>
#import "UINavigationControllerDelegate.h"

@class TwitterCompositionAttachment;
@protocol TweetieComposeAttachmentsViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface TweetieComposeAttachmentsViewController : UITableViewController <UIActionSheetDelegate, UINavigationControllerDelegate, UIDocumentInteractionControllerDelegate> {
@private
	TwitterCompositionAttachment* _selectedAttachment;
	id<TweetieComposeAttachmentsViewControllerDelegate> attachmentsDelegate;
}
@property(assign, nonatomic) id<TweetieComposeAttachmentsViewControllerDelegate> attachmentsDelegate;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)account;
-(id)composition;
-(void)_updateTitle;
-(void)viewDidLoad;
-(void)addAttachment:(id)attachment;
-(void)viewWillAppear:(BOOL)view;
-(id)attachmentAtIndex:(int)index;
-(BOOL)promptForAddAttachment;
-(BOOL)isValidIndex:(id)index;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)addAttachmentText;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForDeleteConfirmationButtonForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)movieFinishedCallback:(id)callback;
-(void)didEditVideo:(id)video info:(id)info;
@end

