/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIButton.h>

@class ABCallback;

__attribute__((visibility("hidden")))
@interface TweetiePromotedButton : UIButton {
@private
	ABCallback* callback;
}
@property(retain, nonatomic) ABCallback* callback;
+(id)textColor;
+(id)textShadowColor;
+(id)font;
+(id)promotedLabelAt:(CGPoint)at callback:(id)callback;
-(void)didClickPromotedLabel:(id)label;
-(void)fitText;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
@end

