/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface TweetieListViewControllerController : NSObject {
}
+(id)barButtonItemsForList:(id)list account:(id)account flipped:(BOOL)flipped target:(id)target;
+(void)flipButton:(id)button transition:(int)transition;
@end

