/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MKMapViewDelegate.h"
#import "TweetiePlaceMapTapDetectorDelegate.h"
#import "TweetieSearchResultsViewController.h"
#import "Twitter-Structs.h"

@class TwitterPlace, MKMapView, UIActivityIndicatorView, UIView, GeoRSSPoint;

__attribute__((visibility("hidden")))
@interface TweetiePlaceSearchResultsViewController : TweetieSearchResultsViewController <MKMapViewDelegate, TweetiePlaceMapTapDetectorDelegate> {
@private
	TwitterPlace* place;
	GeoRSSPoint* location;
	UIActivityIndicatorView* mapSpinner;
	UIView* mapViewContainer;
	MKMapView* mapView;
	UIView* shadowView;
}
@property(retain, nonatomic) TwitterPlace* place;
@property(retain, nonatomic) GeoRSSPoint* location;
-(id)initWithPlace:(id)place location:(id)location account:(id)account;
-(id)autosaveName;
-(void)_updateTitle;
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
-(id)mapView:(id)view viewForAnnotation:(id)annotation;
-(float)_headerExtraOffset;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)_loadFullPlace;
-(void)didLoadFullPlace:(id)place info:(id)info;
-(void)loadHeaderView;
-(void)viewDidUnload;
-(id)mapView:(id)view viewForOverlay:(id)overlay;
-(void)tapDetector:(id)detector didReceiveTap:(id)tap;
-(void)dealloc;
@end

