/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class TwitterList;

__attribute__((visibility("hidden")))
@interface TweetieListCell : UITableViewCell {
@private
	TwitterList* list;
}
@property(retain, nonatomic) TwitterList* list;
-(id)initWithList:(id)list;
-(void)dealloc;
@end

