/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "SMSStyleConversationCell.h"

@class TwitterDirectMessageConversation;

__attribute__((visibility("hidden")))
@interface TweetieConversationCell : SMSStyleConversationCell {
@private
	TwitterDirectMessageConversation* conversation;
}
@property(retain, nonatomic) TwitterDirectMessageConversation* conversation;
-(void)dealloc;
-(void)userDidUpdate:(id)user;
@end

