/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIPopoverControllerDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "ABStaticTableViewController.h"

@class UIBarButtonItem, UIPopoverController, NSString, TwitterAccount;
@protocol TweetieEditProfileViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface TweetieEditProfileViewController : ABStaticTableViewController <UIActionSheetDelegate, UIPopoverControllerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate> {
@private
	id<TweetieEditProfileViewControllerDelegate> editProfileDelegate;
	TwitterAccount* account;
	UIBarButtonItem* saveButton;
	NSString* updatedProfileImageFile;
	NSString* updatedName;
	NSString* updatedURL;
	NSString* updatedLocation;
	NSString* updatedBio;
	UIPopoverController* imagePickerPopover;
}
@property(retain, nonatomic) TwitterAccount* account;
@property(assign, nonatomic) id<TweetieEditProfileViewControllerDelegate> editProfileDelegate;
+(void)_showIfError:(id)error;
+(void)updateProfileImageResponse:(id)response info:(id)info;
+(void)updateProfileResponse:(id)response info:(id)info;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)dealloc;
-(void)loadTableView;
-(void)profileImage:(id)image;
-(BOOL)canUpdateImage;
-(BOOL)canUpdateProfile;
-(BOOL)canSave;
-(void)imagePickerController:(id)controller didFinishPickingMediaWithInfo:(id)info;
-(void)imagePickerControllerDidCancel:(id)imagePickerController;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(void)name:(id)name;
-(void)setName:(id)name info:(id)info;
-(void)url:(id)url;
-(void)setURL:(id)url info:(id)info;
-(void)location:(id)location;
-(void)setLocation:(id)location info:(id)info;
-(void)bio:(id)bio;
-(void)setBio:(id)bio info:(id)info;
-(void)viewDidLoad;
-(void)choseMedia:(id)media info:(id)info;
-(void)viewWillAppear:(BOOL)view;
-(void)cancel:(id)cancel;
-(void)save:(id)save;
@end

