/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TweetieComposeViewControllerDelegate.h"
#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>

@class UINavigationController, TweetieComposeViewController;

__attribute__((visibility("hidden")))
@interface TweetieComposeController : NSObject <TweetieComposeViewControllerDelegate> {
@private
	TweetieComposeViewController* composeViewController;
	UINavigationController* sourceNavigationController;
	XXStruct_3sqDcB _flags;
}
+(Class)noAnimation;
+(id)controller;
+(id)composeWithComposition:(id)composition fromAccount:(id)account sourceNavigationController:(id)controller;
+(void)newTweetFromAccount:(id)account sourceNavigationController:(id)controller;
+(void)newTweetWithText:(id)text fromAccount:(id)account sourceNavigationController:(id)controller;
+(void)replyToTweet:(id)tweet fromAccount:(id)account sourceNavigationController:(id)controller;
+(void)quoteTweet:(id)tweet fromAccount:(id)account sourceNavigationController:(id)controller;
+(void)repostLink:(id)link fromStatus:(id)status fromAccount:(id)account sourceNavigationController:(id)controller;
+(void)retweet:(id)retweet fromAccount:(id)account sourceNavigationController:(id)controller;
+(void)retweetResponse:(id)response info:(id)info;
+(void)replyToUser:(id)user fromAccount:(id)account sourceNavigationController:(id)controller;
+(void)directMessageUser:(id)user fromAccount:(id)account sourceNavigationController:(id)controller;
+(void)directMessageUsername:(id)username fromAccount:(id)account sourceNavigationController:(id)controller;
-(BOOL)animated;
-(void)dealloc;
-(void)forceDismissAndSaveAsDraft;
-(void)showComposeViewController:(id)controller sourceNavigationController:(id)controller2;
-(void)composeViewControllerDidDismiss:(id)composeViewController;
@end

