/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TwitPicCompatibleImageService.h"


__attribute__((visibility("hidden")))
@interface TweetPhoto : TwitPicCompatibleImageService {
}
+(id)thumbnailImageURLForURL:(id)url;
+(id)fullSizeImageURLForURL:(id)url;
-(id)OAuthEchoServiceProvider;
-(void)addMoarStuff:(id)stuff;
-(id)apiRoot;
-(id)apiKeyParameterName;
-(id)apiKey;
-(id)mediaURLResponseTag;
@end

