/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class TweetieStatusCell, UIButton;

__attribute__((visibility("hidden")))
@interface TweetieStatusCellContextView : UIView {
@private
	TweetieStatusCell* statusCell;
	UIButton* replyButton;
	UIButton* linkButton;
	UIButton* userButton;
	UIButton* retweetButton;
	UIButton* favoriteButton;
	UIButton* actionButton;
}
-(CGRect)frameForIndex:(int)index;
-(id)imageForButton:(int)button;
-(id)accessibilityLabelForButton:(int)button;
-(id)button:(int)button;
-(BOOL)shouldEnableLinkButton;
-(BOOL)shouldEnableRetweetButton;
-(id)initWithFrame:(CGRect)frame statusCell:(id)cell;
-(void)setupButtons;
-(void)layoutSubviews;
-(void)animate:(id)animate delay:(float)delay;
-(void)animateIn;
-(void)drawRect:(CGRect)rect;
-(void)contextAction:(id)action;
@end

