/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface TweetieSettings : NSObject {
@private
	int fontSize;
	int displayName;
	SEL displayNameSelector;
	int quoteSyntax;
	int dateFormatStyle;
}
@property(assign, nonatomic) int fontSize;
@property(readonly, assign, nonatomic) int displayName;
@property(readonly, assign, nonatomic) SEL displayNameSelector;
@property(readonly, assign, nonatomic) int quoteSyntax;
@property(readonly, assign, nonatomic) int dateFormatStyle;
@property(readonly, assign, nonatomic) BOOL placeAutoComplete;
+(id)sharedSettings;
-(id)init;
-(void)setupInitialSettings;
-(void)recacheFontSize;
-(void)recacheDisplayName;
-(void)recacheQuoteSyntax;
-(void)recacheDateFormatStyle;
-(BOOL)soundEffectsEnabled;
@end

