/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TweetieStatusStreamViewController.h"

@class TwitterList;

__attribute__((visibility("hidden")))
@interface TweetieListViewController : TweetieStatusStreamViewController {
@private
	TwitterList* list;
}
@property(retain, nonatomic) TwitterList* list;
-(void)dealloc;
-(void)_updateTitle;
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
-(id)statusStream;
-(void)viewWillAppear:(BOOL)view;
-(void)compose:(id)compose;
-(void)flip:(id)flip;
-(void)followList:(id)list;
-(void)unfollowList:(id)list;
-(void)confirmFollow:(id)follow info:(id)info;
-(void)confirmUnfollow:(id)unfollow info:(id)info;
@end

