/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class TweetiePromotedButton, ABCallback, TwitterTrend;

__attribute__((visibility("hidden")))
@interface TweetieTrendCell : UITableViewCell {
@private
	TwitterTrend* trend;
	TweetiePromotedButton* promotedLabel;
	ABCallback* promotedLabelCallback;
}
@property(retain, nonatomic) TwitterTrend* trend;
@property(retain, nonatomic) ABCallback* promotedLabelCallback;
+(id)cellIdentifier;
+(id)dequeueCellForTableView:(id)tableView;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(void)update;
-(void)didClickPromotedLabel:(id)label;
-(void)dealloc;
@end

