/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TweetieStatusStreamViewController.h"

@class TwitterAccountStream;

__attribute__((visibility("hidden")))
@interface TweetieRetweetStreamViewController : TweetieStatusStreamViewController {
@private
	int streamType;
	TwitterAccountStream* stream;
}
@property(assign, nonatomic) int streamType;
-(void)dealloc;
-(void)_updateTitle;
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
-(void)viewWillAppear:(BOOL)view;
-(id)statusStream;
@end

