/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "ABStaticTableViewController.h"
#import "TweetieAddAccountAdvancedViewControllerDelegate.h"
#import "UITextFieldDelegate.h"

@class UIBarButtonItem, NSString, UITextField, ABHUD;
@protocol TweetieAddAccountViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface TweetieAddAccountViewController : ABStaticTableViewController <UITextFieldDelegate, TweetieAddAccountAdvancedViewControllerDelegate> {
@private
	id<TweetieAddAccountViewControllerDelegate> delegate;
	UIBarButtonItem* saveButton;
	UITextField* usernameField;
	UITextField* passwordField;
	NSString* apiEndpointText;
	NSString* searchAPIEndpointText;
	BOOL hidesCancelButton;
	ABHUD* hud;
}
@property(assign, nonatomic) id<TweetieAddAccountViewControllerDelegate> delegate;
@property(assign, nonatomic) BOOL hidesCancelButton;
-(void)dealloc;
-(void)loadTableView;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)advanced:(id)advanced;
-(void)tweetieAddAccountAdvancedViewControllerDismiss:(id)dismiss;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(BOOL)canSubmit;
-(void)_updateSaveButton;
-(void)viewDidAppear:(BOOL)view;
-(void)cancel:(id)cancel;
-(void)save:(id)save;
-(void)didVerifyXAuth:(id)auth info:(id)info;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)textFieldShouldReturn:(id)textField;
@end

