/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TweetieSearchAllTweetsController.h"

@class CLLocation, MKPlacemark;

__attribute__((visibility("hidden")))
@interface TweetieSearchNearbyController : TweetieSearchAllTweetsController {
@private
	id gpsRequestToken;
	MKPlacemark* mostRecentPlacemark;
	CLLocation* mostRecentLocation;
}
@property(retain, nonatomic) MKPlacemark* mostRecentPlacemark;
@property(retain, nonatomic) CLLocation* mostRecentLocation;
-(void)dealloc;
-(BOOL)_isNearbySearch;
-(void)startSearch:(id)search;
-(id)nearString;
-(void)locationUpdate:(id)update;
@end

