/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIView.h>

@class NSString, ABCallback;

__attribute__((visibility("hidden")))
@interface TweetieUserProfile4WayCornerView : UIView {
@private
	NSString* bigText;
	NSString* littleText;
	int cornerMask;
	ABCallback* callback;
	BOOL highlighted;
}
@property(copy, nonatomic) NSString* bigText;
@property(copy, nonatomic) NSString* littleText;
@property(assign, nonatomic) int cornerMask;
@property(assign, nonatomic) BOOL highlighted;
@property(retain, nonatomic) ABCallback* callback;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)_updateAX;
-(void)drawRect:(CGRect)rect;
-(id)buttonView;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
@end

