/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MKMapViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "Twitter-Structs.h"
#import "ABStaticTableViewController.h"

@class NSArray, TwitterAccount, UITableViewCell, UIBarButtonItem, ABHUD, TwitterPlace, NSString, UITextField;
@protocol ABPlacePickerDelegate;

__attribute__((visibility("hidden")))
@interface TweetieAddPlaceViewController : ABStaticTableViewController <MKMapViewDelegate, UITextFieldDelegate> {
@private
	TwitterPlace* pickedPlace;
	NSString* token;
	UITextField* nameField;
	UITextField* addressField;
	UIBarButtonItem* saveButton;
	UITableViewCell* mapView;
	id<ABPlacePickerDelegate> delegate;
	ABHUD* hud;
	TwitterAccount* account;
	NSArray* similarPlaces;
	NSString* initialText;
}
@property(retain, nonatomic) TwitterPlace* pickedPlace;
@property(retain, nonatomic) NSString* token;
@property(retain, nonatomic) NSString* initialText;
@property(assign, nonatomic) id<ABPlacePickerDelegate> delegate;
@property(retain, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) NSArray* similarPlaces;
-(id)init;
-(void)dealloc;
-(id)mapView:(id)view viewForAnnotation:(id)annotation;
-(void)loadTableView;
-(void)viewDidLoad;
-(BOOL)textFieldShouldReturn:(id)textField;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)save:(id)save;
-(void)didGetToken:(id)token info:(id)info;
-(void)didFindContainer:(id)container info:(id)info;
-(void)placeDidSave:(id)place info:(id)info;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
@end

