/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "Twitter-Structs.h"
#import "MKMapViewDelegate.h"
#import "ABStaticTableViewController.h"

@class TweetieAddPlaceViewController, NSArray, NSString, TwitterAccount, ABHUD, TwitterPlace;

__attribute__((visibility("hidden")))
@interface TweetieSimilarPlacesViewController : ABStaticTableViewController <MKMapViewDelegate, UITextFieldDelegate> {
@private
	TwitterPlace* pickedPlace;
	NSString* placeName;
	NSString* placeAddress;
	NSArray* similarPlaces;
	NSString* token;
	NSString* containedWithin;
	TweetieAddPlaceViewController* addPlaceController;
	ABHUD* hud;
	TwitterAccount* account;
}
@property(retain, nonatomic) TwitterPlace* pickedPlace;
@property(retain, nonatomic) NSString* placeName;
@property(retain, nonatomic) NSString* placeAddress;
@property(retain, nonatomic) NSArray* similarPlaces;
@property(retain, nonatomic) NSString* token;
@property(retain, nonatomic) TweetieAddPlaceViewController* addPlaceController;
@property(retain, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) NSString* containedWithin;
-(id)init;
-(void)dealloc;
-(void)loadTableView;
-(void)viewDidLoad;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)save:(id)save;
-(void)didSelectSimilarPlace:(id)place;
-(void)placeDidSave:(id)place info:(id)info;
@end

