/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABWebViewController.h"

@class TwitterStatus, TwitterAccount;

__attribute__((visibility("hidden")))
@interface TweetieWebViewController : ABWebViewController {
@private
	TwitterAccount* account;
	TwitterStatus* sourceStatus;
	BOOL hasProvidedReferer;
}
@property(retain, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) TwitterStatus* sourceStatus;
-(void)dealloc;
-(void)setRootURL:(id)url;
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
-(id)entityForShowingLinksActionSheet;
-(id)URLForShowingLinksActionSheet;
-(void)action:(id)action;
-(void)openLatitude:(double)latitude longitude:(double)longitude;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)openExternalURL:(id)url;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(unsigned)type;
-(BOOL)shouldStartLoadWithURL:(id)url;
@end

