/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TweetieStatusCell.h"
#import "Twitter-Structs.h"
#import "ABTableViewCell.h"

@class UIView, TwitterStatus, TwitterAccount;
@protocol TweetieStatusCellContextActionDelegate;

__attribute__((visibility("hidden")))
@interface TweetieStatusCell : ABTableViewCell {
@private
	id<TweetieStatusCellContextActionDelegate> contextActionDelegate;
	TwitterAccount* account;
	TwitterStatus* status;
	BOOL disableMentionHighlighting;
	UIView* contextModeView;
}
@property(retain, nonatomic) TwitterStatus* status;
@property(retain, nonatomic) TwitterAccount* account;
@property(assign, nonatomic) id<TweetieStatusCellContextActionDelegate> contextActionDelegate;
@property(assign, nonatomic) BOOL disableMentionHighlighting;
+(id)textFont;
+(id)nameFont;
+(id)dateFont;
+(CGRect)textRectGivenTotalWidth:(float)width;
+(float)heightForStatus:(id)status inTableView:(id)tableView;
-(void)dealloc;
-(void)_animateTransition:(int)transition;
-(void)beginContextMode;
-(void)endContextMode;
-(void)userDidUpdateNotification:(id)user;
-(void)drawContentView:(CGRect)view;
@end

@interface TweetieStatusCell (Drawing)
+(void)initialize;
-(id)displayNameForUser:(id)user;
-(void)displayDate:(id*)date alt:(id*)alt;
-(void)drawContent_simple:(CGRect)simple;
@end

