/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TweetieStatusStreamViewController.h"

@class TwitterUser, TwitterUserTimelineStream;

__attribute__((visibility("hidden")))
@interface TweetieUserRecentsViewController : TweetieStatusStreamViewController {
@private
	TwitterUser* user;
	TwitterUserTimelineStream* stream;
}
@property(retain, nonatomic) TwitterUser* user;
-(void)dealloc;
-(id)scribePage;
-(id)scribeSection;
-(id)statusStream;
-(void)recordImpressionFromReferringEvent:(id)referringEvent;
@end

