/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "Tweetie2AppDelegate.h"
#import "TwitterCommonAppDelegate.h"

@class TwitterComposition, TweetieNavigationController, NSString, UIWindow;

__attribute__((visibility("hidden")))
@interface Tweetie2AppDelegate : TwitterCommonAppDelegate {
@private
	UIWindow* window;
	TweetieNavigationController* navigationController;
	TwitterComposition* currentComposition;
	NSString* lastComposeAccountUsername;
}
@property(retain, nonatomic) TwitterComposition* currentComposition;
@property(copy, nonatomic) NSString* lastComposeAccountUsername;
@property(retain, nonatomic) TweetieNavigationController* navigationController;
-(BOOL)application:(id)application didFinishLaunchingWithOptions:(id)options;
-(void)_logLoadedViewController;
-(void)_resetImpressionLog;
-(void)_handleOpenURL:(id)url;
-(void)_saveState;
-(void)dealloc;
@end

@interface Tweetie2AppDelegate (Push)
@end

