/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TweetieStatusStreamViewController.h"
#import "UIActionSheetDelegate.h"

@class TwitterStatus, TwitterConversationStream;

__attribute__((visibility("hidden")))
@interface TweetieReplyChainViewController : TweetieStatusStreamViewController <UIActionSheetDelegate> {
@private
	TwitterStatus* baseStatus;
	TwitterConversationStream* conversationStream;
}
@property(retain, nonatomic) TwitterStatus* baseStatus;
-(id)init;
-(void)dealloc;
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
-(void)viewDidLoad;
-(id)statusStream;
-(id)placeholderSearchStringForFilterBar;
-(BOOL)canLoadNewer;
-(void)reply:(id)reply;
-(void)action:(id)action;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
@end

