/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UINavigationController.h>


__attribute__((visibility("hidden")))
@interface TweetieNavigationController : UINavigationController {
@private
	BOOL didRegisterForCompositionUpdates;
}
-(void)dealloc;
-(id)originatingTweet;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(BOOL)isWorthPoppingToMainScreen;
-(void)pushViewController:(id)controller animated:(BOOL)animated;
-(id)popViewControllerAnimated:(BOOL)animated;
-(id)accountMainViewController;
-(void)_doPop;
-(void)navigationGesture:(id)gesture;
-(void)compositionWillSend:(id)composition;
-(void)compositionDidSend:(id)composition;
-(void)compositionDidUploadAttachment:(id)composition;
-(void)ab_attemptToRecordImpressionFromReferringEvent:(id)referringEvent;
-(void)ab_resetImpression;
@end

