/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIWindow.h>


__attribute__((visibility("hidden")))
@interface TweetieWindow : UIWindow {
@private
	CGPoint startTouch;
	struct {
		unsigned touchState : 3;
	} _flags;
}
-(CGPoint)_ab_convertPoint:(CGPoint)point;
-(void)sendEvent:(id)event;
@end

