/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol TweetieEditProfileViewControllerDelegate
-(void)editProfileControllerWillCancel:(id)editProfileController;
-(void)editProfileControllerDidSave:(id)editProfileController;
@end

