/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class TwitterAccount;

__attribute__((visibility("hidden")))
@interface TweetieAccountCell : UITableViewCell {
@private
	TwitterAccount* account;
}
@property(assign, nonatomic) TwitterAccount* account;
-(void)updateProfileImage;
-(void)willTransitionToState:(unsigned)state;
@end

