/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TweetieAddAccountViewControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "TweetieSearchesViewController.h"
#import "TweetieSignUpViewControllerDelegate.h"

@class TweetieAccountsViewController;

__attribute__((visibility("hidden")))
@interface TweetieLoggedOutViewController : TweetieSearchesViewController <TweetieAddAccountViewControllerDelegate, TweetieSignUpViewControllerDelegate, UINavigationControllerDelegate> {
@private
	TweetieAccountsViewController* accountsViewController;
}
@property(assign, nonatomic) TweetieAccountsViewController* accountsViewController;
-(id)init;
-(void)dealloc;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)view;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)signIn:(id)anIn;
-(void)signUp:(id)up;
-(void)_handleAccount:(id)account;
-(void)signUpViewController:(id)controller didSignUpNewAccount:(id)account;
-(void)addAccountController:(id)controller didAddAccount:(id)account;
-(BOOL)viewControllerShouldBeHidden:(id)viewController;
-(void)navigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)navigationController:(id)controller didShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)_recordImpression;
@end

