/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TweetieUserPerAccountToggleViewController.h"


__attribute__((visibility("hidden")))
@interface TweetieUserFollowViewController : TweetieUserPerAccountToggleViewController {
}
-(void)viewDidLoad;
-(id)footerText;
-(void)toggleOnFromAccount:(id)account;
-(void)toggleOffFromAccount:(id)account;
-(void)requestToggleStateForAccount:(id)account;
-(void)doesFollowResponse:(id)response info:(id)info;
@end

