/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UIButton.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface TweetieComposeTitleView : UIButton {
@private
	NSString* title;
	NSString* subtitle;
	XXStruct_3sqDcB _flags;
}
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) NSString* subtitle;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)_drawPortraitStyle;
-(void)_drawLandscapeStyle;
-(void)drawRect:(CGRect)rect;
-(BOOL)beginTrackingWithTouch:(id)touch withEvent:(id)event;
-(void)endTrackingWithTouch:(id)touch withEvent:(id)event;
-(void)cancelTrackingWithEvent:(id)event;
@end

