/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewController.h"


__attribute__((visibility("hidden")))
@interface TweetieDebugViewController : ABStaticTableViewController {
}
-(void)loadTableView;
-(void)refreshDecider:(id)decider;
-(void)resetChangelogVersion:(id)version;
-(void)configurationUpdated:(id)updated;
-(void)dealloc;
@end

