/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"
#import "ABSubTabBarController.h"
#import "ChooseUserViewControllerDelegate.h"
#import "ABSubTabBarControllerDelegate.h"

@class TwitterAccount;

__attribute__((visibility("hidden")))
@interface TweetieMainViewController : ABSubTabBarController <ABSubTabBarControllerDelegate, UIActionSheetDelegate, ChooseUserViewControllerDelegate> {
@private
	TwitterAccount* account;
}
@property(retain, nonatomic) TwitterAccount* account;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)init;
-(void)dealloc;
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)accountUpdateNotification:(id)notification;
-(void)_doneSending;
-(void)updateSendingProgress:(float)progress;
-(int)numberOfTabsInSubTabController:(id)subTabController;
-(id)subTabBarController:(id)controller accessibilityLabelForIndex:(int)index;
-(id)subTabBarController:(id)controller barItemForIndex:(int)index;
-(id)subTabBarController:(id)controller viewControllerForIndex:(int)index;
-(BOOL)subTabBarController:(id)controller drawGlowForIndex:(int)index;
-(void)subTabBarController:(id)controller didSelectViewControllerAtIndex:(int)index;
-(void)subTabBarController:(id)controller doubleTapTabItemAtIndex:(int)index;
-(void)_newTweet;
-(void)_newDirectMessage;
-(void)compose:(id)compose;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)newConversationWith:(id)with;
-(void)chooseUserViewController:(id)controller didChooseUser:(id)user;
-(void)chooseUserViewController:(id)controller didChooseUsername:(id)username;
-(void)didLoadUserForDirectMessage:(id)directMessage info:(id)info;
-(void)chooseUserViewControllerDidCancel:(id)chooseUserViewController;
@end

