/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"
#import <Foundation/NSObject.h>

@class TwitterEntityURL, UINavigationController, TwitterStatus, UIActionSheet, NSArray, TwitterAccount;

__attribute__((visibility("hidden")))
@interface TweetieLinksAction : NSObject <UIActionSheetDelegate> {
@private
	TwitterAccount* account;
	TwitterStatus* statusContext;
	UINavigationController* navigationController;
	NSArray* links;
	UIActionSheet* _linkSheet;
	UIActionSheet* _linkSelectorSheet;
	TwitterEntityURL* selectedEntityURL;
	BOOL showOpenButton;
	BOOL showOpenInSafariButton;
	BOOL showShareablesButton;
	int openButtonIndex;
	int openInSafariButtonIndex;
	int mailLinkButtonIndex;
	int repostLinkButtonIndex;
	int readLaterButtonIndex;
	int shareablesButtonIndex;
}
@property(retain, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) TwitterStatus* statusContext;
@property(copy, nonatomic) NSArray* links;
@property(assign, nonatomic) BOOL showOpenButton;
@property(assign, nonatomic) BOOL showOpenInSafariButton;
+(id)actionController;
-(void)dealloc;
-(void)specificLinkAction:(id)action;
-(void)expandURLResponse:(id)response info:(id)info;
-(void)linkAction:(id)action;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)showFromNavigationController:(id)navigationController;
@end

