/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewController.h"

@class TwitterAccount;

__attribute__((visibility("hidden")))
@interface TweetieMoreViewController : ABStaticTableViewController {
@private
	TwitterAccount* account;
	id listSection;
	int lastListsCount;
}
@property(retain, nonatomic) TwitterAccount* account;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)dealloc;
-(id)backBarButtonItemTitle;
-(id)lists;
-(void)_setupListSection;
-(void)aboutRED:(id)red;
-(void)joinRED:(id)red;
-(void)sul:(id)sul;
-(void)loadTableView;
-(void)benchmarks:(id)benchmarks;
-(void)accountsAndSettings:(id)settings;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidLoad;
-(void)myProfile:(id)profile;
-(void)favorites:(id)favorites;
-(void)drafts:(id)drafts;
-(void)listsDidUpdate:(id)lists;
-(void)viewList:(id)list;
-(void)createList:(id)list;
-(void)createListResponse:(id)response info:(id)info;
@end

