/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABSearchableTableViewController.h"

@class NSMutableSet, NSMutableArray, TwitterAccount, NSArray;

__attribute__((visibility("hidden")))
@interface TweetieUserListViewController : ABSearchableTableViewController {
@private
	TwitterAccount* account;
	NSArray* searchUsers;
	NSArray* nonSearchUsers;
	NSArray* filteredUsers;
	NSMutableSet* simpleFollowSet;
	NSMutableArray* _followButtons;
	float currentProgress;
	struct {
		unsigned mode : 3;
		unsigned isShowingSearchResults : 1;
	} _flags;
}
@property(retain, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) NSArray* searchUsers;
@property(retain, nonatomic) NSArray* nonSearchUsers;
@property(retain, nonatomic) NSArray* filteredUsers;
@property(retain, nonatomic) NSMutableSet* simpleFollowSet;
@property(assign, nonatomic) float currentProgress;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)init;
-(void)dealloc;
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
-(id)arbitraryUserFormatString;
-(id)placeholderSearchStringForFilterBar;
-(BOOL)showComposeButton;
-(void)viewDidLoad;
-(void)compose:(id)compose;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)loadMore:(id)more;
-(id)userForRow:(int)row;
-(void)searchDisplayController:(id)controller didLoadSearchResultsTableView:(id)view;
-(BOOL)couldBeUsername;
-(BOOL)searchDisplayController:(id)controller shouldReloadTableForSearchString:(id)searchString;
-(void)searchDisplayControllerDidBeginSearch:(id)searchDisplayController;
-(void)searchDisplayControllerWillEndSearch:(id)searchDisplayController;
-(id)usernameFromSearchText;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)_updateButtonTitle:(id)title animated:(BOOL)animated;
-(void)follow_unfollow:(id)unfollow;
-(void)updateButtonTitlesForUsernames:(id)usernames;
-(void)userDidFollow:(id)user;
-(void)userDidUnfollow:(id)user;
-(void)disableButtons;
-(void)enableButtons;
-(id)tableView:(id)view cellForUser:(id)user;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)selectUser:(id)user;
-(void)selectUsername:(id)username;
-(BOOL)automaticallyDeselect;
-(void)findUsers;
-(void)browseSUL;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)_returnToFilteringMode;
-(void)findUsersResponse:(id)response info:(id)info;
-(void)searchBarSearchButtonClicked:(id)clicked;
@end

