/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABSearchableTableViewController.h"
#import "UIActionSheetDelegate.h"
#import "Twitter-Structs.h"

@class NSArray, TwitterAccount;

__attribute__((visibility("hidden")))
@interface TweetieMessagesViewController : ABSearchableTableViewController <UIActionSheetDelegate> {
@private
	TwitterAccount* account;
	NSArray* filteredConversations;
	XXStruct_3sqDcB _flags;
}
@property(retain, nonatomic) TwitterAccount* account;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)dealloc;
-(id)backBarButtonItemTitle;
-(void)showActionSheet;
-(void)doubleTappedRepresentativeTabItem;
-(void)markAllAsRead:(id)read;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)ab_attemptToRecordImpressionFromReferringEvent:(id)referringEvent;
-(void)ab_resetImpression;
-(void)viewWillSwitchToAnotherSubTab;
-(void)viewWillDisappear:(BOOL)view;
-(void)searchDisplayController:(id)controller didLoadSearchResultsTableView:(id)view;
-(BOOL)searchDisplayController:(id)controller shouldReloadTableForSearchString:(id)searchString;
-(id)selectedConversation;
-(void)selectConversation:(id)conversation;
-(void)conversationsDidUpdate:(id)conversations;
-(id)conversationAtIndex:(int)index inTableView:(id)tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)updateVisibleUnreadBits:(id)bits;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
@end

