/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <MapKit/MKAnnotationView.h>

@class CALayer;

__attribute__((visibility("hidden")))
@interface TweetieStatusAnnotationView : MKAnnotationView {
@private
	CALayer* funkmaster;
}
-(id)initWithAnnotation:(id)annotation reuseIdentifier:(id)identifier;
-(void)showAnimation:(double)animation;
@end

