/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewController.h"

@class NSString, TwitterAccount;

__attribute__((visibility("hidden")))
@interface TweetieUnknownListViewController : ABStaticTableViewController {
@private
	TwitterAccount* account;
	NSString* listName;
}
@property(retain, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) NSString* listName;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)dealloc;
-(void)loadTableView;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)view;
-(void)listResponse:(id)response info:(id)info;
@end

