/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TweetieUserPerAccountToggleViewControllerDelegate.h"
#import "ABUnknownPersonViewControllerDelegate.h"
#import "ABPersonViewControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "Twitter-Structs.h"
#import "ABStaticTableViewController.h"

@class TwitterUser, TwitterAccount, UILabel, UIButton, UIImageView, UIActionSheet;
@protocol TweetieUserProfileViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface TweetieUserProfileViewController : ABStaticTableViewController <UIActionSheetDelegate, ABPersonViewControllerDelegate, ABUnknownPersonViewControllerDelegate, TweetieUserPerAccountToggleViewControllerDelegate> {
@private
	id<TweetieUserProfileViewControllerDelegate> delegate;
	TwitterAccount* account;
	TwitterUser* user;
	UIButton* _profileImageButton;
	UIButton* _contactCardButton;
	UILabel* _usernameLabel;
	UILabel* _usernameLabel2;
	UILabel* _userNumberLabel;
	UILabel* _bioLabel;
	UIImageView* _protectedView;
	UIImageView* _verifiedView;
	BOOL iFollowThem;
	BOOL iFollowThem_pending;
	BOOL theyFollowMe;
	id bioSection;
	id actionsSection;
	id followButton;
	UIActionSheet* _followSheet;
	UIActionSheet* _unfollowSheet;
	UIActionSheet* _notificationsSheet;
	UIActionSheet* _reportSpamSheet;
	struct {
		unsigned isLoadingNewer : 1;
		unsigned isLoadingOlder : 1;
		unsigned isAtEnd : 1;
	} _flags;
	XXStruct_3sqDcB _impressionFlags;
}
@property(retain, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) TwitterUser* user;
@property(assign, nonatomic) id<TweetieUserProfileViewControllerDelegate> delegate;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)dealloc;
-(BOOL)userIsLoaded;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)userDidUpdate:(id)user;
-(void)_loadFollowStateIfNeededAndPossible;
-(void)_updateFollowButton;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)followStatus:(id)status info:(id)info;
-(void)viewLargeProfileImage:(id)image;
-(BOOL)isMe;
-(void)loadTableView;
-(void)_follow;
-(void)didFollow:(id)follow info:(id)info;
-(id)_originatingTweet;
-(void)follow:(id)follow;
-(void)unfollow:(id)unfollow;
-(void)addToList:(id)list;
-(void)showListList:(id)list;
-(void)usersLists:(id)lists;
-(void)subscribedToLists:(id)lists;
-(void)memberOfLists:(id)lists;
-(void)dismissAddToList:(id)list info:(id)info;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)bio:(id)bio;
-(void)web:(id)web;
-(void)location:(id)location;
-(void)followers:(id)followers;
-(void)following:(id)following;
-(void)favorites:(id)favorites;
-(void)tweets:(id)tweets;
-(void)_showRetweetStreamType:(int)type;
-(void)retweetedToMe:(id)me;
-(void)retweetsOfMe:(id)me;
-(void)retweetedByMe:(id)me;
-(void)tweetblocker:(id)tweetblocker;
-(void)followcost:(id)followcost;
-(void)favrd:(id)favrd;
-(void)overlapr:(id)overlapr;
-(void)reportSpam:(id)spam;
-(void)favstar:(id)favstar;
-(void)tweeteorites:(id)tweeteorites;
-(void)block:(id)block;
-(void)multiFollow:(id)follow;
-(void)dismissPerAccountToggleViewController:(id)controller;
-(void)notification:(id)notification;
-(void)showContactCardAnimated:(BOOL)animated;
-(void)_showContactCardAnimated;
-(void)contactCard:(id)card;
-(BOOL)_actionForPerson:(void*)person property:(int)property identifier:(int)identifier;
-(BOOL)personViewController:(id)controller shouldPerformDefaultActionForPerson:(void*)person property:(int)property identifier:(int)identifier;
-(BOOL)unknownPersonViewController:(id)controller shouldPerformDefaultActionForPerson:(void*)person property:(int)property identifier:(int)identifier;
-(void)unknownPersonViewController:(id)controller didResolveToPerson:(void*)person;
-(void)ab_attemptToRecordImpressionFromReferringEvent:(id)referringEvent;
-(void)ab_resetImpression;
@end

