/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface Tweetshrink : NSObject {
@private
	int difference;
	NSString* text;
}
@property(copy, nonatomic) NSString* text;
+(void)shrink:(id)shrink callback:(id)callback;
+(void)didShrink:(id)shrink info:(id)info;
-(void)dealloc;
-(void)parseXML:(id)xml info:(id)info;
-(int)difference;
@end

