/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol TweetBlockerDelegate
-(void)tweetBlocker:(id)blocker error:(id)error;
-(void)tweetBlockerDidUpdate:(id)tweetBlocker;
@end

