/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"
#import "TweetieStatusStreamViewController.h"
#import "Twitter-Structs.h"
#import "UITextFieldDelegate.h"

@class UIBarButtonItem, TwitterSearch, UIActionSheet;

__attribute__((visibility("hidden")))
@interface TweetieSearchResultsViewController : TweetieStatusStreamViewController <UITextFieldDelegate, UIActionSheetDelegate> {
@private
	TwitterSearch* search;
	UIBarButtonItem* saveSearchButton;
	UIBarButtonItem* moreInfoButton;
	BOOL isTrend;
	UIActionSheet* saveSearchSheet;
	UIActionSheet* removeSavedSearchSheet;
	UIActionSheet* stockInfoSheet;
}
@property(retain, nonatomic) TwitterSearch* search;
@property(assign, nonatomic) BOOL isTrend;
-(void)setupToolbar;
-(id)scribePage;
-(id)scribeSection;
-(id)init;
-(void)dealloc;
-(void)_updateTitle;
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)view;
-(BOOL)isSavedSearch;
-(BOOL)isHashtag;
-(BOOL)definitionsEnabled;
-(BOOL)isStockLink;
-(id)stockSymbol;
-(void)_updateToolbar;
-(void)viewWillAppear:(BOOL)view;
-(id)statusStream;
-(void)compose:(id)compose;
-(void)searchDisplayControllerWillEndSearch:(id)searchDisplayController;
-(void)moreInfo:(id)info;
-(void)defineResponse:(id)response info:(id)info;
-(void)showDefinitonPanelForTerm:(id)term existingDefinition:(id)definition;
-(void)didDefine:(id)define info:(id)info;
-(void)shouldDefine:(id)define info:(id)info;
-(void)willPresentActionSheet:(id)sheet;
-(void)didPresentActionSheet:(id)sheet;
-(void)saveSearch:(id)search;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)actionSheet:(id)sheet didDismissWithButtonIndex:(int)buttonIndex;
-(BOOL)shouldHideHeaderOnLoad;
@end

