/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TweetieAddAccountViewControllerDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import <UIKit/UIViewController.h>

@class UIBarButtonItem, UITableView;

__attribute__((visibility("hidden")))
@interface TweetieAccountsViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, TweetieAddAccountViewControllerDelegate> {
@private
	UITableView* accountsTableView;
	UIBarButtonItem* refreshAllItem;
	BOOL didAddAccountOnce;
	int noAnimationCount;
	BOOL showWelcomeScreen;
}
@property(assign, nonatomic) BOOL showWelcomeScreen;
+(float)tableRowHeight;
+(id)tableView:(id)view cellForAccount:(id)account;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)init;
-(void)dealloc;
-(void)loadView;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)beginLoggedOutStateAnimated:(BOOL)animated;
-(void)viewDidAppear:(BOOL)view;
-(void)settings:(id)settings;
-(void)refreshAll:(id)all;
-(void)settingsDidComplete:(id)complete;
-(void)userDidUpdate:(id)user;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(id)accountForIndex:(int)index;
-(int)rowForAccount:(id)account;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)beginNoAnimation;
-(void)endNoAnimation;
-(BOOL)shouldAnimate;
-(void)viewAccount:(id)account;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForDeleteConfirmationButtonForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view moveRowAtIndexPath:(id)indexPath toIndexPath:(id)indexPath3;
-(void)addAccountForced:(BOOL)forced;
-(void)addAccount:(id)account;
-(void)addAccountController:(id)controller didAddAccount:(id)account;
-(void)welcomeDidEnd:(id)welcome;
@end

