/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class TwitterPlace;

__attribute__((visibility("hidden")))
@interface TweetiePlaceCell : UITableViewCell {
@private
	TwitterPlace* place;
}
@property(retain, nonatomic) TwitterPlace* place;
@end

