/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "Twitter-Structs.h"
#import "UISearchDisplayDelegate.h"
#import "UISearchBarDelegate.h"

@class UISearchDisplayController, TweetiePickPlaceViewController, TwitterPlaceResponse;

__attribute__((visibility("hidden")))
@interface TweetieGeoSearchDelegate : NSObject <UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate, UISearchDisplayDelegate> {
@private
	TwitterPlaceResponse* searchResponse;
	UISearchDisplayController* searchController;
	TweetiePickPlaceViewController* picker;
	BOOL isSearching;
}
@property(retain, nonatomic) UISearchDisplayController* searchController;
@property(retain, nonatomic) TweetiePickPlaceViewController* picker;
-(BOOL)emptyResults;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)grayCell:(id)cell;
-(id)promptCell:(id)cell;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)searchDidLoad:(id)search info:(id)info;
-(void)performSearch;
-(void)searchBarSearchButtonClicked:(id)clicked;
-(void)searchBarCancelButtonClicked:(id)clicked;
-(void)searchBar:(id)bar textDidChange:(id)text;
-(void)searchBarTextDidBeginEditing:(id)searchBarText;
-(BOOL)searchDisplayController:(id)controller shouldReloadTableForSearchString:(id)searchString;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)dealloc;
-(void)tableView:(id)view didDeselectRowAtIndexPath:(id)indexPath;
@end

