/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import <UIKit/UIViewController.h>

@class NSArray, TopTweetsRailView, UISearchBar, UISearchDisplayController, UIImageView, UIView, TwitterAccount, UITableView;

__attribute__((visibility("hidden")))
@interface TweetieSearchesViewController : UIViewController <UITableViewDelegate, UITableViewDataSource> {
@private
	TwitterAccount* account;
	UITableView* _tableView;
	NSArray* trends;
	NSArray* savedSearches;
	UIImageView* searchesHeaderView;
	TopTweetsRailView* trendsHeaderView;
	UIImageView* signupHeaderView;
	UIImageView* shadow;
	UIView* signupContainer;
	UISearchBar* fakeSearchBar;
	UISearchDisplayController* fakeSearchController;
	id searchingController;
	UIView* searchDivider;
	int SignupSection;
	int SavedSearchesSection;
	int TrendsSection;
	int BrowseUsersSection;
	int NumberOfSections;
	BOOL showSavedSearches;
	XXStruct_3sqDcB _impressionFlags;
}
@property(retain, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) NSArray* trends;
@property(retain, nonatomic) NSArray* savedSearches;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)dealloc;
-(id)backBarButtonItemTitle;
-(void)_updateDivider;
-(void)loadView;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)viewDidUnload;
-(void)viewWillAppear:(BOOL)view;
-(void)topTweetsRailView:(id)view selectedTweet:(id)tweet;
-(void)topTweetsRailViewShowAllTopTweets:(id)tweets;
-(void)viewWillDisappear:(BOOL)view;
-(void)reloadSection:(int)section animated:(BOOL)animated;
-(void)trendsDidUpdate:(id)trends;
-(void)savedSearchesDidUpdate:(id)savedSearches;
-(void)topTweetsDidUpdate:(id)topTweets;
-(BOOL)hasTrends;
-(BOOL)hasSavedSearches;
-(id)trendAtIndex:(int)index;
-(id)savedSearchAtIndex:(int)index;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)radar:(id)radar;
-(id)searchField;
-(void)_hideSearchBar;
-(void)viewWillSwitchToAnotherSubTab;
-(id)appropriateSearchDisplayContentsController;
-(void)startSearch:(id)search;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)didTapPromotedLabel:(id)label info:(id)info;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(void)_findFriends;
-(void)sul:(id)sul;
-(void)didLoadFullPlace:(id)place info:(id)info;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForDeleteConfirmationButtonForRowAtIndexPath:(id)indexPath;
-(void)ab_attemptToRecordImpressionFromReferringEvent:(id)referringEvent;
-(void)ab_resetImpression;
-(void)_recordImpression;
@end

