/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewController.h"

@class ABStaticTableViewCheckmarkElement, TwitterAccount, ABStaticTableViewSectionElement;

__attribute__((visibility("hidden")))
@interface TweetiePushSettingsViewController : ABStaticTableViewController {
@private
	ABStaticTableViewSectionElement* mentionsSection;
	ABStaticTableViewCheckmarkElement* followerElement;
	ABStaticTableViewCheckmarkElement* allElement;
	TwitterAccount* account;
}
@property(retain, nonatomic) TwitterAccount* account;
-(id)init;
-(void)updateServer;
-(void)switchedTweets:(id)tweets info:(id)info;
-(void)switchedMessages:(id)messages info:(id)info;
-(void)checkedFollowers:(id)followers info:(id)info;
-(void)checkedAll:(id)all info:(id)info;
-(void)expandMentionLevels;
-(void)hideMentionLevels;
-(void)switchedMentions:(id)mentions info:(id)info;
-(void)refreshMentionLevels;
-(void)loadTableView;
-(void)dealloc;
@end

