/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "ABTableViewCell.h"

@class UIActivityIndicatorView, TwitterDummyGapStatus;

__attribute__((visibility("hidden")))
@interface TweetieStatusGapCell : ABTableViewCell {
@private
	TwitterDummyGapStatus* gapStatus;
	UIActivityIndicatorView* spinner;
}
@property(retain, nonatomic) TwitterDummyGapStatus* gapStatus;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(void)dealloc;
-(void)drawContentView:(CGRect)view;
-(void)_updateSpinner;
-(void)gapStateNotification:(id)notification;
@end

