/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"
#import <Foundation/NSObject.h>

@class ABCallback, UINavigationController, TwitterStatus, UIActionSheet, TwitterAccount;

__attribute__((visibility("hidden")))
@interface TweetieStatusActions : NSObject <UIActionSheetDelegate> {
@private
	UIActionSheet* _retweetSheet;
	UIActionSheet* _actionSheet;
	UIActionSheet* _deleteSheet;
	TwitterStatus* status;
	TwitterAccount* account;
	UINavigationController* navigationController;
	ABCallback* onDelete;
}
+(void)reply:(id)reply account:(id)account sourceNavigationController:(id)controller;
+(void)link:(id)link account:(id)account sourceNavigationController:(id)controller showOpenButton:(BOOL)button;
+(void)user:(id)user account:(id)account sourceNavigationController:(id)controller;
+(void)favorite:(id)favorite account:(id)account sourceNavigationController:(id)controller;
+(void)delete:(id)aDelete account:(id)account sourceNavigationController:(id)controller onDelete:(id)aDelete4;
+(void)retweet:(id)retweet account:(id)account sourceNavigationController:(id)controller;
+(void)action:(id)action account:(id)account sourceNavigationController:(id)controller;
+(void)translationResponse:(id)response info:(id)info;
+(id)emailBodyForStatuses:(id)statuses subject:(id*)subject;
+(void)sendEmailWithStatuses:(id)statuses fromNavigationController:(id)navigationController;
-(void)dealloc;
-(void)delete:(id)aDelete account:(id)account sourceNavigationController:(id)controller onDelete:(id)aDelete4;
-(void)retweet:(id)retweet account:(id)account sourceNavigationController:(id)controller;
-(void)action:(id)action account:(id)account sourceNavigationController:(id)controller;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
@end

