/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewController.h"

@class NSMutableSet, UILabel, UIImageView, UIView, TweetieFindFriendsViewController, TwitterAccount;

__attribute__((visibility("hidden")))
@interface TweetieSULViewController : ABStaticTableViewController {
@private
	TwitterAccount* account;
	BOOL welcomeMode;
	int lastCounter;
	NSMutableSet* simpleFollowSet;
	UILabel* counterLabel;
	UIView* transitionCounterView;
	UIImageView* signupHeaderView;
	UIImageView* shadow;
	UIView* signupContainer;
	TweetieFindFriendsViewController* _findFriendsController;
}
@property(retain, nonatomic) TwitterAccount* account;
@property(assign, nonatomic) BOOL welcomeMode;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)init;
-(void)dealloc;
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
-(int)tableViewStyle;
-(void)loadTableView;
-(int)currentFollowCount;
-(void)_setupWelcomeHeader;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)_showUsersInCategory:(id)category;
-(void)_findFriends:(id)friends;
-(void)categoriesDidUpdate:(id)categories;
-(BOOL)automaticallyDeselect;
@end

