/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "Twitter-Structs.h"
#import "ABStaticTableViewController.h"

@class UIBarButtonItem, NSString, UITextField;
@protocol TweetieSignUpViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface TweetieSignUpViewController : ABStaticTableViewController <UITextFieldDelegate> {
@private
	id<TweetieSignUpViewControllerDelegate> delegate;
	UITextField* fullNameField;
	UITextField* usernameField;
	UITextField* emailField;
	UITextField* passwordField;
	UIBarButtonItem* cancelButton;
	UIBarButtonItem* signUpButton;
	NSString* captchaToken;
	NSString* captchaSolution;
	int signupRetries;
	XXStruct_3sqDcB _flags;
}
@property(assign, nonatomic) id<TweetieSignUpViewControllerDelegate> delegate;
@property(retain, nonatomic) NSString* captchaToken;
@property(retain, nonatomic) NSString* captchaSolution;
-(void)dealloc;
-(void)loadTableView;
-(void)usernameInfo:(id)info;
-(void)cancel:(id)cancel;
-(void)termsOfService:(id)service;
-(void)privacyPolicy:(id)policy;
-(BOOL)canSignup;
-(void)signUp:(id)up;
-(void)makeSignupCall;
-(void)enableButtons;
-(void)signupResponse:(id)response info:(id)info;
-(void)captchaConfirm:(id)confirm info:(id)info;
-(void)_updateSignUpButton;
-(void)viewDidLoad;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)textFieldShouldReturn:(id)textField;
@end

