/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>

@class TweetieComposeViewController;

__attribute__((visibility("hidden")))
@interface TweetieComposeView : UIView {
@private
	TweetieComposeViewController* controller;
}
@property(assign, nonatomic) TweetieComposeViewController* controller;
-(void)layoutSubviews;
@end

