/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TweetieStatusStreamViewController.h"


__attribute__((visibility("hidden")))
@interface TweetieTimelineViewController : TweetieStatusStreamViewController {
}
-(id)scribePage;
-(id)scribeSection;
-(void)recordImpressionFromReferringEvent:(id)referringEvent;
-(id)backBarButtonItemTitle;
-(id)statusStream;
-(id)placeholderSearchStringForFilterBar;
-(void)viewedMostRecent:(id)recent;
@end

