/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "ABStaticTableViewController.h"

@class UIView, NSURL, NSString, UIImage, ABCallback, UITextField;

__attribute__((visibility("hidden")))
@interface TweetieSignUpCaptchaViewController : ABStaticTableViewController {
@private
	NSString* captchaToken;
	NSURL* captchaImageURL;
	UIImage* captchaImage;
	UIView* header;
	UITextField* _solutionField;
	ABCallback* callback;
	XXStruct_3sqDcB _flags;
}
@property(retain, nonatomic) NSString* captchaToken;
@property(retain, nonatomic) NSURL* captchaImageURL;
@property(retain, nonatomic) UIImage* captchaImage;
@property(retain, nonatomic) ABCallback* callback;
-(void)dealloc;
-(void)handleImage:(id)image info:(id)info;
-(void)loadTableView;
-(void)viewDidLoad;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidAppear:(BOOL)view;
-(void)cancel:(id)cancel;
-(void)done:(id)done;
@end

