/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TwitterPadSearchesViewController.h"


__attribute__((visibility("hidden")))
@interface TwitterPadLoggedOutViewController : TwitterPadSearchesViewController {
}
-(BOOL)loggedOutMode;
-(void)addTopSectionTo:(id)to;
-(void)signIn:(id)anIn;
-(void)signUp:(id)up;
@end

