/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TwitterStatusStreamFilter.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface TwitterStatusStreamFilterUserListFilter : TwitterStatusStreamFilter {
@private
	NSArray* users;
}
@property(copy, nonatomic) NSArray* users;
-(void)dealloc;
-(BOOL)validStatus:(id)status;
@end

