/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSDate, TwitterUser;

__attribute__((visibility("hidden")))
@interface TwitterStreamEvent : NSObject {
@private
	TwitterUser* source;
	TwitterUser* target;
	id targetObject;
	int eventType;
	NSDate* date;
}
@property(assign, nonatomic) int eventType;
@property(retain, nonatomic) TwitterUser* source;
@property(retain, nonatomic) TwitterUser* target;
@property(retain, nonatomic) id targetObject;
@property(retain, nonatomic) NSDate* date;
+(id)keepAlive;
+(id)eventFromDictionary:(id)dictionary;
+(id)retweetEvent:(id)event;
-(void)dealloc;
@end

