/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TweetieAddAccountViewControllerDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import <UIKit/UIViewController.h>
#import "UIPopoverControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "TweetieSignUpViewControllerDelegate.h"
#import "ABSwipeColumnViewControllerDelegate.h"
#import "TwitterPadSidebarViewController.h"

@class NSArray, TwitterComposition, TwitterAccount, UITableView, UIButton, UIView, UIActionSheet;

__attribute__((visibility("hidden")))
@interface TwitterPadSidebarViewController : UIViewController <UINavigationControllerDelegate, UITableViewDataSource, UITableViewDelegate, TweetieAddAccountViewControllerDelegate, ABSwipeColumnViewControllerDelegate, UIPopoverControllerDelegate, TweetieSignUpViewControllerDelegate, UIActionSheetDelegate> {
@private
	UITableView* _tableView;
	UIView* bottom;
	TwitterAccount* selectedAccount;
	int selectedItem;
	UIActionSheet* plusActionSheet;
	UIButton* compose;
	UIButton* settings;
	UIButton* plus;
	TwitterAccount* duckie;
	NSArray* categories;
	TwitterComposition* nextComp;
	struct {
		unsigned isLoadingNewer : 1;
		unsigned isLoadingOlder : 1;
		unsigned isAtEnd : 1;
	} _flags;
}
@property(retain, nonatomic) TwitterAccount* selectedAccount;
@property(retain, nonatomic) TwitterComposition* nextComp;
-(id)init;
-(void)dealloc;
-(float)ab_swipeColumnWidth:(int)width;
-(BOOL)hasAccounts;
-(void)_updateBottomView;
-(void)loadView;
-(void)viewDidAppear:(BOOL)view;
-(void)longPress:(id)press;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(void)swipeColumnController:(id)controller willBeginInteractionOnViewController:(id)controller2;
-(void)_showCompose:(id)compose;
-(void)compose:(id)compose;
-(void)_compose;
-(void)plus:(id)plus;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)more:(id)more;
-(void)signin;
-(void)addAccountController:(id)controller didAddAccount:(id)account;
-(void)_firstSelect;
-(id)duckie;
-(void)setup;
-(void)swipeColumnControllerDidHideOverViewController:(id)swipeColumnController;
-(void)_dismissCompose:(id)compose;
-(void)composeViewControllerDidDismiss:(id)composeViewController;
-(void)accountsDidChange;
-(void)settingsDidComplete:(id)complete;
-(void)accountUpdate:(id)update;
-(void)signup;
-(void)signUpViewController:(id)controller didSignUpNewAccount:(id)account;
-(void)welcomeDidEnd:(id)welcome;
-(void)ab_columnViewController:(id)controller willShowOverViewController:(id)controller2 animated:(BOOL)animated;
-(void)ab_columnViewController:(id)controller willHideOverViewController:(id)controller2 animated:(BOOL)animated;
-(int)selectedAccountIndex;
-(id)accountAtIndex:(int)index;
-(id)firstAccount;
-(id)lastAccount;
-(BOOL)itemShouldGlow:(id)item;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)categories;
-(void)suggestionCategoriesResponse:(id)response info:(id)info;
-(CGRect)coordinatesOfMessagesIconForAccount:(id)account;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)redrawAllCells;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)_setNewRoot:(Class)root;
-(void)selectItem:(int)item;
-(void)didSelectRowAtIndexPath:(id)indexPath animated:(BOOL)animated;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
@end

@interface TwitterPadSidebarViewController (OpenURL)
-(void)_handleOpenURL:(id)url;
@end

