/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "ABPlainRowCell.h"

@class TwitterTrend, TweetiePromotedButton;

__attribute__((visibility("hidden")))
@interface TwitterPadTrendRowCell : ABPlainRowCell {
@private
	TwitterTrend* trend;
	TweetiePromotedButton* promotedLabel;
}
@property(retain, nonatomic) TwitterTrend* trend;
-(id)init;
-(void)didClickPromotedLabel:(id)label;
-(void)layoutSubviews;
-(void)dealloc;
@end

