/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TwitterAutocompleteResultItem.h"


__attribute__((visibility("hidden")))
@interface TwitterPlaceAutocompleteResultItem : TwitterAutocompleteResultItem {
@private
	int placeType;
	double latitude;
	double longitude;
}
@property(assign, nonatomic) int placeType;
@property(assign, nonatomic) double latitude;
@property(assign, nonatomic) double longitude;
+(id)itemWithID:(id)anId placeType:(int)type autocompleteText:(id)text subtext:(id)subtext priority:(int)priority latitude:(id)latitude longitude:(id)longitude;
+(id)itemWithPlace:(id)place;
@end

