/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface TwitterTrend : NSObject <NSCoding> {
@private
	NSString* name;
	NSString* query;
	NSString* promotedTrendID;
	NSString* username;
	NSString* userID;
	BOOL hasRecordedImpression;
}
@property(retain, nonatomic) NSString* name;
@property(retain, nonatomic) NSString* query;
@property(retain, nonatomic) NSString* promotedTrendID;
@property(retain, nonatomic) NSString* username;
@property(retain, nonatomic) NSString* userID;
@property(assign, nonatomic) BOOL hasRecordedImpression;
+(id)parseLocalTrends:(id)trends;
+(void)parseLocalTrendsJSON:(id)json info:(id)info;
+(id)parseTrends:(id)trends;
+(void)parseTrendsJSON:(id)json info:(id)info;
+(void)parseOuterTrendsJSONArray:(id)array info:(id)info;
+(void)parseTrendsJSONArray:(id)array info:(id)info;
-(id)initWithCoder:(id)coder;
-(void)dealloc;
-(void)encodeWithCoder:(id)coder;
-(void)parseTrendJSON:(id)json info:(id)info;
-(void)parseTrendPromotedJSON:(id)json info:(id)info;
-(void)parseTrendUserJSON:(id)json info:(id)info;
-(id)description;
-(BOOL)isPromoted;
@end

