/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TwitterStream.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface TwitterAggregateStatusesStream : TwitterStream {
@private
	NSArray* streams;
}
@property(retain, nonatomic) NSArray* streams;
-(void)dealloc;
-(id)statuses;
-(void)streamDidUpdate:(id)stream;
@end

