/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TwitterPadStatusStreamViewController.h"

@class TwitterUser, TwitterUserTimelineStream;

__attribute__((visibility("hidden")))
@interface TwitterPadUserTimelineViewController : TwitterPadStatusStreamViewController {
@private
	TwitterUser* user;
	TwitterUserTimelineStream* stream;
}
@property(retain, nonatomic) TwitterUser* user;
-(void)dealloc;
-(id)statusStream;
-(BOOL)showFilterBar;
@end

