/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSDate;

__attribute__((visibility("hidden")))
@interface TwitterSettings : NSObject {
@private
	BOOL geoEnabled;
	NSDate* lastUpdated;
}
@property(assign, nonatomic) BOOL geoEnabled;
@property(retain, nonatomic) NSDate* lastUpdated;
+(id)settingsWithXML:(id)xml;
-(void)parseSettingsXML:(id)xml info:(id)info;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
@end

