/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <Foundation/NSObject.h>

@class NSDate;

__attribute__((visibility("hidden")))
@interface TwitterConfiguration : NSObject <NSCoding> {
@private
	int shortenedURLLength;
	float scribeInterval;
	NSDate* lastUpdate;
	BOOL scribeEnabled;
}
@property(assign, nonatomic) int shortenedURLLength;
@property(readonly, assign, nonatomic) NSDate* lastUpdate;
@property(assign, nonatomic) float scribeInterval;
@property(assign, nonatomic) BOOL scribeEnabled;
-(id)description;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)nextConfiguration;
-(void)loadMobileConfiguration:(id)configuration;
-(void)parseMobileConfiguration:(id)configuration info:(id)info;
-(void)loadGlobalConfiguration:(id)configuration;
-(void)parseGlobalConfiguration:(id)configuration info:(id)info;
-(BOOL)needsRefresh;
-(void)finishedLoading;
-(void)dealloc;
@end

