/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <Foundation/NSObject.h>

@class TwitterAccount, NSMutableArray;

__attribute__((visibility("hidden")))
@interface TwitterScribe : NSObject <NSCoding> {
@private
	NSMutableArray* eventBuffer;
	TwitterAccount* account;
	int bufferSpinLock;
}
@property(assign, nonatomic) TwitterAccount* account;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)logTweetSend;
-(void)logTweetReply;
-(void)logTweetRetweet;
-(void)logTweetFavorite;
-(void)logTweetOpenLink;
-(void)logUserFollow;
-(void)logUserUnfollow;
-(void)logNotificationOpen;
-(void)logHomeImpressionFromReferringEvent:(id)referringEvent items:(id)items;
-(void)logAction:(id)action page:(id)page section:(id)section;
-(void)logCompositionImpression;
-(void)logFavoritesImpression;
-(void)logQuoteTweet;
-(void)logMessagesImpression;
-(void)logMessagesConversationImpression;
-(void)logMessageSend;
-(void)logUserProfileImpressionForUserID:(id)userID;
-(void)logUserTimelineImpressionFromReferringEvent:(id)referringEvent userID:(id)anId;
-(void)logSearchesHomeImpression;
-(void)logLoggedOutHomepageImpression;
-(void)logTweetDetailsImpressionFromReferringEvent:(id)referringEvent items:(id)items;
-(void)logRequestResponseURL:(id)url statusCode:(int)code networkStatus:(int)status errorMessage:(id)message duration:(double)duration;
-(void)logEvent:(id)event keysAndValues:(id)values;
-(void)dealloc;
-(void)flush;
@end

