/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface TwitterPlaceEntity : NSObject <NSCoding> {
@private
	NSString* _placeID;
	int _startIndex;
	int _endIndex;
}
@property(readonly, assign, nonatomic) NSString* placeID;
@property(assign, nonatomic) int startIndex;
@property(assign, nonatomic) int endIndex;
-(id)initWithPlaceID:(id)placeID startIndex:(int)index endIndex:(int)index3;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)description;
@end

