/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSDate;

__attribute__((visibility("hidden")))
@interface TwitterApplePushDestination : NSObject {
@private
	int enabledFor;
	int availableLevels;
	NSDate* lastRefreshed;
}
@property(retain, nonatomic) NSDate* lastRefreshed;
@property(assign, nonatomic) int enabledFor;
@property(assign, nonatomic) int availableLevels;
@property(assign, nonatomic) BOOL mentionsFromAll;
@property(assign, nonatomic) BOOL mentionsFromFollowing;
@property(assign, nonatomic) BOOL mentions;
@property(assign, nonatomic) BOOL tweets;
@property(assign, nonatomic) BOOL messages;
+(id)defaultApplePushDestination;
+(id)applePushDestinationFromXML:(id)xml;
-(void)parseApplePushDestinationXML:(id)xml info:(id)info;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(BOOL)isAvailable:(int)available;
-(BOOL)needsRefresh;
-(id)enabledSummary;
-(void)dealloc;
@end

