/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>

@class NSString, TwitterAccount, NSArray;

__attribute__((visibility("hidden")))
@interface TwitterListList : NSObject {
@private
	TwitterAccount* account;
	NSString* nextCursor;
	NSString* previousCursor;
	NSArray* lists;
	XXStruct_3sqDcB _listListFlags;
}
@property(assign, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) NSString* nextCursor;
@property(retain, nonatomic) NSString* previousCursor;
@property(copy, nonatomic) NSArray* lists;
-(void)dealloc;
-(void)loadNextOnRequester:(id)requester;
-(void)loadNext;
-(void)didLoadNextListList:(id)list info:(id)info;
@end

