/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABRowViewController.h"
#import "UIPopoverControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "ABUITextViewDelegate.h"
#import "TweetieEditProfileViewControllerDelegate.h"

@class NSArray, TwitterUser, ABRowView, NSError, TwitterAccount, UIButton, UIImageView, UIActionSheet, NSString, ABTableViewPinchPreviewController, TwitterStatus;

__attribute__((visibility("hidden")))
@interface TwitterPadUserViewController : ABRowViewController <UIPopoverControllerDelegate, TweetieEditProfileViewControllerDelegate, ABUITextViewDelegate, UIActionSheetDelegate> {
@private
	TwitterAccount* account;
	TwitterUser* user;
	NSString* username;
	NSString* userID;
	TwitterStatus* statusContext;
	BOOL mini;
	ABTableViewPinchPreviewController* pinchPreviewController;
	UIActionSheet* actionActionSheet;
	UIActionSheet* unfollowActionSheet;
	UIButton* actionButton;
	UIImageView* avatar;
	ABRowView* relationshipInfoGroup;
	ABRowView* similarHeaderRowView;
	ABRowView* similarLoadingRowView;
	ABRowView* listsHeaderRowView;
	ABRowView* listsLoadingRowView;
	BOOL iFollowThem;
	BOOL theyFollowMe;
	struct {
		unsigned char reply;
		unsigned char dm;
		unsigned char notifications;
		unsigned char block;
		unsigned char spam;
	} buttonIndex;
	NSArray* lists;
	NSError* error;
	struct {
		unsigned loading : 1;
		unsigned errorLoading : 1;
		unsigned loadingFollowStatus : 1;
		unsigned errorLoadingFollowStatus : 1;
		unsigned didLoadFollowStatus : 1;
		unsigned loadingLists : 1;
		unsigned errorLoadingLists : 1;
		unsigned didLoadLists : 1;
		unsigned loadingRecs : 1;
		unsigned didLoadRecs : 1;
		unsigned errorLoadingRecs : 1;
	} _flags;
}
@property(retain, nonatomic) NSString* username;
@property(retain, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) NSString* userID;
@property(retain, nonatomic) TwitterUser* user;
@property(retain, nonatomic) TwitterStatus* statusContext;
@property(assign, nonatomic) BOOL mini;
@property(assign, nonatomic) ABTableViewPinchPreviewController* pinchPreviewController;
-(void)dealloc;
-(void)userResponse:(id)response info:(id)info;
-(BOOL)userIsLoaded;
-(BOOL)miniHeader;
-(void)_loadUser;
-(void)_updateAvatar;
-(void)userDidUpdate:(id)user;
-(id)attributedBio;
-(id)originatingTweet;
-(void)viewDidLoad;
-(void)viewWillDisappear:(BOOL)view;
-(BOOL)isMe;
-(void)_loadFollowState;
-(void)_updateFollowButton;
-(void)followStatus:(id)status info:(id)info;
-(void)_loadLists;
-(void)listsResponse:(id)response info:(id)info;
-(void)_loadSimilar;
-(void)similarResponse:(id)response info:(id)info;
-(void)selectRecommendedUser:(id)user;
-(void)selectList:(id)list;
-(float)contentHeight;
-(id)moreInfoGroup;
-(void)loadRowView;
-(void)retry:(id)retry;
-(void)_didDismissPinch_pushColumn:(id)column info:(id)info;
-(void)_pushColumn:(id)column;
-(void)moreInfo:(id)info;
-(void)viewWeb:(id)web;
-(void)profilePic:(id)pic;
-(id)activeRangesForTextRenderer:(id)textRenderer;
-(void)textView:(id)view didTapActiveRange:(id)range;
-(void)rowView:(id)view didSelectChildRow:(id)row;
-(void)follow:(id)follow;
-(void)unfollow:(id)unfollow;
-(void)action:(id)action;
-(void)_showPopover:(id)popover from:(id)from;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)reallyBlock:(id)block info:(id)info;
-(void)tweets:(id)tweets;
-(void)mentions:(id)mentions;
-(void)favorites:(id)favorites;
-(void)followers:(id)followers;
-(void)following:(id)following;
-(void)editProfile:(id)profile;
-(void)editProfileControllerWillCancel:(id)editProfileController;
-(void)editProfileControllerDidSave:(id)editProfileController;
-(void)ab_didPopDetails;
@end

