/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import "TwitterUser.h"
#import <Foundation/NSObject.h>
#import "Twitter-Structs.h"

@class NSString, NSDate, NSURL, ABImage, NSNumber;

__attribute__((visibility("hidden")))
@interface TwitterUser : NSObject {
@private
	NSDate* lastUpdated;
	NSString* userID;
	NSString* username;
	NSURL* profileImageURL;
	NSString* fullName;
	NSString* location;
	NSString* bio;
	NSURL* url;
	NSURL* expandedURL;
	NSNumber* protected;
	NSNumber* verified;
	NSNumber* numberOfFollowers;
	NSNumber* numberOfStatuses;
	NSNumber* numberOfFollowing;
	NSNumber* numberOfFavorites;
	NSDate* createdAt;
	NSNumber* following;
	ABImage* profileImage;
	struct {
		unsigned isLoadingNewer : 1;
		unsigned isLoadingOlder : 1;
		unsigned isAtEnd : 1;
	} _flags;
}
@property(retain, nonatomic) NSDate* lastUpdated;
@property(copy, nonatomic) NSString* userID;
@property(copy, nonatomic) NSString* username;
@property(retain, nonatomic) NSURL* profileImageURL;
@property(copy, nonatomic) NSString* fullName;
@property(copy, nonatomic) NSString* location;
@property(copy, nonatomic) NSString* bio;
@property(retain, nonatomic) NSURL* url;
@property(retain, nonatomic) NSURL* expandedURL;
@property(retain, nonatomic) NSNumber* protected;
@property(retain, nonatomic) NSNumber* verified;
@property(retain, nonatomic) NSNumber* numberOfFollowers;
@property(retain, nonatomic) NSNumber* numberOfStatuses;
@property(retain, nonatomic) NSNumber* numberOfFollowing;
@property(retain, nonatomic) NSNumber* numberOfFavorites;
@property(retain, nonatomic) NSDate* createdAt;
@property(retain, nonatomic) NSNumber* following;
@property(readonly, assign, nonatomic) NSURL* twitterURL;
@property(assign, nonatomic) BOOL isPartialUser;
@property(readonly, assign, nonatomic) NSURL* largeProfileImageURL;
+(id)userWithDictionary:(id)dictionary;
+(id)userWithXML:(id)xml;
+(id)userWithJSON:(id)json;
+(id)usersWithXML:(id)xml;
+(id)parseUsersJSONCallback:(id)callback;
+(id)parseUsersXMLCallback:(id)callback;
+(id)usersWithJSON:(id)json;
+(void)saveAutocompleteUsers:(id)users;
-(id)init;
-(id)parseUserXMLCallback;
-(void)dealloc;
-(id)_profileImage;
-(void)_assimilateUser:(id)user;
-(void)assimilateUser:(id)user;
-(id)description;
-(int)compare:(id)compare;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)lowercaseUsername;
-(BOOL)isNotADummyUser;
-(id)searchSpace;
-(BOOL)matchesSearchString:(id)string;
@end

@interface TwitterUser (Avatar)
@property(readonly, assign, nonatomic) ABImage* plainProfileImage;
@property(readonly, assign, nonatomic) ABImage* profileImage;
-(void)_requestProfileImage;
-(void)purgeCachedAvatar;
-(void)profileImageResponsePostNotification;
-(void)profileImageResponse:(id)response info:(id)info;
-(void)profileImage73Request:(id)request;
-(void)profileImage73Response:(id)response info:(id)info;
@end

@interface TwitterUser (XML)
+(void)parseUsersXML:(id)xml info:(id)info;
-(void)parseUserXML:(id)xml info:(id)info;
@end

@interface TwitterUser (JSON)
+(void)parseUsersJSON:(id)json info:(id)info;
-(void)parseUserJSON:(id)json info:(id)info;
@end

@interface TwitterUser (NSCoding) <NSCoding>
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
@end

@interface TwitterUser (Streams)
@end

