/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "Twitter-Structs.h"
#import "UIActionSheetDelegate.h"
#import <UIKit/UIViewController.h>
#import "UITextViewDelegate.h"

@class UIBarButtonItem, UIView, TwitterDirectMessage, UINavigationBar, TwitterDirectMessageConversation, UITextView, TwitterAccount, UITableView;

__attribute__((visibility("hidden")))
@interface TwitterPadDirectMessageConversationViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UITextViewDelegate, UIActionSheetDelegate> {
@private
	TwitterAccount* account;
	TwitterDirectMessageConversation* conversation;
	UITableView* _tableView;
	UIView* bottomView;
	UITextView* _textView;
	UINavigationBar* _topBar;
	UIBarButtonItem* _send;
	float keyboardHeight;
	BOOL startReplyImmediately;
	struct {
		unsigned isLoading : 1;
		unsigned shouldRemove : 1;
	} _flags;
	TwitterDirectMessage* selectedMessage;
}
@property(retain, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) TwitterDirectMessageConversation* conversation;
@property(assign, nonatomic) BOOL startReplyImmediately;
-(void)dealloc;
-(BOOL)_isInPopover;
-(id)currentComposition;
-(void)loadView;
-(void)_scrollToBottom:(BOOL)bottom;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)conversationDidUpdate:(id)conversation;
-(void)textViewDidChange:(id)textView;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)_updateKeyboardChange:(id)change animated:(BOOL)animated;
-(void)send:(id)send;
-(void)cancel:(id)cancel;
-(void)keyboardShow:(id)show;
-(void)_scrollToBottomAnimated;
-(void)keyboardHide:(id)hide;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)errorButtonTouch:(id)touch;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
@end

