/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TweetieMessagesViewController.h"

@class UIBarButtonItem;

__attribute__((visibility("hidden")))
@interface TwitterPadMessagesViewController : TweetieMessagesViewController {
@private
	UIBarButtonItem* actionButtonItem;
}
-(void)viewDidLoad;
-(void)ab_didPopDetails;
@end

