/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

typedef struct _NSZone NSZone;

typedef struct _NSRange {
	unsigned location;
	unsigned length;
} NSRange;

typedef struct {
	double latitude;
	double longitude;
} XXStruct_zYrK5D;

typedef struct {
	unsigned long _field1;
	id* _field2;
	unsigned long* _field3;
	unsigned long _field4[5];
} XXStruct_kFm5bA;

typedef struct CGPoint {
	float x;
	float y;
} CGPoint;

typedef struct CGSize {
	float width;
	float height;
} CGSize;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct {
	unsigned didRequestTopStatusID : 1;
} XXStruct_3sqDcB;

typedef struct CGImage* CGImageRef;

typedef struct CGContext* CGContextRef;

typedef struct CGAffineTransform {
	float _field1;
	float _field2;
	float _field3;
	float _field4;
	float _field5;
	float _field6;
} CGAffineTransform;

typedef struct UIEdgeInsets {
	float _field1;
	float _field2;
	float _field3;
	float _field4;
} UIEdgeInsets;

typedef struct {
	XXStruct_zYrK5D _field1;
	XXStruct_zYrK5D _field2;
} XXStruct_03F4WD;

typedef struct __CFArray* CFArrayRef;

typedef struct __CTFramesetter* CTFramesetterRef;

typedef struct CGPath* CGPathRef;

typedef struct __CTFrame* CTFrameRef;

typedef struct {
	int _field1;
	int _field2;
} XXStruct_K5nmsA;

typedef struct sqlite3_stmt sqlite3_stmt;

typedef struct sqlite3 sqlite3;

typedef struct yajl_gen_t yajl_gen_t;

typedef struct JKConstPtrRange {
	char* ptr;
	unsigned length;
} JKConstPtrRange;

typedef struct JKConstBuffer {
	JKConstPtrRange bytes;
} JKConstBuffer;

typedef struct JKTokenCacheItem* JKTokenCacheItemRef;

typedef struct JKTokenValue {
	JKConstPtrRange ptrRange;
	unsigned type;
	unsigned hash;
	union {
		long long longLongValue;
		unsigned long long unsignedLongLongValue;
		double doubleValue;
	} number;
	JKTokenCacheItemRef cacheItem;
} JKTokenValue;

typedef struct JKPtrRange {
	char* ptr;
	unsigned length;
} JKPtrRange;

typedef struct JKManagedBuffer {
	JKPtrRange bytes;
	unsigned flags;
	unsigned roundSizeUpToMultipleOf;
} JKManagedBuffer;

typedef struct JKParseToken {
	JKConstPtrRange tokenPtrRange;
	unsigned type;
	JKTokenValue value;
	JKManagedBuffer tokenBuffer;
} JKParseToken;

typedef struct JKObjectStack {
	void** objects;
	void** keys;
	unsigned* cfHashes;
	unsigned count;
	unsigned index;
	unsigned roundSizeUpToMultipleOf;
	unsigned flags;
} JKObjectStack;

typedef struct JKTokenCache {
	JKTokenCacheItemRef items;
	unsigned count;
	unsigned prng_lfsr;
	unsigned char age[1024];
} JKTokenCache;

typedef struct JKObjCImpCache {
	Class NSNumberClass;
	/*function-pointer*/ void* NSNumberAlloc;
	/*function-pointer*/ void* NSNumberInitWithUnsignedLongLong;
} JKObjCImpCache;

@class NSError;
typedef struct JKParseState {
	unsigned _field1;
	JKConstBuffer _field2;
	unsigned _field3;
	unsigned _field4;
	unsigned _field5;
	unsigned _field6;
	unsigned _field7;
	unsigned _field8;
	JKParseToken _field9;
	JKObjectStack _field10;
	JKTokenCache _field11;
	JKObjCImpCache _field12;
	NSError* _field13;
	int _field14;
	BOOL _field15;
} JKParseState;

typedef struct JKHashTableEntry {
	unsigned _field1;
	id _field2;
	id _field3;
} JKHashTableEntry;

typedef struct __SCNetworkReachability* SCNetworkReachabilityRef;

typedef struct in_addr {
	unsigned _field1;
} in_addr;

typedef struct sockaddr_in {
	unsigned char _field1;
	unsigned char _field2;
	unsigned short _field3;
	in_addr _field4;
	BOOL _field5[8];
} sockaddr_in;

typedef struct _CCCryptor* CCCryptorRef;

typedef struct __CTFont* CTFontRef;

typedef struct {
	int _field1;
	int _field2;
	void* _field3;
} XXStruct_Z6OKRC;


