/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TwitterEntity.h"
#import "Twitter-Structs.h"

@class NSURL, NSString;

__attribute__((visibility("hidden")))
@interface TwitterEntityURL : TwitterEntity {
@private
	NSURL* url;
	NSURL* expandedURL;
	NSString* displayURL;
	NSRange rangeInDisplayText;
}
@property(retain, nonatomic) NSURL* url;
@property(retain, nonatomic) NSURL* expandedURL;
@property(retain, nonatomic) NSString* displayURL;
@property(assign, nonatomic) NSRange rangeInDisplayText;
+(void)parseEntityXML:(id)xml info:(id)info;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)parseEntityJSON:(id)json info:(id)info;
-(int)compare:(id)compare;
-(id)displayString;
-(int)rangeFlavor;
-(NSRange)rangeValue;
-(void)parseDict:(id)dict;
-(id)description;
@end

