/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "ABTableViewCell.h"

@class TwitterList;

__attribute__((visibility("hidden")))
@interface TwitterPadSULCategoryCell : ABTableViewCell {
@private
	TwitterList* list;
}
@property(retain, nonatomic) TwitterList* list;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(void)dealloc;
-(void)drawContentView:(CGRect)view;
@end

