/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewController.h"

@class TwitterAccount;

__attribute__((visibility("hidden")))
@interface TwitterPadListsViewController : ABStaticTableViewController {
@private
	TwitterAccount* account;
	id mainSection;
	int lastCount;
}
@property(retain, nonatomic) TwitterAccount* account;
-(void)dealloc;
-(id)lists;
-(int)tableViewStyle;
-(void)_setupMainSection;
-(void)loadTableView;
-(void)viewDidLoad;
-(void)listsDidUpdate:(id)lists;
-(void)selectList:(id)list;
-(BOOL)automaticallyDeselect;
@end

