/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "ABTableViewCell.h"

@class TwitterStatus;

__attribute__((visibility("hidden")))
@interface TwitterStatusCell : ABTableViewCell {
@private
	TwitterStatus* status;
	id delegate;
}
@property(retain, nonatomic) TwitterStatus* status;
@property(assign, nonatomic) id delegate;
-(Class)cellViewClass;
-(void)dealloc;
-(void)userDidUpdate:(id)user;
-(id)ab_copyForStayOnScreen:(BOOL)stayOnScreen;
@end

