/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TwitterPadStatusListViewController.h"
#import "Twitter-Structs.h"

@class TwitterStream;

__attribute__((visibility("hidden")))
@interface TwitterPadStatusStreamViewController : TwitterPadStatusListViewController {
@private
	XXStruct_3sqDcB _streamFlags;
}
@property(readonly, assign, nonatomic) TwitterStream* statusStream;
-(void)dealloc;
-(void)streamDidUpdate:(id)stream;
-(void)streamError:(id)error;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)loadOlder:(id)older;
-(void)loadNewer:(id)newer;
-(void)fillInGap:(id)gap;
-(BOOL)isLoadingNewer;
-(id)lastUpdated;
-(id)autosaveName;
@end

