/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "ABTableViewCell.h"

@class TwitterAccount, TwitterPadSidebarViewController;

__attribute__((visibility("hidden")))
@interface TwitterPadSidebarCell : ABTableViewCell {
@private
	TwitterAccount* account;
	TwitterPadSidebarViewController* delegate;
}
@property(retain, nonatomic) TwitterAccount* account;
@property(assign, nonatomic) TwitterPadSidebarViewController* delegate;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(void)dealloc;
-(BOOL)associatedAccountIsSelected;
-(BOOL)isFirst;
-(BOOL)isLast;
-(void)drawContentView:(CGRect)view;
@end

