/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <Foundation/NSObject.h>

@class NSMutableArray, TwitterAccount, NSTimer;

__attribute__((visibility("hidden")))
@interface Twitter : NSObject <NSCoding> {
@private
	NSMutableArray* accounts;
	TwitterAccount* duckie;
	NSTimer* scribeTimer;
	NSTimer* heartbeatTimer;
	double clockDelta;
}
@property(assign, nonatomic) double clockDelta;
@property(readonly, assign, nonatomic) TwitterAccount* duckie;
+(id)sharedTwitter;
-(void)heartbeat:(id)heartbeat;
-(id)init;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(void)saveStreams;
-(void)shutdown;
-(id)accounts;
-(void)signInWithUsername:(id)username password:(id)password callback:(id)callback;
-(void)didSignIn:(id)anIn info:(id)info;
-(void)addAccount:(id)account;
-(void)removeAccount:(id)account;
-(BOOL)containsAccount:(id)account;
-(id)accountWithUsername:(id)username;
-(id)defaultAccount;
-(void)reorderAccountFromIndex:(int)index toIndex:(int)index2;
-(void)flushScribe:(id)scribe;
-(void)flushScribeInBackground;
-(void)refresh;
-(BOOL)hasFreshMessages;
-(BOOL)hasFreshAnythingApplicableToStatusItem;
-(BOOL)hasFreshAnythingApplicableToDockBadge;
-(BOOL)hasAnythingUnread;
-(void)markAllAsRead;
-(id)cachedUsers;
-(BOOL)canBlock:(id)block;
@end

