/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABImageService.h"


__attribute__((visibility("hidden")))
@interface TwitVid : ABImageService {
}
-(void)authenticateWithAccount:(id)account callback:(id)callback;
-(id)parseAuthenticationData:(id)data;
-(void)parseAuthenticationXML:(id)xml info:(id)info;
-(void)authenticateResponse:(id)response info:(id)info;
-(void)_postVideo:(id)video message:(id)message callback:(id)callback;
-(id)parseVideoResponse:(id)response;
-(void)parseVideoResponseXML:(id)xml info:(id)info;
-(void)postVideoResponse:(id)response info:(id)info;
-(void)postVideo:(id)video associatedMessage:(id)message fromAccount:(id)account callback:(id)callback;
-(void)postVideoAuthenticationResponse:(id)response info:(id)info;
@end

