/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIApplicationDelegate.h"
#import "NSKeyedUnarchiverDelegate.h"
#import "Twitter-Structs.h"
#import "TwitterCommonAppDelegate.h"
#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface TwitterCommonAppDelegate : NSObject <UIApplicationDelegate, NSKeyedUnarchiverDelegate> {
@private
	BOOL handlingURL;
}
+(BOOL)isLoadingViaPush;
+(void)setIsLoadingViaPush:(BOOL)push;
-(void)dealloc;
-(id)applicationStateFile;
-(id)applicationState;
-(void)saveApplicationState:(id)state;
-(id)reloadApplicationState;
-(void)firstLaunch;
-(BOOL)application:(id)application didFinishLaunchingWithOptions:(id)options;
-(void)applicationDidBecomeActive:(id)application;
-(void)applicationWillResignActive:(id)application;
-(void)handleLaunchOptions:(id)options;
-(void)_handleOpenURL:(id)url;
-(void)handleOpenURL:(id)url;
-(BOOL)application:(id)application handleOpenURL:(id)url;
-(BOOL)application:(id)application openURL:(id)url sourceApplication:(id)application3 annotation:(id)annotation;
-(void)_saveState;
-(void)applicationWillTerminate:(id)application;
-(void)applicationDidEnterBackground:(id)application;
-(void)applicationDidReceiveMemoryWarning:(id)application;
-(void)applicationStateDidReload;
-(void)purgeCaches;
-(void)beginNetworkActivity:(id)activity;
-(void)endNetworkActivity:(id)activity;
-(void)errorPostingNotification:(id)notification;
-(void)_logLoadedViewController;
-(void)_resetImpressionLog;
@end

@interface TwitterCommonAppDelegate (Push)
-(void)parsePushDictionary:(id)dictionary sender:(id*)sender recipient:(id*)recipient status:(id*)status;
-(void)updatePushToken:(id)token;
-(void)application:(id)application didRegisterForRemoteNotificationsWithDeviceToken:(id)deviceToken;
-(void)application:(id)application didFailToRegisterForRemoteNotificationsWithError:(id)error;
-(void)refreshPushToken:(BOOL)token;
-(void)application:(id)application didReceiveRemoteNotification:(id)notification;
-(void)handlePushPayload:(id)payload;
@end

