/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TwitterPadStatusStreamViewController.h"


__attribute__((visibility("hidden")))
@interface TwitterPadTimelineViewController : TwitterPadStatusStreamViewController {
}
-(id)statusStream;
-(BOOL)showFilterBar;
-(void)viewDidLoad;
-(void)viewedMostRecent:(id)recent;
@end

