/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>

@class NSString, NSDate, ABHTTPRequest, TwitterSearchStream, TwitterAccount;

__attribute__((visibility("hidden")))
@interface TwitterSearch : NSObject <NSCoding> {
@private
	TwitterAccount* account;
	NSString* searchID;
	NSString* name;
	NSDate* createdAt;
	TwitterSearchStream* stream;
	ABHTTPRequest* liveStream;
	float liveSearchStreamReconnectDelay;
	BOOL droppedLastLiveStreamConnection;
	BOOL supportsLiveStream;
	XXStruct_3sqDcB _flags;
}
@property(copy, nonatomic) NSString* name;
@property(copy, nonatomic) NSString* searchID;
@property(retain, nonatomic) NSDate* createdAt;
@property(assign, nonatomic) TwitterAccount* account;
@property(copy, nonatomic) NSString* geocodeQuery;
@property(copy, nonatomic) NSString* query;
@property(readonly, assign, nonatomic) TwitterSearchStream* stream;
+(id)searchQuery:(id)query account:(id)account via:(id)via;
+(id)searchQuery:(id)query account:(id)account;
+(id)savedSearchesWithXML:(id)xml;
+(void)parseSavedSearchesXML:(id)xml info:(id)info;
+(id)savedSearchWithXML:(id)xml;
+(id)restPrefixOperators;
-(void)setSource:(id)source;
-(BOOL)isConnectedToLiveSearchStream;
-(void)loadNewerForced:(BOOL)forced;
-(BOOL)supportsLiveStream;
-(void)openLiveSearchStream;
-(void)didDropStream:(id)stream info:(id)info;
-(void)_scheduleSearchStreamReconnectAfterDelay:(float)delay;
-(void)_cancelSearchStreamReconnect;
-(void)_reopenStream;
-(void)didReceiveStreamSearchResult:(id)result info:(id)info;
-(void)closeLiveSearchStream;
-(void)parseSavedSearchXML:(id)xml info:(id)info;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)displayName;
-(void)dealloc;
@end

