/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>
#import "UIPopoverControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "ABAutocompleteControllerDelegate.h"
#import "TweetieComposeSwitchAccountViewControllerDelegate.h"
#import "UITextViewDelegate.h"
#import "Twitter-Structs.h"
#import "ABPlacePickerDelegate.h"
#import "TweetieDraftsViewControllerDelegate.h"

@class TwitterAutocompleteController, TwitterComposition, TwitterAccount, UIBarButtonItem, ABHUD, UILabel, UIButton, UIImageView, UIView, UIActionSheet, TwitterPadComposeTextView, UINavigationBar, UIPopoverController;
@protocol TwitterPadComposeViewDelegate;

__attribute__((visibility("hidden")))
@interface TwitterPadComposeViewController : UIViewController <UITextViewDelegate, UIActionSheetDelegate, UIPopoverControllerDelegate, TweetieComposeSwitchAccountViewControllerDelegate, TweetieDraftsViewControllerDelegate, ABAutocompleteControllerDelegate, ABPlacePickerDelegate> {
@private
	id<TwitterPadComposeViewDelegate> delegate;
	id nextComp;
	TwitterAccount* account;
	TwitterComposition* composition;
	UINavigationBar* nav;
	UIView* _notepad;
	UILabel* _counter;
	UIImageView* _curl;
	TwitterPadComposeTextView* _textView;
	UIBarButtonItem* _send;
	UIBarButtonItem* _cancel;
	UILabel* _fromAccountLabel;
	UIButton* draftsButton;
	UIActionSheet* _cancelActionSheet;
	UIPopoverController* _selectAccountPopover;
	UIPopoverController* _draftsPopover;
	ABHUD* hud;
	TwitterAutocompleteController* autocompleteController;
	NSRange selection;
}
@property(assign, nonatomic) id delegate;
@property(retain, nonatomic) id nextComp;
@property(retain, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) TwitterComposition* composition;
@property(readonly, assign, nonatomic) TwitterAutocompleteController* autocompleteController;
-(id)init;
-(void)accountConfigurationDidChange:(id)accountConfiguration;
-(void)dealloc;
-(void)_updateFromAccountLabelText;
-(void)loadView;
-(void)drafts:(id)drafts;
-(void)restoreComposition:(id)composition;
-(void)selectAccount:(id)account;
-(void)dismissAccountSwitcher:(id)switcher;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(void)dismissFirstResponder;
-(void)_columnViewDidBringOverViewOnScreen;
-(void)_columnViewWillBringOverViewOffScreen;
-(void)_send;
-(void)send:(id)send;
-(void)_cancel:(id)cancel;
-(void)cancel:(id)cancel;
-(void)askToDismiss;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)textViewDidChangeSelection:(id)textView;
-(void)textViewDidChange:(id)textView;
-(NSRange)autocompleteController:(id)controller autocompletableRangeForSelection:(NSRange)selection;
-(void)_setCompositionText:(id)text;
-(BOOL)textView:(id)view shouldChangeTextInRange:(NSRange)range replacementText:(id)text;
-(BOOL)textViewShouldEndEditing:(id)textView;
-(void)viewWillDisappear:(BOOL)view;
-(void)autocompleteControllerDidBegin:(id)autocompleteController;
-(void)autocompleteControllerDidEnd:(id)autocompleteController;
-(void)place:(id)place;
-(void)userDidFinishPickingPlace:(id)user;
-(void)handleMedia:(id)media info:(id)info;
-(void)_handleMedia:(id)media;
@end

