/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TwitterUserStream.h"


__attribute__((visibility("hidden")))
@interface TwitterUserFavoritesStream : TwitterUserStream {
@private
	int page;
}
-(void)_loadNewer;
-(void)_loadOlder;
-(void)didLoadOlder;
-(BOOL)supportsFillingInGaps;
-(id)autosaveName;
-(id)emptyStreamMessage;
@end

