/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import "Twitter-Structs.h"
#import "TwitterAccountStream.h"

@class TwitterStatus;

__attribute__((visibility("hidden")))
@interface TwitterConversationStream : TwitterAccountStream <NSCoding> {
@private
	TwitterStatus* baseStatus;
	TwitterStatus* _nextStatus;
}
@property(assign, nonatomic) TwitterStatus* baseStatus;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)getNext;
-(void)handleStatus:(id)status;
-(void)gotNext:(id)next info:(id)info;
-(void)_loadNewer;
-(void)_loadOlder;
-(BOOL)supportsFillingInGaps;
-(id)autosaveName;
@end

