/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TwitterPadStatusStreamViewController.h"

@class TwitterList, TwitterListStream;

__attribute__((visibility("hidden")))
@interface TwitterPadListViewController : TwitterPadStatusStreamViewController {
@private
	TwitterList* list;
	TwitterListStream* stream;
}
@property(retain, nonatomic) TwitterList* list;
-(void)dealloc;
-(id)statusStream;
-(BOOL)showFilterBar;
@end

