/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>
#import "ABActiveTextRange.h"
#import "NSCopying.h"

@class NSString, NSValue;

__attribute__((visibility("hidden")))
@interface TwitterEntity : NSObject <NSCoding, NSCopying, ABActiveTextRange> {
@private
	NSRange range;
}
@property(assign, nonatomic) NSRange range;
@property(readonly, assign, nonatomic) NSRange rangeValue;
@property(readonly, assign, nonatomic) int rangeFlavor;
@property(readonly, assign, nonatomic) NSString* displayString;
@property(readonly, assign, nonatomic) NSValue* rangeNSValue;
+(void)parseEntityXML:(id)xml info:(id)info;
+(void)setIndices:(id)indices parser:(id)parser;
+(void)parseEntitiesXML:(id)xml info:(id)info;
+(void)parseEntityJSON:(id)json info:(id)info;
+(void)parseEntitiesJSON:(id)json info:(id)info;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)copyWithZone:(NSZone*)zone;
-(void)parseIndexJSON:(id)json info:(id)info;
-(void)parseEntityJSON:(id)json info:(id)info;
-(void)parseDict:(id)dict;
@end

