/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>
#import "TwitterDirectMessageConversation.h"

@class TwitterUser, TwitterDirectMessage, NSArray, TwitterComposition, NSMutableArray;

__attribute__((visibility("hidden")))
@interface TwitterDirectMessageConversation : NSObject <NSCoding> {
@private
	TwitterUser* correspondent;
	NSMutableArray* _messages;
	NSMutableArray* _toRemove;
	TwitterComposition* composition;
	struct {
		unsigned isLoading : 1;
		unsigned shouldRemove : 1;
	} _flags;
}
@property(retain, nonatomic) TwitterUser* correspondent;
@property(retain, nonatomic) TwitterComposition* composition;
@property(assign, nonatomic) BOOL needsFullCorrespondant;
@property(readonly, assign, nonatomic) TwitterDirectMessage* mostRecentMessage;
@property(retain, nonatomic) NSArray* messages;
-(id)init;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(id)newestMessageNotFrom:(id)from;
-(int)compare:(id)compare;
-(void)beginAddingMessages;
-(void)addMessage:(id)message;
-(void)endAddingMessages;
-(void)deleteMessage:(id)message;
-(BOOL)isRepliedTo;
-(BOOL)hasUnreadMessages;
-(void)markAsRead;
-(BOOL)matchesSearchString:(id)string;
-(void)sendFromAccount:(id)account;
-(void)_didSend:(id)send info:(id)info;
-(void)replaceComposition:(id)composition withSentMessage:(id)sentMessage;
@end

@interface TwitterDirectMessageConversation (Email)
-(id)emailHTML;
@end

