/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TwitterListList.h"
#import "Twitter-Structs.h"

@class TwitterUser;

__attribute__((visibility("hidden")))
@interface TwitterUserListList : TwitterListList {
@private
	TwitterUser* user;
}
@property(retain, nonatomic) TwitterUser* user;
-(void)dealloc;
@end

