/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TwitterPadSidebarCell.h"


__attribute__((visibility("hidden")))
@interface TwitterPadSidebarAccountCell : TwitterPadSidebarCell {
}
-(void)setAccount:(id)account;
-(void)accountDidUpdate:(id)account;
-(void)accountUserDidUpdate:(id)accountUser;
-(BOOL)isFirst;
-(BOOL)isLast;
-(void)drawContentView:(CGRect)view;
@end

