/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TwitterPadStatusStreamViewController.h"

@class UIBarButtonItem, UIActionSheet, TwitterSearch;

__attribute__((visibility("hidden")))
@interface TwitterPadSearchResultsViewController : TwitterPadStatusStreamViewController {
@private
	TwitterSearch* search;
	UIBarButtonItem* saveSearch;
	UIActionSheet* _saveSearchSheet;
}
@property(retain, nonatomic) TwitterSearch* search;
-(void)dealloc;
-(id)statusStream;
-(void)viewDidLoad;
-(void)viewedMostRecent:(id)recent;
-(BOOL)isHashtag;
-(BOOL)showToolbar;
-(void)_noteSavedSearchesDidChange;
-(BOOL)isSavedSearch;
-(void)_updateSaveSearchButton;
-(void)saveSearch:(id)search;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(id)toolbarView;
@end

