/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABTableViewCellView.h"
#import "Twitter-Structs.h"
#import "UIActionSheetDelegate.h"
#import "ABUITextRendererDelegate.h"

@class TwitterStatus, UIButton, TwitterStatusCell, ABUITextRenderer;

__attribute__((visibility("hidden")))
@interface TwitterStatusCellView : ABTableViewCellView <UIActionSheetDelegate, ABUITextRendererDelegate> {
@private
	ABUITextRenderer* renderer;
	UIButton* avatarButton;
}
@property(readonly, assign, nonatomic) ABUITextRenderer* renderer;
@property(readonly, assign, nonatomic) TwitterStatus* status;
@property(readonly, assign, nonatomic) TwitterStatusCell* statusCell;
+(void)initialize;
-(id)initWithFrame:(CGRect)frame cell:(id)cell;
-(void)dealloc;
-(id)hitStringForRangeValue:(id)rangeValue;
-(BOOL)canBecomeFirstResponder;
-(void)longPress:(id)press;
-(id)activeRanges;
-(id)activeRangesForTextRenderer:(id)textRenderer;
-(CGRect)textRect;
-(void)displayDate:(id*)date alt:(id*)alt;
-(void)drawRect:(CGRect)rect;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)tapAvatar:(id)avatar;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
@end

