/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import "Twitter-Structs.h"
#import <Foundation/NSObject.h>

@class NSString, NSError, NSURL, ABImage;

__attribute__((visibility("hidden")))
@interface TwitterCompositionAttachment : NSObject <NSCoding> {
@private
	NSString* localFile;
	NSURL* localURL;
	BOOL ownsLocalFile;
	NSString* sourceDescription;
	NSURL* remoteURL;
	int size;
	XXStruct_3sqDcB _flags;
	ABImage* thumbnail;
	NSError* uploadError;
}
@property(retain, nonatomic) NSURL* remoteURL;
@property(retain, nonatomic) NSError* uploadError;
@property(readonly, assign, nonatomic) int size;
@property(retain, nonatomic) NSString* sourceDescription;
-(id)initWithCoder:(id)coder;
-(void)dealloc;
-(void)encodeWithCoder:(id)coder;
-(void)setLocalFile:(id)file;
-(void)setLocalURL:(id)url;
-(void)setData:(id)data;
-(id)localFile;
-(id)data;
-(BOOL)isPendingUpload;
-(void)_uploadFromAccount:(id)account associatedMessage:(id)message callback:(id)callback;
-(void)uploadFromAccount:(id)account associatedMessage:(id)message callback:(id)callback;
-(void)didUpload:(id)upload info:(id)info;
-(void)cleanup;
-(id)title;
-(id)thumbnail;
-(int)type;
@end

