/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSArray, ABCallback, NSString;

__attribute__((visibility("hidden")))
@interface TwitterAutocompleteResultsController : NSObject {
@private
	ABCallback* resultsCallback;
	NSString* lastPartialText;
	NSArray* lastResults;
	int lastType;
}
@property(retain, nonatomic) ABCallback* resultsCallback;
-(void)dealloc;
-(void)_returnResults:(id)results;
-(void)setLastPartialText:(id)text;
-(void)setLastResults:(id)results;
-(void)resetAutocompleteResults;
-(void)_appendSearchItem:(id)item type:(int)type;
-(void)_appendSearchResultItems:(id)items type:(int)type;
-(int)updateAutocompleteResults:(id)results searchPlaces:(id)places;
-(int)updateAutocompleteResults:(id)results type:(int)type poiOnly:(BOOL)only;
@end

