/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SearchRowViewDelegate.h"
#import "TopTweetsRailViewDelegate.h"
#import "Twitter-Structs.h"
#import "ABRowViewController.h"

@class ABRowView, TwitterAccount, TopTweetsRailView, TwitterSavedSearchesRowView, TwitterTrendsRowView;

__attribute__((visibility("hidden")))
@interface TwitterPadSearchesViewController : ABRowViewController <TopTweetsRailViewDelegate, SearchRowViewDelegate> {
@private
	TwitterAccount* account;
	ABRowView* everythingContainer;
	TwitterSavedSearchesRowView* savedSearchesRowView;
	TopTweetsRailView* topTweetsRailView;
	TwitterTrendsRowView* trendsRowView;
}
@property(retain, nonatomic) TwitterAccount* account;
-(void)dealloc;
-(BOOL)loggedOutMode;
-(void)addTopSectionTo:(id)to;
-(void)_addTrends;
-(void)_addTopTweets;
-(void)loadRowView;
-(void)rowView:(id)view didSelectChildRow:(id)row;
-(void)ab_didPopDetails;
-(void)viewWillAppear:(BOOL)view;
-(void)topTweetsRailView:(id)view selectedTweet:(id)tweet;
-(void)topTweetsRailViewShowAllTopTweets:(id)tweets;
-(void)topTweetsDidUpdate:(id)topTweets;
-(void)searchRowViewDidBegin:(id)searchRowView;
-(void)searchRowViewDidCancel:(id)searchRowView;
-(void)searchFor:(id)aFor;
-(void)gotoUsername:(id)username;
-(void)searchNearby:(id)nearby coordinates:(XXStruct_zYrK5D)coordinates;
-(void)gotoUser:(id)user;
-(void)goToPromotedTOSViaTrend:(id)promotedTOSViaTrend;
@end

