/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface TwitterChangelog : NSObject {
}
+(BOOL)shouldShowWhatsNew;
+(void)didDismissWhatsNewAlert:(id)alert info:(id)info;
+(void)showWhatsNewWithCallback:(id)callback;
+(void)showWhatsNewWithViewController:(id)viewController account:(id)account;
+(int)changelogVersion;
+(void)updateChangelogVersionPreference;
+(void)resetChangelogVersionPreference;
@end

