/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TwitterDummyAdStatus.h"
#import "TwitterStatus.h"

@class NSString, NSArray, FusionAd;

__attribute__((visibility("hidden")))
@interface TwitterDummyAdStatus : TwitterStatus {
@private
	FusionAd* ad;
}
@property(readonly, assign, nonatomic) FusionAd* ad;
-(id)init;
-(void)dealloc;
@end

@interface TwitterDummyAdStatus (UIAdditions)
-(id)cellForTableView:(id)tableView account:(id)account delegate:(id)delegate disableMentionHighlighting:(BOOL)highlighting;
-(float)heightForRowInTableView:(id)tableView;
@end

