/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "ABRowView.h"

@class TwitterUser;

__attribute__((visibility("hidden")))
@interface TwitterPadUserRowView : ABRowView {
@private
	TwitterUser* user;
}
@property(retain, nonatomic) TwitterUser* user;
-(id)initWithTwitterUser:(id)twitterUser;
-(void)dealloc;
-(void)userDidUpdate:(id)user;
-(void)drawRect:(CGRect)rect;
@end

