/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <Foundation/NSObject.h>

@class TwitterReceivedDirectMessagesStream, TwitterSentDirectMessagesStream, NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface TwitterDirectMessagesConversationManager : NSObject <NSCoding> {
@private
	TwitterReceivedDirectMessagesStream* receivedStream;
	TwitterSentDirectMessagesStream* sentStream;
	NSMutableArray* _conversations;
	struct {
		unsigned isLoading : 1;
		unsigned shouldRemove : 1;
	} _flags;
}
@property(readonly, assign, nonatomic) TwitterReceivedDirectMessagesStream* receivedStream;
@property(readonly, assign, nonatomic) TwitterSentDirectMessagesStream* sentStream;
@property(readonly, assign, nonatomic) NSArray* conversations;
-(void)_setupNotifications;
-(id)initWithAccount:(id)account;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)setAccount:(id)account;
-(void)dealloc;
-(void)refresh;
-(void)loadOlder;
-(id)conversationWith:(id)with;
-(void)_postDidUpdateNotification;
-(void)_addStubConversation:(id)conversation;
-(void)addMessages:(id)messages fromMe:(BOOL)me;
-(void)sentDidUpdate:(id)sent;
-(void)receivedDidUpdate:(id)received;
-(id)newestMessageDate;
-(id)newestMessageNotFromMe;
-(id)newestMessageDateNotFromMe;
-(void)_deleteMessage:(id)message;
-(void)deleteMessage:(id)message;
-(void)didDeleteMessage:(id)message info:(id)info;
-(void)deleteConversation:(id)conversation;
-(BOOL)hasUnreadMessages;
-(void)markAllAsRead;
-(void)clearCachedUnreadState;
-(id)conversationsMatching:(id)matching;
@end

