/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TwitterDummyStatus.h"
#import "TwitterDummyGapStatus.h"


__attribute__((visibility("hidden")))
@interface TwitterDummyGapStatus : TwitterDummyStatus {
@private
	struct {
		unsigned isLoading : 1;
		unsigned shouldRemove : 1;
	} _gapFlags;
}
@property(assign, nonatomic) BOOL loading;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(BOOL)isGap;
-(BOOL)isEqual:(id)equal;
-(BOOL)_shouldFilterOutOfStream;
@end

@interface TwitterDummyGapStatus (UIAdditions)
-(id)cellForTableView:(id)tableView account:(id)account delegate:(id)delegate disableMentionHighlighting:(BOOL)highlighting;
-(float)heightForRowInTableView:(id)tableView;
@end

