/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TwitterEntity.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TwitterEntityHashtag : TwitterEntity {
@private
	NSString* text;
}
@property(retain, nonatomic) NSString* text;
+(void)parseEntityXML:(id)xml info:(id)info;
-(id)initWithCoder:(id)coder;
-(void)dealloc;
-(void)encodeWithCoder:(id)coder;
-(void)parseEntityJSON:(id)json info:(id)info;
-(void)parseDict:(id)dict;
-(id)displayString;
-(id)description;
-(int)rangeFlavor;
@end

