/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TwitterAccountStream.h"

@class TwitterUser;

__attribute__((visibility("hidden")))
@interface TwitterUserStream : TwitterAccountStream {
@private
	TwitterUser* user;
}
@property(assign, nonatomic) TwitterUser* user;
-(void)dealloc;
-(id)autosaveName;
-(id)emptyStreamMessage;
@end

