/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TwitterAccountStream.h"

@class NSString, NSDate, NSDictionary, NSArray;

__attribute__((visibility("hidden")))
@interface TwitterSearchStream : TwitterAccountStream {
@private
	NSString* query;
	NSDictionary* source;
	NSString* geocodeQuery;
	int page;
	NSDate* freshDate;
	NSArray* searchResults;
	NSArray* promotedSearchResults;
	XXStruct_3sqDcB _searchFlags;
}
@property(copy, nonatomic) NSString* query;
@property(copy, nonatomic) NSString* geocodeQuery;
@property(retain, nonatomic) NSDictionary* source;
-(void)dealloc;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(void)reload;
-(void)loadedSearch:(id)search info:(id)info;
-(void)loadedPromotedSearch:(id)search info:(id)info;
-(void)resultsDidReturn;
-(void)_loadNewer;
-(BOOL)supportsFillingInGaps;
-(void)_loadOlder;
-(void)didLoadOlder;
-(int)unseenStatusCount;
-(BOOL)hasFreshStatuses;
-(void)noteFreshStatuses;
-(id)autosaveName;
-(id)definitiveStatuses:(id)statuses;
-(id)emptyStreamMessage;
@end

