/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UITableView.h>

@class NSIndexPath;

__attribute__((visibility("hidden")))
@interface TwitterPadTableView : UITableView {
@private
	struct {
		NSIndexPath* indexPath;
		CGPoint oldOffset;
		CGRect oldCellRect;
	} stayOnScreen;
	CGRect _lastFrame;
}
-(BOOL)touchesShouldCancelInContentView:(id)touches;
-(void)_saveScrollPosition;
-(void)_restoreScrollPosition;
@end

