/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABTableViewCell.h"
#import "Twitter-Structs.h"
#import "ABUITextRendererDelegate.h"

@class TwitterPadDirectMessageConversationViewController, UIButton, TwitterDirectMessage, ABUITextRenderer, ABCallback;

__attribute__((visibility("hidden")))
@interface TwitterPadDirectMessageCell : ABTableViewCell <ABUITextRendererDelegate> {
@private
	TwitterDirectMessage* message;
	ABUITextRenderer* renderer;
	TwitterPadDirectMessageConversationViewController* conversationViewController;
	UIButton* errorButton;
	ABCallback* errorCallback;
}
@property(assign, nonatomic) TwitterPadDirectMessageConversationViewController* conversationViewController;
@property(retain, nonatomic) ABCallback* errorCallback;
@property(readonly, assign, nonatomic) UIButton* errorButton;
@property(retain, nonatomic) TwitterDirectMessage* message;
+(void)initialize;
+(float)heightForMessage:(id)message inTableView:(id)tableView;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(void)dealloc;
-(void)errorButtonTouch:(id)touch;
-(void)userDidUpdate:(id)user;
-(CGRect)textRect;
-(CGRect)bubbleRect;
-(BOOL)drawRight;
-(void)drawContentView:(CGRect)view;
-(id)activeRanges;
-(id)activeRangesForTextRenderer:(id)textRenderer;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
@end

