/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface TwitterStream : NSObject {
@private
	double cacheTime;
}
@property(assign, nonatomic) double cacheTime;
@property(readonly, assign, nonatomic) NSString* emptyStreamMessage;
@property(retain, nonatomic) NSArray* statuses;
-(void)loadNewer;
-(void)loadOlder;
-(void)fillInGap:(id)gap;
-(BOOL)supportsFillingInGaps;
-(BOOL)hasData;
-(void)didLoadOlder;
-(id)lastUpdated;
-(BOOL)isLoadingNewer;
-(id)autosaveName;
-(void)noteNewTopStatusID:(id)anId;
-(void)requestTopStatusID;
@end

