/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TwitterStream.h"
#import "NSCoding.h"

@class NSArray, TwitterAccount;

__attribute__((visibility("hidden")))
@interface TwitterDirectMessagesStream : TwitterStream <NSCoding> {
@private
	TwitterAccount* account;
	NSArray* messages;
	int page;
	struct {
		unsigned isLoadingNewer : 1;
		unsigned isLoadingOlder : 1;
		unsigned isAtEnd : 1;
	} _flags;
}
@property(assign, nonatomic) TwitterAccount* account;
@property(retain, nonatomic) NSArray* messages;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(id)newestMessageID;
-(id)oldestMessageID;
-(BOOL)forceReadBit;
-(void)addMessages:(id)messages;
-(void)deleteMessage:(id)message;
-(void)messagesResponse:(id)response info:(id)info;
-(void)_loadNewer;
-(void)_loadOlder;
-(void)loadNewer;
-(void)loadOlder;
-(void)loadNewerResponse:(id)response info:(id)info;
-(void)loadOlderResponse:(id)response info:(id)info;
-(id)loadNewerResponseCallback;
-(id)loadOlderResponseCallback;
@end

