/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "ABAutocompleteTableViewDelegate.h"
#import "UIPopoverControllerDelegate.h"
#import <Foundation/NSObject.h>

@class TwitterComposition, TwitterAutocompleteResultsController, TwitterAccount, ABAutocompleteView, ABAutocompletePopover, NSMutableSet, UINavigationController, UITextView;
@protocol ABAutocompleteControllerDelegate, ABPlacePickerDelegate;

__attribute__((visibility("hidden")))
@interface TwitterAutocompleteController : NSObject <ABAutocompleteTableViewDelegate, UIPopoverControllerDelegate> {
@private
	id<ABAutocompleteControllerDelegate, ABPlacePickerDelegate> delegate;
	UITextView* _textView;
	TwitterComposition* _composition;
	TwitterAccount* _account;
	NSMutableSet* _fastPrefixStartSet;
	BOOL isMatchingWord;
	int savedAutocorrectionType;
	int savedAutocapitalizationType;
	UINavigationController* navigationController;
	ABAutocompletePopover* autocompletePopover;
	ABAutocompleteView* autocompleteView;
	TwitterAutocompleteResultsController* resultsController;
	BOOL forcedPlaceAutocomplete;
	BOOL forcedNameAutocomplete;
	BOOL forcedHashtagAutocomplete;
	int autocompleteStartIndex;
	int autocompleteType;
}
@property(assign, nonatomic) id<ABAutocompleteControllerDelegate, ABPlacePickerDelegate> delegate;
@property(assign, nonatomic) UINavigationController* navigationController;
@property(readonly, assign, nonatomic) ABAutocompleteView* autocompleteView;
@property(readonly, assign, nonatomic) ABAutocompletePopover* autocompletePopover;
-(id)init;
-(id)initWithTextView:(id)textView composition:(id)composition account:(id)account;
-(id)initWithFrame:(CGRect)frame textView:(id)view composition:(id)composition account:(id)account;
-(void)dealloc;
-(BOOL)popoverControllerShouldDismissPopover:(id)popoverController;
-(void)updateFastPrefixStartSet:(id)set;
-(id)resultsTableView;
-(void)autocompleteResults:(id)results info:(id)info;
-(void)_end;
-(void)_updateResults:(id)results;
-(void)didChangeSelection;
-(void)_startOrUpdate;
-(void)_forceAutoComplete;
-(void)forceEnablePlaceAutocomplete;
-(void)forceEnableNameAutocomplete;
-(void)forceEnableHashtagAutocomplete;
-(id)wordAtIndex:(int)index;
-(BOOL)wordIsPlaceTrigger:(id)trigger;
-(BOOL)_couldBeAPlainWordMatch:(id)match;
-(void)_updateAutocompleter:(id)autocompleter;
-(void)textViewDidChange:(id)textView;
-(NSRange)insertAutocompleteItem:(id)item atRange:(NSRange)range;
-(void)didSelectAutocompleteItem:(id)item;
-(void)foundUsers:(id)users info:(id)info;
-(void)foundPlaces:(id)places searchQuery:(id)query;
@end

