/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface TwitterPlaceResponse : NSObject {
@private
	NSString* token;
	NSMutableArray* places;
}
@property(retain, nonatomic) NSString* token;
@property(retain, nonatomic) NSMutableArray* places;
-(id)init;
-(void)dealloc;
@end

