/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABStaticTableViewController.h"

@class TwitterAccount;

__attribute__((visibility("hidden")))
@interface TwitterPadMoreViewController : ABStaticTableViewController {
@private
	TwitterAccount* account;
}
@property(retain, nonatomic) TwitterAccount* account;
-(void)dealloc;
-(void)loadTableView;
-(void)viewDidLoad;
@end

