/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TwitterCompositionAttachment.h"


__attribute__((visibility("hidden")))
@interface TwitterCompositionImageAttachment : TwitterCompositionAttachment {
}
-(id)title;
-(void)_uploadFromAccount:(id)account associatedMessage:(id)message callback:(id)callback;
-(void)didUploadImage:(id)image info:(id)info;
-(id)thumbnail;
-(int)type;
@end

