/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSArray, TwitterList, NSString;

__attribute__((visibility("hidden")))
@interface TwitterListUserList : NSObject {
@private
	TwitterList* list;
	NSString* nextCursor;
	NSString* previousCursor;
	NSArray* users;
}
@property(assign, nonatomic) TwitterList* list;
@property(retain, nonatomic) NSString* nextCursor;
@property(retain, nonatomic) NSString* previousCursor;
@property(copy, nonatomic) NSArray* users;
-(void)dealloc;
@end

