/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import "TwitterPadSidebarCell.h"


__attribute__((visibility("hidden")))
@interface TwitterPadSidebarItemCell : TwitterPadSidebarCell {
}
-(BOOL)isLast;
-(id)itemTitle;
-(id)itemImageName;
-(id)itemImage;
-(id)highlightedItemImage;
-(BOOL)_isSubitem;
-(void)drawContentView:(CGRect)view;
@end

