/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABRowView.h"

@class TwitterAccount;

__attribute__((visibility("hidden")))
@interface TwitterTrendsRowView : ABRowView {
@private
	TwitterAccount* account;
}
@property(retain, nonatomic) TwitterAccount* account;
-(void)dealloc;
-(void)setTrends:(id)trends animated:(BOOL)animated;
-(void)trendsUpdate:(id)update;
@end

