/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABImageService.h"


__attribute__((visibility("hidden")))
@interface TwitPicCompatibleImageService : ABImageService {
}
+(id)identifierForURL:(id)url base:(id)base;
-(id)apiRoot;
-(id)apiKey;
-(id)apiKeyParameterName;
-(id)mediaParameterName;
-(id)mediaURLResponseTag;
-(id)messageParameterName;
-(BOOL)useBasicAuth;
-(BOOL)useOAuthEcho;
-(id)OAuthEchoServiceProvider;
-(id)OAuthEchoAuthorizationHeaderForAccount:(id)account;
-(void)addMoarStuff:(id)stuff;
-(BOOL)OAuthEchoInPOST;
-(void)postImage:(id)image associatedMessage:(id)message fromAccount:(id)account callback:(id)callback;
-(void)postVideo:(id)video associatedMessage:(id)message fromAccount:(id)account callback:(id)callback;
-(void)didPostImage:(id)image info:(id)info;
-(void)parseYFrogXML:(id)xml info:(id)info;
@end

