/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABMutableAttributedArray.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface TwitterPaginatedResults : ABMutableAttributedArray {
}
@property(retain, nonatomic) NSString* previousCursor;
@property(retain, nonatomic) NSString* nextCursor;
-(BOOL)isAtEnd;
@end

