/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIActionSheet.h>


@interface UIActionSheet (UIActionSheetAdditions)
+(void)showActionSheetWithTitle:(id)title button:(id)button cancelButton:(id)button3 fromView:(id)view buttonCallback:(id)callback;
@end

