/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIAlertView.h>


@interface UIAlertView (UIAlertViewAdditions)
+(void)_setupAttributionTextForAlertView:(id)alertView;
+(void)showAlertViewWithTitle:(id)title message:(id)message dismissButtonTitle:(id)title3 dismissCallback:(id)callback;
+(void)showAlertViewWithTitle:(id)title message:(id)message buttonTitle:(id)title3 cancelButtonTitle:(id)title4 dismissCallback:(id)callback;
+(id)newMaliciousWarning:(id)warning;
+(void)showAlertViewWithTitle:(id)title message:(id)message dismissButtonTitle:(id)title3;
+(void)showAlertWithError:(id)error;
+(void)showAlertWithError:(id)error dismissCallback:(id)callback;
@end

