/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIColor.h>


@interface UIColor (ABAdditions)
+(id)linkColor;
+(id)blueLabelColor;
+(id)tableFooterLabelColor;
+(id)graphiteColor;
+(id)darkBlueLabelColor;
+(id)grayDividerColor;
+(id)blueDateColor;
+(id)fadedBlueDateColor;
+(id)hashBackgroundColor;
+(id)lightHashBackgroundColor;
+(id)conversationBackgroundColor;
+(id)mailTableViewBackgroundColor;
+(id)embeddedSearchBarTintColor;
+(id)flatPinstripesShadeColor;
+(id)projectREDColor;
+(id)iPadSteel;
+(id)selectedGradientTopBlue;
+(id)selectedGradientBottomBlue;
@end

