/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIImage.h>
#import "Twitter-Structs.h"


@interface UIImage (ABAdditions)
+(id)_ab_imageFromBitmapContext:(CGContextRef)bitmapContext;
-(id)_ab_imageByFindingEdges;
-(id)_ab_gradientShadowImage;
-(id)_ab_squareImageWithHeight:(int)height;
-(id)_ab_fixOrientationConstrainToSize:(int)size compress:(float)compress;
@end

