/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Twitter-Structs.h"
#import <UIKit/UILabel.h>


@interface UILabel (ABAdditions)
+(id)primaryEmbossedBlueLabelWithFrame:(CGRect)frame;
+(id)secondaryEmbossedBlueLabelWithFrame:(CGRect)frame;
+(id)miniEmbossedBlueLabelWithFrame:(CGRect)frame;
@end

