/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UINavigationController.h>


@interface UINavigationController (SaveState)
-(id)initWithDictionary:(id)dictionary;
-(void)saveStateToDictionary:(id)dictionary;
@end

@interface UINavigationController (ABAdditions)
-(id)_ab_setupTransition:(id)transition subtype:(id)subtype onLayer:(id)layer;
-(void)releaseVC:(id)vc;
-(void)replaceTopViewController:(id)controller animation:(id)animation subtype:(id)subtype;
-(void)replaceTopViewController:(id)controller animated:(BOOL)animated;
-(void)replaceTopViewController:(id)controller contentViewTransition:(int)transition duration:(double)duration;
-(void)replaceTopViewControllerDidStop:(id)replaceTopViewController finished:(id)finished context:(id)context;
-(void)replaceModalViewController:(id)controller animated:(BOOL)animated;
-(void)presentModalViewControllerInANavigationController:(id)anavigationController animated:(BOOL)animated;
-(void)resetToDefaultStyleAnimated:(BOOL)defaultStyleAnimated;
@end

@interface UINavigationController (ABPersistence)
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
@end

