/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UISwitch, UILabel, UISlider, UITextField;

@interface UITableViewCell (ABAdditions)
@property(readonly, assign, nonatomic) UILabel* multilineLabel;
@property(readonly, assign, nonatomic) UISlider* accessorySlider;
@property(readonly, assign, nonatomic) UITextField* accessoryTextField;
@property(readonly, assign, nonatomic) UISwitch* accessorySwitch;
@end

@interface UITableViewCell (ABDequeueAdditions)
+(id)ab_cellForTableView:(id)tableView identifier:(id)identifier;
@end

