/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol UIVideoEditorControllerDelegate <NSObject>
@optional
-(void)videoEditorController:(id)controller didSaveEditedVideoToPath:(id)path;
-(void)videoEditorController:(id)controller didFailWithError:(id)error;
-(void)videoEditorControllerDidCancel:(id)videoEditorController;
@end

