/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>

@class ABColumnItem, ABSwipeColumnViewController;

@interface UIViewController (SaveState)
-(id)initWithDictionary:(id)dictionary;
-(void)saveStateToDictionary:(id)dictionary;
-(void)restoreStateFromDictionary:(id)dictionary;
@end

@interface UIViewController (ABViewControllerCoder)
+(id)_ab_restoreFromDictionaryRepresentation:(id)dictionaryRepresentation;
-(id)_ab_dictionaryRepresentation;
@end

@interface UIViewController (ABSubTabBarControllerAdditions)
-(void)viewWillSwitchToAnotherSubTab;
-(id)backBarButtonItemTitle;
-(void)doubleTappedRepresentativeTabItem;
@end

@interface UIViewController (ABSubTabBarController)
-(void)_ab_setParentViewController:(id)controller;
@end

@interface UIViewController (ABPersistence)
-(id)persistentProxy;
-(void)decodeWithPersistentProxy:(id)persistentProxy;
@end

@interface UIViewController (ABColumnItemAdditions)
@property(readonly, assign, nonatomic) ABColumnItem* ab_columnItem;
@end

@interface UIViewController (ABColumnViewControllerAdditions)
@property(readonly, assign, nonatomic) UIViewController* ab_superColumn;
@property(readonly, assign, nonatomic) ABSwipeColumnViewController* ab_columnViewController;
-(void)_ab_setColumnViewController:(id)controller;
-(void)_ab_setSuperColumn:(id)column;
-(void)ab_pushColumn:(id)column animated:(BOOL)animated;
@end

@interface UIViewController (ABSwipeColumnViewController)
-(float)ab_swipeColumnWidth:(int)width;
-(BOOL)ab_shouldShowPullTab;
-(void)ab_didPopDetails;
@end

@interface UIViewController (ImpressionAdditions)
-(id)ab_referrerID;
-(void)ab_attemptToRecordImpressionFromReferringEvent:(id)referringEvent;
-(void)ab_resetImpression;
@end

