/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIWebView.h>

@class UIScrollView;

@interface UIWebView (ABAdditions)
@property(readonly, assign, nonatomic) UIScrollView* _ab_scrollView;
-(void)_ab_killShadows;
@end

