/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSError, NSString;

__attribute__((visibility("hidden")))
@interface WhatTheTrend : NSObject {
@private
	NSString* term;
	NSString* definition;
	NSError* error;
}
@property(copy, nonatomic) NSString* term;
@property(copy, nonatomic) NSString* definition;
@property(retain, nonatomic) NSError* error;
+(void)define:(id)define callback:(id)callback;
+(id)locale;
+(void)define:(id)define as:(id)as username:(id)username userID:(id)anId;
+(void)defineDefinitionResponse:(id)response info:(id)info;
-(void)dealloc;
-(void)defineResponse:(id)response info:(id)info;
-(void)parseJSON:(id)json info:(id)info;
-(void)parseTrend:(id)trend info:(id)info;
-(void)parseBlurb:(id)blurb info:(id)info;
@end

