/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Twitter-Structs.h"


__attribute__((visibility("hidden")))
@interface YAJLGen : NSObject {
@private
	yajl_gen_t* gen_;
	unsigned genOptions_;
}
-(id)init;
-(id)initWithGenOptions:(unsigned)genOptions indentString:(id)string;
-(void)dealloc;
-(void)object:(id)object;
-(void)null;
-(void)_Bool:(BOOL)aBool;
-(void)number:(id)number;
-(void)string:(id)string;
-(void)startDictionary;
-(void)endDictionary;
-(void)startArray;
-(void)endArray;
-(void)clear;
-(id)buffer;
@end

